// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AbilityCustomActivateStartHandler(ReducerEventContext ctx, int abilityCustomId, ulong targetEntityId, ulong timestamp);
        public event AbilityCustomActivateStartHandler? OnAbilityCustomActivateStart;

        public void AbilityCustomActivateStart(int abilityCustomId, ulong targetEntityId, ulong timestamp)
        {
            conn.InternalCallReducer(new Reducer.AbilityCustomActivateStart(abilityCustomId, targetEntityId, timestamp), this.SetCallReducerFlags.AbilityCustomActivateStartFlags);
        }

        public bool InvokeAbilityCustomActivateStart(ReducerEventContext ctx, Reducer.AbilityCustomActivateStart args)
        {
            if (OnAbilityCustomActivateStart == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAbilityCustomActivateStart(
                ctx,
                args.AbilityCustomId,
                args.TargetEntityId,
                args.Timestamp
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AbilityCustomActivateStart : Reducer, IReducerArgs
        {
            [DataMember(Name = "ability_custom_id")]
            public int AbilityCustomId;
            [DataMember(Name = "target_entity_id")]
            public ulong TargetEntityId;
            [DataMember(Name = "timestamp")]
            public ulong Timestamp;

            public AbilityCustomActivateStart(
                int AbilityCustomId,
                ulong TargetEntityId,
                ulong Timestamp
            )
            {
                this.AbilityCustomId = AbilityCustomId;
                this.TargetEntityId = TargetEntityId;
                this.Timestamp = Timestamp;
            }

            public AbilityCustomActivateStart()
            {
            }

            string IReducerArgs.ReducerName => "ability_custom_activate_start";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AbilityCustomActivateStartFlags;
        public void AbilityCustomActivateStart(CallReducerFlags flags) => AbilityCustomActivateStartFlags = flags;
    }
}
