// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminRemoveCollectibleHandler(ReducerEventContext ctx, string identity, int collectibleId, uint quantity);
        public event AdminRemoveCollectibleHandler? OnAdminRemoveCollectible;

        public void AdminRemoveCollectible(string identity, int collectibleId, uint quantity)
        {
            conn.InternalCallReducer(new Reducer.AdminRemoveCollectible(identity, collectibleId, quantity), this.SetCallReducerFlags.AdminRemoveCollectibleFlags);
        }

        public bool InvokeAdminRemoveCollectible(ReducerEventContext ctx, Reducer.AdminRemoveCollectible args)
        {
            if (OnAdminRemoveCollectible == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminRemoveCollectible(
                ctx,
                args.Identity,
                args.CollectibleId,
                args.Quantity
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminRemoveCollectible : Reducer, IReducerArgs
        {
            [DataMember(Name = "identity")]
            public string Identity;
            [DataMember(Name = "collectible_id")]
            public int CollectibleId;
            [DataMember(Name = "quantity")]
            public uint Quantity;

            public AdminRemoveCollectible(
                string Identity,
                int CollectibleId,
                uint Quantity
            )
            {
                this.Identity = Identity;
                this.CollectibleId = CollectibleId;
                this.Quantity = Quantity;
            }

            public AdminRemoveCollectible()
            {
                this.Identity = "";
            }

            string IReducerArgs.ReducerName => "admin_remove_collectible";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminRemoveCollectibleFlags;
        public void AdminRemoveCollectible(CallReducerFlags flags) => AdminRemoveCollectibleFlags = flags;
    }
}
