// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminPatchHousingCostsHandler(ReducerEventContext ctx);
        public event AdminPatchHousingCostsHandler? OnAdminPatchHousingCosts;

        public void AdminPatchHousingCosts()
        {
            conn.InternalCallReducer(new Reducer.AdminPatchHousingCosts(), this.SetCallReducerFlags.AdminPatchHousingCostsFlags);
        }

        public bool InvokeAdminPatchHousingCosts(ReducerEventContext ctx, Reducer.AdminPatchHousingCosts args)
        {
            if (OnAdminPatchHousingCosts == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminPatchHousingCosts(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminPatchHousingCosts : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "admin_patch_housing_costs";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminPatchHousingCostsFlags;
        public void AdminPatchHousingCosts(CallReducerFlags flags) => AdminPatchHousingCostsFlags = flags;
    }
}
