// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminAlpha3ResetOnboardingToThirdTempleQuestHandler(ReducerEventContext ctx, ulong entityId);
        public event AdminAlpha3ResetOnboardingToThirdTempleQuestHandler? OnAdminAlpha3ResetOnboardingToThirdTempleQuest;

        public void AdminAlpha3ResetOnboardingToThirdTempleQuest(ulong entityId)
        {
            conn.InternalCallReducer(new Reducer.AdminAlpha3ResetOnboardingToThirdTempleQuest(entityId), this.SetCallReducerFlags.AdminAlpha3ResetOnboardingToThirdTempleQuestFlags);
        }

        public bool InvokeAdminAlpha3ResetOnboardingToThirdTempleQuest(ReducerEventContext ctx, Reducer.AdminAlpha3ResetOnboardingToThirdTempleQuest args)
        {
            if (OnAdminAlpha3ResetOnboardingToThirdTempleQuest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminAlpha3ResetOnboardingToThirdTempleQuest(
                ctx,
                args.EntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminAlpha3ResetOnboardingToThirdTempleQuest : Reducer, IReducerArgs
        {
            [DataMember(Name = "entity_id")]
            public ulong EntityId;

            public AdminAlpha3ResetOnboardingToThirdTempleQuest(ulong EntityId)
            {
                this.EntityId = EntityId;
            }

            public AdminAlpha3ResetOnboardingToThirdTempleQuest()
            {
            }

            string IReducerArgs.ReducerName => "admin_alpha3_reset_onboarding_to_third_temple_quest";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminAlpha3ResetOnboardingToThirdTempleQuestFlags;
        public void AdminAlpha3ResetOnboardingToThirdTempleQuest(CallReducerFlags flags) => AdminAlpha3ResetOnboardingToThirdTempleQuestFlags = flags;
    }
}
