// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AdminResetAllHerdLocationsHandler(ReducerEventContext ctx);
        public event AdminResetAllHerdLocationsHandler? OnAdminResetAllHerdLocations;

        public void AdminResetAllHerdLocations()
        {
            conn.InternalCallReducer(new Reducer.AdminResetAllHerdLocations(), this.SetCallReducerFlags.AdminResetAllHerdLocationsFlags);
        }

        public bool InvokeAdminResetAllHerdLocations(ReducerEventContext ctx, Reducer.AdminResetAllHerdLocations args)
        {
            if (OnAdminResetAllHerdLocations == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnAdminResetAllHerdLocations(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AdminResetAllHerdLocations : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "admin_reset_all_herd_locations";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AdminResetAllHerdLocationsFlags;
        public void AdminResetAllHerdLocations(CallReducerFlags flags) => AdminResetAllHerdLocationsFlags = flags;
    }
}
