// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheatQuestAdvanceToHandinHandler(ReducerEventContext ctx, ulong playerEntityId, int questDescId);
        public event CheatQuestAdvanceToHandinHandler? OnCheatQuestAdvanceToHandin;

        public void CheatQuestAdvanceToHandin(ulong playerEntityId, int questDescId)
        {
            conn.InternalCallReducer(new Reducer.CheatQuestAdvanceToHandin(playerEntityId, questDescId), this.SetCallReducerFlags.CheatQuestAdvanceToHandinFlags);
        }

        public bool InvokeCheatQuestAdvanceToHandin(ReducerEventContext ctx, Reducer.CheatQuestAdvanceToHandin args)
        {
            if (OnCheatQuestAdvanceToHandin == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCheatQuestAdvanceToHandin(
                ctx,
                args.PlayerEntityId,
                args.QuestDescId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheatQuestAdvanceToHandin : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_entity_id")]
            public ulong PlayerEntityId;
            [DataMember(Name = "quest_desc_id")]
            public int QuestDescId;

            public CheatQuestAdvanceToHandin(
                ulong PlayerEntityId,
                int QuestDescId
            )
            {
                this.PlayerEntityId = PlayerEntityId;
                this.QuestDescId = QuestDescId;
            }

            public CheatQuestAdvanceToHandin()
            {
            }

            string IReducerArgs.ReducerName => "cheat_quest_advance_to_handin";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CheatQuestAdvanceToHandinFlags;
        public void CheatQuestAdvanceToHandin(CallReducerFlags flags) => CheatQuestAdvanceToHandinFlags = flags;
    }
}
