// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheatPavingDestroyHandler(ReducerEventContext ctx, int x, int z, uint dimension);
        public event CheatPavingDestroyHandler? OnCheatPavingDestroy;

        public void CheatPavingDestroy(int x, int z, uint dimension)
        {
            conn.InternalCallReducer(new Reducer.CheatPavingDestroy(x, z, dimension), this.SetCallReducerFlags.CheatPavingDestroyFlags);
        }

        public bool InvokeCheatPavingDestroy(ReducerEventContext ctx, Reducer.CheatPavingDestroy args)
        {
            if (OnCheatPavingDestroy == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCheatPavingDestroy(
                ctx,
                args.X,
                args.Z,
                args.Dimension
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheatPavingDestroy : Reducer, IReducerArgs
        {
            [DataMember(Name = "x")]
            public int X;
            [DataMember(Name = "z")]
            public int Z;
            [DataMember(Name = "dimension")]
            public uint Dimension;

            public CheatPavingDestroy(
                int X,
                int Z,
                uint Dimension
            )
            {
                this.X = X;
                this.Z = Z;
                this.Dimension = Dimension;
            }

            public CheatPavingDestroy()
            {
            }

            string IReducerArgs.ReducerName => "cheat_paving_destroy";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CheatPavingDestroyFlags;
        public void CheatPavingDestroy(CallReducerFlags flags) => CheatPavingDestroyFlags = flags;
    }
}
