// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClaimRenameHandler(ReducerEventContext ctx, PlayerClaimRenameRequest request);
        public event ClaimRenameHandler? OnClaimRename;

        public void ClaimRename(PlayerClaimRenameRequest request)
        {
            conn.InternalCallReducer(new Reducer.ClaimRename(request), this.SetCallReducerFlags.ClaimRenameFlags);
        }

        public bool InvokeClaimRename(ReducerEventContext ctx, Reducer.ClaimRename args)
        {
            if (OnClaimRename == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClaimRename(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClaimRename : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerClaimRenameRequest Request;

            public ClaimRename(PlayerClaimRenameRequest Request)
            {
                this.Request = Request;
            }

            public ClaimRename()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "claim_rename";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClaimRenameFlags;
        public void ClaimRename(CallReducerFlags flags) => ClaimRenameFlags = flags;
    }
}
