// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ClosedListingCollectHandler(ReducerEventContext ctx, SpacetimeDB.Types.PlayerClosedListingCollectRequest request);
        public event ClosedListingCollectHandler? OnClosedListingCollect;

        public void ClosedListingCollect(SpacetimeDB.Types.PlayerClosedListingCollectRequest request)
        {
            conn.InternalCallReducer(new Reducer.ClosedListingCollect(request), this.SetCallReducerFlags.ClosedListingCollectFlags);
        }

        public bool InvokeClosedListingCollect(ReducerEventContext ctx, Reducer.ClosedListingCollect args)
        {
            if (OnClosedListingCollect == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnClosedListingCollect(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ClosedListingCollect : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerClosedListingCollectRequest Request;

            public ClosedListingCollect(PlayerClosedListingCollectRequest Request)
            {
                this.Request = Request;
            }

            public ClosedListingCollect()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "closed_listing_collect";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ClosedListingCollectFlags;
        public void ClosedListingCollect(CallReducerFlags flags) => ClosedListingCollectFlags = flags;
    }
}
