// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ConvertDeedToCollectibleHandler(ReducerEventContext ctx, PlayerConvertDeedToCollectibleRequest request);
        public event ConvertDeedToCollectibleHandler? OnConvertDeedToCollectible;

        public void ConvertDeedToCollectible(PlayerConvertDeedToCollectibleRequest request)
        {
            conn.InternalCallReducer(new Reducer.ConvertDeedToCollectible(request), this.SetCallReducerFlags.ConvertDeedToCollectibleFlags);
        }

        public bool InvokeConvertDeedToCollectible(ReducerEventContext ctx, Reducer.ConvertDeedToCollectible args)
        {
            if (OnConvertDeedToCollectible == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnConvertDeedToCollectible(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ConvertDeedToCollectible : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerConvertDeedToCollectibleRequest Request;

            public ConvertDeedToCollectible(PlayerConvertDeedToCollectibleRequest Request)
            {
                this.Request = Request;
            }

            public ConvertDeedToCollectible()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "convert_deed_to_collectible";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ConvertDeedToCollectibleFlags;
        public void ConvertDeedToCollectible(CallReducerFlags flags) => ConvertDeedToCollectibleFlags = flags;
    }
}
