// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ConvertCollectibleToDeedHandler(ReducerEventContext ctx, SpacetimeDB.Types.PlayerConvertCollectibleToDeedRequest request);
        public event ConvertCollectibleToDeedHandler? OnConvertCollectibleToDeed;

        public void ConvertCollectibleToDeed(SpacetimeDB.Types.PlayerConvertCollectibleToDeedRequest request)
        {
            conn.InternalCallReducer(new Reducer.ConvertCollectibleToDeed(request), this.SetCallReducerFlags.ConvertCollectibleToDeedFlags);
        }

        public bool InvokeConvertCollectibleToDeed(ReducerEventContext ctx, Reducer.ConvertCollectibleToDeed args)
        {
            if (OnConvertCollectibleToDeed == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnConvertCollectibleToDeed(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ConvertCollectibleToDeed : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerConvertCollectibleToDeedRequest Request;

            public ConvertCollectibleToDeed(PlayerConvertCollectibleToDeedRequest Request)
            {
                this.Request = Request;
            }

            public ConvertCollectibleToDeed()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "convert_collectible_to_deed";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ConvertCollectibleToDeedFlags;
        public void ConvertCollectibleToDeed(CallReducerFlags flags) => ConvertCollectibleToDeedFlags = flags;
    }
}
