// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CraftSetPublicHandler(ReducerEventContext ctx, ulong progressiveActionEntityId, bool isPublic);
        public event CraftSetPublicHandler? OnCraftSetPublic;

        public void CraftSetPublic(ulong progressiveActionEntityId, bool isPublic)
        {
            conn.InternalCallReducer(new Reducer.CraftSetPublic(progressiveActionEntityId, isPublic), this.SetCallReducerFlags.CraftSetPublicFlags);
        }

        public bool InvokeCraftSetPublic(ReducerEventContext ctx, Reducer.CraftSetPublic args)
        {
            if (OnCraftSetPublic == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCraftSetPublic(
                ctx,
                args.ProgressiveActionEntityId,
                args.IsPublic
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CraftSetPublic : Reducer, IReducerArgs
        {
            [DataMember(Name = "progressive_action_entity_id")]
            public ulong ProgressiveActionEntityId;
            [DataMember(Name = "is_public")]
            public bool IsPublic;

            public CraftSetPublic(
                ulong ProgressiveActionEntityId,
                bool IsPublic
            )
            {
                this.ProgressiveActionEntityId = ProgressiveActionEntityId;
                this.IsPublic = IsPublic;
            }

            public CraftSetPublic()
            {
            }

            string IReducerArgs.ReducerName => "craft_set_public";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CraftSetPublicFlags;
        public void CraftSetPublic(CallReducerFlags flags) => CraftSetPublicFlags = flags;
    }
}
