// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DeployableMoveHandler(ReducerEventContext ctx, PlayerDeployableMoveRequest request);
        public event DeployableMoveHandler? OnDeployableMove;

        public void DeployableMove(PlayerDeployableMoveRequest request)
        {
            conn.InternalCallReducer(new Reducer.DeployableMove(request), this.SetCallReducerFlags.DeployableMoveFlags);
        }

        public bool InvokeDeployableMove(ReducerEventContext ctx, Reducer.DeployableMove args)
        {
            if (OnDeployableMove == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDeployableMove(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DeployableMove : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerDeployableMoveRequest Request;

            public DeployableMove(PlayerDeployableMoveRequest Request)
            {
                this.Request = Request;
            }

            public DeployableMove()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "deployable_move";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DeployableMoveFlags;
        public void DeployableMove(CallReducerFlags flags) => DeployableMoveFlags = flags;
    }
}
