// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void DiscoverPavementHandler(ReducerEventContext ctx, int pavingId);
        public event DiscoverPavementHandler? OnDiscoverPavement;

        public void DiscoverPavement(int pavingId)
        {
            conn.InternalCallReducer(new Reducer.DiscoverPavement(pavingId), this.SetCallReducerFlags.DiscoverPavementFlags);
        }

        public bool InvokeDiscoverPavement(ReducerEventContext ctx, Reducer.DiscoverPavement args)
        {
            if (OnDiscoverPavement == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnDiscoverPavement(
                ctx,
                args.PavingId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class DiscoverPavement : Reducer, IReducerArgs
        {
            [DataMember(Name = "paving_id")]
            public int PavingId;

            public DiscoverPavement(int PavingId)
            {
                this.PavingId = PavingId;
            }

            public DiscoverPavement()
            {
            }

            string IReducerArgs.ReducerName => "discover_pavement";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags DiscoverPavementFlags;
        public void DiscoverPavement(CallReducerFlags flags) => DiscoverPavementFlags = flags;
    }
}
