// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireCollectHexiteCapsuleHandler(ReducerEventContext ctx, SpacetimeDB.Types.EmpireCollectHexiteCapsuleRequest request);
        public event EmpireCollectHexiteCapsuleHandler? OnEmpireCollectHexiteCapsule;

        public void EmpireCollectHexiteCapsule(SpacetimeDB.Types.EmpireCollectHexiteCapsuleRequest request)
        {
            conn.InternalCallReducer(new Reducer.EmpireCollectHexiteCapsule(request), this.SetCallReducerFlags.EmpireCollectHexiteCapsuleFlags);
        }

        public bool InvokeEmpireCollectHexiteCapsule(ReducerEventContext ctx, Reducer.EmpireCollectHexiteCapsule args)
        {
            if (OnEmpireCollectHexiteCapsule == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireCollectHexiteCapsule(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireCollectHexiteCapsule : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EmpireCollectHexiteCapsuleRequest Request;

            public EmpireCollectHexiteCapsule(EmpireCollectHexiteCapsuleRequest Request)
            {
                this.Request = Request;
            }

            public EmpireCollectHexiteCapsule()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "empire_collect_hexite_capsule";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EmpireCollectHexiteCapsuleFlags;
        public void EmpireCollectHexiteCapsule(CallReducerFlags flags) => EmpireCollectHexiteCapsuleFlags = flags;
    }
}
