// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EmpireSiegeDepletedWatchtowerHandler(ReducerEventContext ctx, SpacetimeDB.Types.EmpireStartSiegeRequest request);
        public event EmpireSiegeDepletedWatchtowerHandler? OnEmpireSiegeDepletedWatchtower;

        public void EmpireSiegeDepletedWatchtower(SpacetimeDB.Types.EmpireStartSiegeRequest request)
        {
            conn.InternalCallReducer(new Reducer.EmpireSiegeDepletedWatchtower(request), this.SetCallReducerFlags.EmpireSiegeDepletedWatchtowerFlags);
        }

        public bool InvokeEmpireSiegeDepletedWatchtower(ReducerEventContext ctx, Reducer.EmpireSiegeDepletedWatchtower args)
        {
            if (OnEmpireSiegeDepletedWatchtower == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEmpireSiegeDepletedWatchtower(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EmpireSiegeDepletedWatchtower : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EmpireStartSiegeRequest Request;

            public EmpireSiegeDepletedWatchtower(EmpireStartSiegeRequest Request)
            {
                this.Request = Request;
            }

            public EmpireSiegeDepletedWatchtower()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "empire_siege_depleted_watchtower";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EmpireSiegeDepletedWatchtowerFlags;
        public void EmpireSiegeDepletedWatchtower(CallReducerFlags flags) => EmpireSiegeDepletedWatchtowerFlags = flags;
    }
}
