// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnemySetHealthBatchHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.EnemySetHealthRequest> requests);
        public event EnemySetHealthBatchHandler? OnEnemySetHealthBatch;

        public void EnemySetHealthBatch(System.Collections.Generic.List<SpacetimeDB.Types.EnemySetHealthRequest> requests)
        {
            conn.InternalCallReducer(new Reducer.EnemySetHealthBatch(requests), this.SetCallReducerFlags.EnemySetHealthBatchFlags);
        }

        public bool InvokeEnemySetHealthBatch(ReducerEventContext ctx, Reducer.EnemySetHealthBatch args)
        {
            if (OnEnemySetHealthBatch == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnemySetHealthBatch(
                ctx,
                args.Requests
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnemySetHealthBatch : Reducer, IReducerArgs
        {
            [DataMember(Name = "requests")]
            public System.Collections.Generic.List<EnemySetHealthRequest> Requests;

            public EnemySetHealthBatch(System.Collections.Generic.List<EnemySetHealthRequest> Requests)
            {
                this.Requests = Requests;
            }

            public EnemySetHealthBatch()
            {
                this.Requests = new();
            }

            string IReducerArgs.ReducerName => "enemy_set_health_batch";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EnemySetHealthBatchFlags;
        public void EnemySetHealthBatch(CallReducerFlags flags) => EnemySetHealthBatchFlags = flags;
    }
}
