// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void EnemyClearAggroHandler(ReducerEventContext ctx, SpacetimeDB.Types.EnemyClearAggroRequest request);
        public event EnemyClearAggroHandler? OnEnemyClearAggro;

        public void EnemyClearAggro(SpacetimeDB.Types.EnemyClearAggroRequest request)
        {
            conn.InternalCallReducer(new Reducer.EnemyClearAggro(request), this.SetCallReducerFlags.EnemyClearAggroFlags);
        }

        public bool InvokeEnemyClearAggro(ReducerEventContext ctx, Reducer.EnemyClearAggro args)
        {
            if (OnEnemyClearAggro == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnEnemyClearAggro(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class EnemyClearAggro : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public EnemyClearAggroRequest Request;

            public EnemyClearAggro(EnemyClearAggroRequest Request)
            {
                this.Request = Request;
            }

            public EnemyClearAggro()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "enemy_clear_aggro";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags EnemyClearAggroFlags;
        public void EnemyClearAggro(CallReducerFlags flags) => EnemyClearAggroFlags = flags;
    }
}
