// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void GenerateDevIslandHandler(ReducerEventContext ctx);
        public event GenerateDevIslandHandler? OnGenerateDevIsland;

        public void GenerateDevIsland()
        {
            conn.InternalCallReducer(new Reducer.GenerateDevIsland(), this.SetCallReducerFlags.GenerateDevIslandFlags);
        }

        public bool InvokeGenerateDevIsland(ReducerEventContext ctx, Reducer.GenerateDevIsland args)
        {
            if (OnGenerateDevIsland == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnGenerateDevIsland(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class GenerateDevIsland : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "generate_dev_island";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags GenerateDevIslandFlags;
        public void GenerateDevIsland(CallReducerFlags flags) => GenerateDevIslandFlags = flags;
    }
}
