// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportKnowledgeItemStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.KnowledgeItemState> records);
        public event ImportKnowledgeItemStateHandler? OnImportKnowledgeItemState;

        public void ImportKnowledgeItemState(System.Collections.Generic.List<SpacetimeDB.Types.KnowledgeItemState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportKnowledgeItemState(records), this.SetCallReducerFlags.ImportKnowledgeItemStateFlags);
        }

        public bool InvokeImportKnowledgeItemState(ReducerEventContext ctx, Reducer.ImportKnowledgeItemState args)
        {
            if (OnImportKnowledgeItemState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportKnowledgeItemState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportKnowledgeItemState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<KnowledgeItemState> Records;

            public ImportKnowledgeItemState(System.Collections.Generic.List<KnowledgeItemState> Records)
            {
                this.Records = Records;
            }

            public ImportKnowledgeItemState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_knowledge_item_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportKnowledgeItemStateFlags;
        public void ImportKnowledgeItemState(CallReducerFlags flags) => ImportKnowledgeItemStateFlags = flags;
    }
}
