// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportEmpireColorsDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.EmpireColorDesc> records);
        public event ImportEmpireColorsDescHandler? OnImportEmpireColorsDesc;

        public void ImportEmpireColorsDesc(System.Collections.Generic.List<SpacetimeDB.Types.EmpireColorDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportEmpireColorsDesc(records), this.SetCallReducerFlags.ImportEmpireColorsDescFlags);
        }

        public bool InvokeImportEmpireColorsDesc(ReducerEventContext ctx, Reducer.ImportEmpireColorsDesc args)
        {
            if (OnImportEmpireColorsDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportEmpireColorsDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportEmpireColorsDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<EmpireColorDesc> Records;

            public ImportEmpireColorsDesc(System.Collections.Generic.List<EmpireColorDesc> Records)
            {
                this.Records = Records;
            }

            public ImportEmpireColorsDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_empire_colors_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportEmpireColorsDescFlags;
        public void ImportEmpireColorsDesc(CallReducerFlags flags) => ImportEmpireColorsDescFlags = flags;
    }
}
