// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportCraftingRecipeDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.CraftingRecipeDesc> records);
        public event ImportCraftingRecipeDescHandler? OnImportCraftingRecipeDesc;

        public void ImportCraftingRecipeDesc(System.Collections.Generic.List<SpacetimeDB.Types.CraftingRecipeDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportCraftingRecipeDesc(records), this.SetCallReducerFlags.ImportCraftingRecipeDescFlags);
        }

        public bool InvokeImportCraftingRecipeDesc(ReducerEventContext ctx, Reducer.ImportCraftingRecipeDesc args)
        {
            if (OnImportCraftingRecipeDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportCraftingRecipeDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportCraftingRecipeDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<CraftingRecipeDesc> Records;

            public ImportCraftingRecipeDesc(System.Collections.Generic.List<CraftingRecipeDesc> Records)
            {
                this.Records = Records;
            }

            public ImportCraftingRecipeDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_crafting_recipe_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportCraftingRecipeDescFlags;
        public void ImportCraftingRecipeDesc(CallReducerFlags flags) => ImportCraftingRecipeDescFlags = flags;
    }
}
