// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportKnowledgeResourceStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<KnowledgeResourceState> records);
        public event ImportKnowledgeResourceStateHandler? OnImportKnowledgeResourceState;

        public void ImportKnowledgeResourceState(System.Collections.Generic.List<KnowledgeResourceState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportKnowledgeResourceState(records), this.SetCallReducerFlags.ImportKnowledgeResourceStateFlags);
        }

        public bool InvokeImportKnowledgeResourceState(ReducerEventContext ctx, Reducer.ImportKnowledgeResourceState args)
        {
            if (OnImportKnowledgeResourceState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportKnowledgeResourceState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportKnowledgeResourceState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<KnowledgeResourceState> Records;

            public ImportKnowledgeResourceState(System.Collections.Generic.List<KnowledgeResourceState> Records)
            {
                this.Records = Records;
            }

            public ImportKnowledgeResourceState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_knowledge_resource_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportKnowledgeResourceStateFlags;
        public void ImportKnowledgeResourceState(CallReducerFlags flags) => ImportKnowledgeResourceStateFlags = flags;
    }
}
