// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportOnboardingStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.OnboardingState> records);
        public event ImportOnboardingStateHandler? OnImportOnboardingState;

        public void ImportOnboardingState(System.Collections.Generic.List<SpacetimeDB.Types.OnboardingState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportOnboardingState(records), this.SetCallReducerFlags.ImportOnboardingStateFlags);
        }

        public bool InvokeImportOnboardingState(ReducerEventContext ctx, Reducer.ImportOnboardingState args)
        {
            if (OnImportOnboardingState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportOnboardingState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportOnboardingState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<OnboardingState> Records;

            public ImportOnboardingState(System.Collections.Generic.List<OnboardingState> Records)
            {
                this.Records = Records;
            }

            public ImportOnboardingState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_onboarding_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportOnboardingStateFlags;
        public void ImportOnboardingState(CallReducerFlags flags) => ImportOnboardingStateFlags = flags;
    }
}
