// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportInteriorInstanceDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.InteriorInstanceDesc> records);
        public event ImportInteriorInstanceDescHandler? OnImportInteriorInstanceDesc;

        public void ImportInteriorInstanceDesc(System.Collections.Generic.List<SpacetimeDB.Types.InteriorInstanceDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportInteriorInstanceDesc(records), this.SetCallReducerFlags.ImportInteriorInstanceDescFlags);
        }

        public bool InvokeImportInteriorInstanceDesc(ReducerEventContext ctx, Reducer.ImportInteriorInstanceDesc args)
        {
            if (OnImportInteriorInstanceDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportInteriorInstanceDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportInteriorInstanceDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<InteriorInstanceDesc> Records;

            public ImportInteriorInstanceDesc(System.Collections.Generic.List<InteriorInstanceDesc> Records)
            {
                this.Records = Records;
            }

            public ImportInteriorInstanceDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_interior_instance_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportInteriorInstanceDescFlags;
        public void ImportInteriorInstanceDesc(CallReducerFlags flags) => ImportInteriorInstanceDescFlags = flags;
    }
}
