// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportClaimTechDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<ClaimTechDescV2> records);
        public event ImportClaimTechDescHandler? OnImportClaimTechDesc;

        public void ImportClaimTechDesc(System.Collections.Generic.List<ClaimTechDescV2> records)
        {
            conn.InternalCallReducer(new Reducer.ImportClaimTechDesc(records), this.SetCallReducerFlags.ImportClaimTechDescFlags);
        }

        public bool InvokeImportClaimTechDesc(ReducerEventContext ctx, Reducer.ImportClaimTechDesc args)
        {
            if (OnImportClaimTechDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportClaimTechDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportClaimTechDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ClaimTechDescV2> Records;

            public ImportClaimTechDesc(System.Collections.Generic.List<ClaimTechDescV2> Records)
            {
                this.Records = Records;
            }

            public ImportClaimTechDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_claim_tech_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportClaimTechDescFlags;
        public void ImportClaimTechDesc(CallReducerFlags flags) => ImportClaimTechDescFlags = flags;
    }
}
