// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportEmpireIconDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.EmpireIconDesc> records);
        public event ImportEmpireIconDescHandler? OnImportEmpireIconDesc;

        public void ImportEmpireIconDesc(System.Collections.Generic.List<SpacetimeDB.Types.EmpireIconDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportEmpireIconDesc(records), this.SetCallReducerFlags.ImportEmpireIconDescFlags);
        }

        public bool InvokeImportEmpireIconDesc(ReducerEventContext ctx, Reducer.ImportEmpireIconDesc args)
        {
            if (OnImportEmpireIconDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportEmpireIconDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportEmpireIconDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<EmpireIconDesc> Records;

            public ImportEmpireIconDesc(System.Collections.Generic.List<EmpireIconDesc> Records)
            {
                this.Records = Records;
            }

            public ImportEmpireIconDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_empire_icon_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportEmpireIconDescFlags;
        public void ImportEmpireIconDesc(CallReducerFlags flags) => ImportEmpireIconDescFlags = flags;
    }
}
