// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportToolDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.ToolDesc> records);
        public event ImportToolDescHandler? OnImportToolDesc;

        public void ImportToolDesc(System.Collections.Generic.List<SpacetimeDB.Types.ToolDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportToolDesc(records), this.SetCallReducerFlags.ImportToolDescFlags);
        }

        public bool InvokeImportToolDesc(ReducerEventContext ctx, Reducer.ImportToolDesc args)
        {
            if (OnImportToolDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportToolDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportToolDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ToolDesc> Records;

            public ImportToolDesc(System.Collections.Generic.List<ToolDesc> Records)
            {
                this.Records = Records;
            }

            public ImportToolDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_tool_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportToolDescFlags;
        public void ImportToolDesc(CallReducerFlags flags) => ImportToolDescFlags = flags;
    }
}
