// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportWorldRegionStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.WorldRegionState> records);
        public event ImportWorldRegionStateHandler? OnImportWorldRegionState;

        public void ImportWorldRegionState(System.Collections.Generic.List<SpacetimeDB.Types.WorldRegionState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportWorldRegionState(records), this.SetCallReducerFlags.ImportWorldRegionStateFlags);
        }

        public bool InvokeImportWorldRegionState(ReducerEventContext ctx, Reducer.ImportWorldRegionState args)
        {
            if (OnImportWorldRegionState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportWorldRegionState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportWorldRegionState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<WorldRegionState> Records;

            public ImportWorldRegionState(System.Collections.Generic.List<WorldRegionState> Records)
            {
                this.Records = Records;
            }

            public ImportWorldRegionState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_world_region_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportWorldRegionStateFlags;
        public void ImportWorldRegionState(CallReducerFlags flags) => ImportWorldRegionStateFlags = flags;
    }
}
