// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportChatMessageStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.ChatMessageState> records);
        public event ImportChatMessageStateHandler? OnImportChatMessageState;

        public void ImportChatMessageState(System.Collections.Generic.List<SpacetimeDB.Types.ChatMessageState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportChatMessageState(records), this.SetCallReducerFlags.ImportChatMessageStateFlags);
        }

        public bool InvokeImportChatMessageState(ReducerEventContext ctx, Reducer.ImportChatMessageState args)
        {
            if (OnImportChatMessageState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportChatMessageState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportChatMessageState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ChatMessageState> Records;

            public ImportChatMessageState(System.Collections.Generic.List<ChatMessageState> Records)
            {
                this.Records = Records;
            }

            public ImportChatMessageState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_chat_message_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportChatMessageStateFlags;
        public void ImportChatMessageState(CallReducerFlags flags) => ImportChatMessageStateFlags = flags;
    }
}
