// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportInteriorPortalConnectionsDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.InteriorPortalConnectionsDesc> records);
        public event ImportInteriorPortalConnectionsDescHandler? OnImportInteriorPortalConnectionsDesc;

        public void ImportInteriorPortalConnectionsDesc(System.Collections.Generic.List<SpacetimeDB.Types.InteriorPortalConnectionsDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportInteriorPortalConnectionsDesc(records), this.SetCallReducerFlags.ImportInteriorPortalConnectionsDescFlags);
        }

        public bool InvokeImportInteriorPortalConnectionsDesc(ReducerEventContext ctx, Reducer.ImportInteriorPortalConnectionsDesc args)
        {
            if (OnImportInteriorPortalConnectionsDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportInteriorPortalConnectionsDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportInteriorPortalConnectionsDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<InteriorPortalConnectionsDesc> Records;

            public ImportInteriorPortalConnectionsDesc(System.Collections.Generic.List<InteriorPortalConnectionsDesc> Records)
            {
                this.Records = Records;
            }

            public ImportInteriorPortalConnectionsDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_interior_portal_connections_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportInteriorPortalConnectionsDescFlags;
        public void ImportInteriorPortalConnectionsDesc(CallReducerFlags flags) => ImportInteriorPortalConnectionsDescFlags = flags;
    }
}
