// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportKnowledgePavingStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.KnowledgePavingState> records);
        public event ImportKnowledgePavingStateHandler? OnImportKnowledgePavingState;

        public void ImportKnowledgePavingState(System.Collections.Generic.List<SpacetimeDB.Types.KnowledgePavingState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportKnowledgePavingState(records), this.SetCallReducerFlags.ImportKnowledgePavingStateFlags);
        }

        public bool InvokeImportKnowledgePavingState(ReducerEventContext ctx, Reducer.ImportKnowledgePavingState args)
        {
            if (OnImportKnowledgePavingState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportKnowledgePavingState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportKnowledgePavingState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<KnowledgePavingState> Records;

            public ImportKnowledgePavingState(System.Collections.Generic.List<KnowledgePavingState> Records)
            {
                this.Records = Records;
            }

            public ImportKnowledgePavingState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_knowledge_paving_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportKnowledgePavingStateFlags;
        public void ImportKnowledgePavingState(CallReducerFlags flags) => ImportKnowledgePavingStateFlags = flags;
    }
}
