// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportCombatActionDescV2Handler(ReducerEventContext ctx, System.Collections.Generic.List<CombatActionDescV2> records);
        public event ImportCombatActionDescV2Handler? OnImportCombatActionDescV2;

        public void ImportCombatActionDescV2(System.Collections.Generic.List<CombatActionDescV2> records)
        {
            conn.InternalCallReducer(new Reducer.ImportCombatActionDescV2(records), this.SetCallReducerFlags.ImportCombatActionDescV2Flags);
        }

        public bool InvokeImportCombatActionDescV2(ReducerEventContext ctx, Reducer.ImportCombatActionDescV2 args)
        {
            if (OnImportCombatActionDescV2 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportCombatActionDescV2(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportCombatActionDescV2 : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<CombatActionDescV2> Records;

            public ImportCombatActionDescV2(System.Collections.Generic.List<CombatActionDescV2> Records)
            {
                this.Records = Records;
            }

            public ImportCombatActionDescV2()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_combat_action_desc_v2";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportCombatActionDescV2Flags;
        public void ImportCombatActionDescV2(CallReducerFlags flags) => ImportCombatActionDescV2Flags = flags;
    }
}
