// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportResourceClumpDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.ResourceClumpDesc> records);
        public event ImportResourceClumpDescHandler? OnImportResourceClumpDesc;

        public void ImportResourceClumpDesc(System.Collections.Generic.List<SpacetimeDB.Types.ResourceClumpDesc> records)
        {
            conn.InternalCallReducer(new Reducer.ImportResourceClumpDesc(records), this.SetCallReducerFlags.ImportResourceClumpDescFlags);
        }

        public bool InvokeImportResourceClumpDesc(ReducerEventContext ctx, Reducer.ImportResourceClumpDesc args)
        {
            if (OnImportResourceClumpDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportResourceClumpDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportResourceClumpDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ResourceClumpDesc> Records;

            public ImportResourceClumpDesc(System.Collections.Generic.List<ResourceClumpDesc> Records)
            {
                this.Records = Records;
            }

            public ImportResourceClumpDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_resource_clump_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportResourceClumpDescFlags;
        public void ImportResourceClumpDesc(CallReducerFlags flags) => ImportResourceClumpDescFlags = flags;
    }
}
