// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void InteriorSetCollapsedScheduledHandler(ReducerEventContext ctx, InteriorSetCollapsedTimer timer);
        public event InteriorSetCollapsedScheduledHandler? OnInteriorSetCollapsedScheduled;

        public void InteriorSetCollapsedScheduled(InteriorSetCollapsedTimer timer)
        {
            conn.InternalCallReducer(new Reducer.InteriorSetCollapsedScheduled(timer), this.SetCallReducerFlags.InteriorSetCollapsedScheduledFlags);
        }

        public bool InvokeInteriorSetCollapsedScheduled(ReducerEventContext ctx, Reducer.InteriorSetCollapsedScheduled args)
        {
            if (OnInteriorSetCollapsedScheduled == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnInteriorSetCollapsedScheduled(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class InteriorSetCollapsedScheduled : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public InteriorSetCollapsedTimer Timer;

            public InteriorSetCollapsedScheduled(InteriorSetCollapsedTimer Timer)
            {
                this.Timer = Timer;
            }

            public InteriorSetCollapsedScheduled()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "interior_set_collapsed_scheduled";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags InteriorSetCollapsedScheduledFlags;
        public void InteriorSetCollapsedScheduled(CallReducerFlags flags) => InteriorSetCollapsedScheduledFlags = flags;
    }
}
