// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void LootChestDespawnHandler(ReducerEventContext ctx, SpacetimeDB.Types.LootChestDespawnTimer timer);
        public event LootChestDespawnHandler? OnLootChestDespawn;

        public void LootChestDespawn(SpacetimeDB.Types.LootChestDespawnTimer timer)
        {
            conn.InternalCallReducer(new Reducer.LootChestDespawn(timer), this.SetCallReducerFlags.LootChestDespawnFlags);
        }

        public bool InvokeLootChestDespawn(ReducerEventContext ctx, Reducer.LootChestDespawn args)
        {
            if (OnLootChestDespawn == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnLootChestDespawn(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class LootChestDespawn : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public LootChestDespawnTimer Timer;

            public LootChestDespawn(LootChestDespawnTimer Timer)
            {
                this.Timer = Timer;
            }

            public LootChestDespawn()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "loot_chest_despawn";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags LootChestDespawnFlags;
        public void LootChestDespawn(CallReducerFlags flags) => LootChestDespawnFlags = flags;
    }
}
