// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void MigrationSetBuildingDescParamsHandler(ReducerEventContext ctx, bool allowBuildingHealthChange);
        public event MigrationSetBuildingDescParamsHandler? OnMigrationSetBuildingDescParams;

        public void MigrationSetBuildingDescParams(bool allowBuildingHealthChange)
        {
            conn.InternalCallReducer(new Reducer.MigrationSetBuildingDescParams(allowBuildingHealthChange), this.SetCallReducerFlags.MigrationSetBuildingDescParamsFlags);
        }

        public bool InvokeMigrationSetBuildingDescParams(ReducerEventContext ctx, Reducer.MigrationSetBuildingDescParams args)
        {
            if (OnMigrationSetBuildingDescParams == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnMigrationSetBuildingDescParams(
                ctx,
                args.AllowBuildingHealthChange
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class MigrationSetBuildingDescParams : Reducer, IReducerArgs
        {
            [DataMember(Name = "allow_building_health_change")]
            public bool AllowBuildingHealthChange;

            public MigrationSetBuildingDescParams(bool AllowBuildingHealthChange)
            {
                this.AllowBuildingHealthChange = AllowBuildingHealthChange;
            }

            public MigrationSetBuildingDescParams()
            {
            }

            string IReducerArgs.ReducerName => "migration_set_building_desc_params";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags MigrationSetBuildingDescParamsFlags;
        public void MigrationSetBuildingDescParams(CallReducerFlags flags) => MigrationSetBuildingDescParamsFlags = flags;
    }
}
