// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PassiveCraftProcessHandler(ReducerEventContext ctx, PassiveCraftTimer timer);
        public event PassiveCraftProcessHandler? OnPassiveCraftProcess;

        public void PassiveCraftProcess(PassiveCraftTimer timer)
        {
            conn.InternalCallReducer(new Reducer.PassiveCraftProcess(timer), this.SetCallReducerFlags.PassiveCraftProcessFlags);
        }

        public bool InvokePassiveCraftProcess(ReducerEventContext ctx, Reducer.PassiveCraftProcess args)
        {
            if (OnPassiveCraftProcess == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPassiveCraftProcess(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PassiveCraftProcess : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public PassiveCraftTimer Timer;

            public PassiveCraftProcess(PassiveCraftTimer Timer)
            {
                this.Timer = Timer;
            }

            public PassiveCraftProcess()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "passive_craft_process";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PassiveCraftProcessFlags;
        public void PassiveCraftProcess(CallReducerFlags flags) => PassiveCraftProcessFlags = flags;
    }
}
