// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerSetDefaultDeployableHandler(ReducerEventContext ctx, SpacetimeDB.Types.PlayerSetDefaultDeployableRequest request);
        public event PlayerSetDefaultDeployableHandler? OnPlayerSetDefaultDeployable;

        public void PlayerSetDefaultDeployable(SpacetimeDB.Types.PlayerSetDefaultDeployableRequest request)
        {
            conn.InternalCallReducer(new Reducer.PlayerSetDefaultDeployable(request), this.SetCallReducerFlags.PlayerSetDefaultDeployableFlags);
        }

        public bool InvokePlayerSetDefaultDeployable(ReducerEventContext ctx, Reducer.PlayerSetDefaultDeployable args)
        {
            if (OnPlayerSetDefaultDeployable == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerSetDefaultDeployable(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerSetDefaultDeployable : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerSetDefaultDeployableRequest Request;

            public PlayerSetDefaultDeployable(PlayerSetDefaultDeployableRequest Request)
            {
                this.Request = Request;
            }

            public PlayerSetDefaultDeployable()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "player_set_default_deployable";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerSetDefaultDeployableFlags;
        public void PlayerSetDefaultDeployable(CallReducerFlags flags) => PlayerSetDefaultDeployableFlags = flags;
    }
}
