// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SetQuestTrackedHandler(ReducerEventContext ctx, int id, bool tracked);
        public event SetQuestTrackedHandler? OnSetQuestTracked;

        public void SetQuestTracked(int id, bool tracked)
        {
            conn.InternalCallReducer(new Reducer.SetQuestTracked(id, tracked), this.SetCallReducerFlags.SetQuestTrackedFlags);
        }

        public bool InvokeSetQuestTracked(ReducerEventContext ctx, Reducer.SetQuestTracked args)
        {
            if (OnSetQuestTracked == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSetQuestTracked(
                ctx,
                args.Id,
                args.Tracked
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SetQuestTracked : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public int Id;
            [DataMember(Name = "tracked")]
            public bool Tracked;

            public SetQuestTracked(
                int Id,
                bool Tracked
            )
            {
                this.Id = Id;
                this.Tracked = Tracked;
            }

            public SetQuestTracked()
            {
            }

            string IReducerArgs.ReducerName => "set_quest_tracked";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SetQuestTrackedFlags;
        public void SetQuestTracked(CallReducerFlags flags) => SetQuestTrackedFlags = flags;
    }
}
