// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageInteriorPortalConnectionsDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.InteriorPortalConnectionsDesc> records);
        public event StageInteriorPortalConnectionsDescHandler? OnStageInteriorPortalConnectionsDesc;

        public void StageInteriorPortalConnectionsDesc(System.Collections.Generic.List<SpacetimeDB.Types.InteriorPortalConnectionsDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageInteriorPortalConnectionsDesc(records), this.SetCallReducerFlags.StageInteriorPortalConnectionsDescFlags);
        }

        public bool InvokeStageInteriorPortalConnectionsDesc(ReducerEventContext ctx, Reducer.StageInteriorPortalConnectionsDesc args)
        {
            if (OnStageInteriorPortalConnectionsDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageInteriorPortalConnectionsDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageInteriorPortalConnectionsDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<InteriorPortalConnectionsDesc> Records;

            public StageInteriorPortalConnectionsDesc(System.Collections.Generic.List<InteriorPortalConnectionsDesc> Records)
            {
                this.Records = Records;
            }

            public StageInteriorPortalConnectionsDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_interior_portal_connections_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageInteriorPortalConnectionsDescFlags;
        public void StageInteriorPortalConnectionsDesc(CallReducerFlags flags) => StageInteriorPortalConnectionsDescFlags = flags;
    }
}
