// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageTeleportItemDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.TeleportItemDesc> records);
        public event StageTeleportItemDescHandler? OnStageTeleportItemDesc;

        public void StageTeleportItemDesc(System.Collections.Generic.List<SpacetimeDB.Types.TeleportItemDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageTeleportItemDesc(records), this.SetCallReducerFlags.StageTeleportItemDescFlags);
        }

        public bool InvokeStageTeleportItemDesc(ReducerEventContext ctx, Reducer.StageTeleportItemDesc args)
        {
            if (OnStageTeleportItemDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageTeleportItemDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageTeleportItemDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<TeleportItemDesc> Records;

            public StageTeleportItemDesc(System.Collections.Generic.List<TeleportItemDesc> Records)
            {
                this.Records = Records;
            }

            public StageTeleportItemDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_teleport_item_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageTeleportItemDescFlags;
        public void StageTeleportItemDesc(CallReducerFlags flags) => StageTeleportItemDescFlags = flags;
    }
}
