// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageInteriorInstanceDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<InteriorInstanceDesc> records);
        public event StageInteriorInstanceDescHandler? OnStageInteriorInstanceDesc;

        public void StageInteriorInstanceDesc(System.Collections.Generic.List<InteriorInstanceDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageInteriorInstanceDesc(records), this.SetCallReducerFlags.StageInteriorInstanceDescFlags);
        }

        public bool InvokeStageInteriorInstanceDesc(ReducerEventContext ctx, Reducer.StageInteriorInstanceDesc args)
        {
            if (OnStageInteriorInstanceDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageInteriorInstanceDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageInteriorInstanceDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<InteriorInstanceDesc> Records;

            public StageInteriorInstanceDesc(System.Collections.Generic.List<InteriorInstanceDesc> Records)
            {
                this.Records = Records;
            }

            public StageInteriorInstanceDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_interior_instance_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageInteriorInstanceDescFlags;
        public void StageInteriorInstanceDesc(CallReducerFlags flags) => StageInteriorInstanceDescFlags = flags;
    }
}
