// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageLootTableDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.LootTableDesc> records);
        public event StageLootTableDescHandler? OnStageLootTableDesc;

        public void StageLootTableDesc(System.Collections.Generic.List<SpacetimeDB.Types.LootTableDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageLootTableDesc(records), this.SetCallReducerFlags.StageLootTableDescFlags);
        }

        public bool InvokeStageLootTableDesc(ReducerEventContext ctx, Reducer.StageLootTableDesc args)
        {
            if (OnStageLootTableDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageLootTableDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageLootTableDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<LootTableDesc> Records;

            public StageLootTableDesc(System.Collections.Generic.List<LootTableDesc> Records)
            {
                this.Records = Records;
            }

            public StageLootTableDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_loot_table_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageLootTableDescFlags;
        public void StageLootTableDesc(CallReducerFlags flags) => StageLootTableDescFlags = flags;
    }
}
