// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageQuestDropDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.QuestDropDesc> records);
        public event StageQuestDropDescHandler? OnStageQuestDropDesc;

        public void StageQuestDropDesc(System.Collections.Generic.List<SpacetimeDB.Types.QuestDropDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageQuestDropDesc(records), this.SetCallReducerFlags.StageQuestDropDescFlags);
        }

        public bool InvokeStageQuestDropDesc(ReducerEventContext ctx, Reducer.StageQuestDropDesc args)
        {
            if (OnStageQuestDropDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageQuestDropDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageQuestDropDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<QuestDropDesc> Records;

            public StageQuestDropDesc(System.Collections.Generic.List<QuestDropDesc> Records)
            {
                this.Records = Records;
            }

            public StageQuestDropDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_quest_drop_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageQuestDropDescFlags;
        public void StageQuestDropDesc(CallReducerFlags flags) => StageQuestDropDescFlags = flags;
    }
}
