// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageDeployableAppearanceOverrideDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<SpacetimeDB.Types.DeployableAppearanceOverrideDesc> records);
        public event StageDeployableAppearanceOverrideDescHandler? OnStageDeployableAppearanceOverrideDesc;

        public void StageDeployableAppearanceOverrideDesc(System.Collections.Generic.List<SpacetimeDB.Types.DeployableAppearanceOverrideDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageDeployableAppearanceOverrideDesc(records), this.SetCallReducerFlags.StageDeployableAppearanceOverrideDescFlags);
        }

        public bool InvokeStageDeployableAppearanceOverrideDesc(ReducerEventContext ctx, Reducer.StageDeployableAppearanceOverrideDesc args)
        {
            if (OnStageDeployableAppearanceOverrideDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageDeployableAppearanceOverrideDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageDeployableAppearanceOverrideDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<DeployableAppearanceOverrideDesc> Records;

            public StageDeployableAppearanceOverrideDesc(System.Collections.Generic.List<DeployableAppearanceOverrideDesc> Records)
            {
                this.Records = Records;
            }

            public StageDeployableAppearanceOverrideDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_deployable_appearance_override_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageDeployableAppearanceOverrideDescFlags;
        public void StageDeployableAppearanceOverrideDesc(CallReducerFlags flags) => StageDeployableAppearanceOverrideDescFlags = flags;
    }
}
