// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageConstructionRecipeDescV2Handler(ReducerEventContext ctx, System.Collections.Generic.List<ConstructionRecipeDescV2> records);
        public event StageConstructionRecipeDescV2Handler? OnStageConstructionRecipeDescV2;

        public void StageConstructionRecipeDescV2(System.Collections.Generic.List<ConstructionRecipeDescV2> records)
        {
            conn.InternalCallReducer(new Reducer.StageConstructionRecipeDescV2(records), this.SetCallReducerFlags.StageConstructionRecipeDescV2Flags);
        }

        public bool InvokeStageConstructionRecipeDescV2(ReducerEventContext ctx, Reducer.StageConstructionRecipeDescV2 args)
        {
            if (OnStageConstructionRecipeDescV2 == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageConstructionRecipeDescV2(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageConstructionRecipeDescV2 : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ConstructionRecipeDescV2> Records;

            public StageConstructionRecipeDescV2(System.Collections.Generic.List<ConstructionRecipeDescV2> Records)
            {
                this.Records = Records;
            }

            public StageConstructionRecipeDescV2()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_construction_recipe_desc_v2";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageConstructionRecipeDescV2Flags;
        public void StageConstructionRecipeDescV2(CallReducerFlags flags) => StageConstructionRecipeDescV2Flags = flags;
    }
}
