// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StageAbilityUnlockDescHandler(ReducerEventContext ctx, System.Collections.Generic.List<AbilityUnlockDesc> records);
        public event StageAbilityUnlockDescHandler? OnStageAbilityUnlockDesc;

        public void StageAbilityUnlockDesc(System.Collections.Generic.List<AbilityUnlockDesc> records)
        {
            conn.InternalCallReducer(new Reducer.StageAbilityUnlockDesc(records), this.SetCallReducerFlags.StageAbilityUnlockDescFlags);
        }

        public bool InvokeStageAbilityUnlockDesc(ReducerEventContext ctx, Reducer.StageAbilityUnlockDesc args)
        {
            if (OnStageAbilityUnlockDesc == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStageAbilityUnlockDesc(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StageAbilityUnlockDesc : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<AbilityUnlockDesc> Records;

            public StageAbilityUnlockDesc(System.Collections.Generic.List<AbilityUnlockDesc> Records)
            {
                this.Records = Records;
            }

            public StageAbilityUnlockDesc()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "stage_ability_unlock_desc";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StageAbilityUnlockDescFlags;
        public void StageAbilityUnlockDesc(CallReducerFlags flags) => StageAbilityUnlockDescFlags = flags;
    }
}
