// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TerraformSetFinalTargetHandler(ReducerEventContext ctx, SpacetimeDB.Types.PlayerTerraformSetFinalTargetRequest request);
        public event TerraformSetFinalTargetHandler? OnTerraformSetFinalTarget;

        public void TerraformSetFinalTarget(SpacetimeDB.Types.PlayerTerraformSetFinalTargetRequest request)
        {
            conn.InternalCallReducer(new Reducer.TerraformSetFinalTarget(request), this.SetCallReducerFlags.TerraformSetFinalTargetFlags);
        }

        public bool InvokeTerraformSetFinalTarget(ReducerEventContext ctx, Reducer.TerraformSetFinalTarget args)
        {
            if (OnTerraformSetFinalTarget == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTerraformSetFinalTarget(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TerraformSetFinalTarget : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerTerraformSetFinalTargetRequest Request;

            public TerraformSetFinalTarget(PlayerTerraformSetFinalTargetRequest Request)
            {
                this.Request = Request;
            }

            public TerraformSetFinalTarget()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "terraform_set_final_target";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TerraformSetFinalTargetFlags;
        public void TerraformSetFinalTarget(CallReducerFlags flags) => TerraformSetFinalTargetFlags = flags;
    }
}
