// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TradeAcceptHandler(ReducerEventContext ctx, SpacetimeDB.Types.PlayerTradeAcceptRequest request);
        public event TradeAcceptHandler? OnTradeAccept;

        public void TradeAccept(SpacetimeDB.Types.PlayerTradeAcceptRequest request)
        {
            conn.InternalCallReducer(new Reducer.TradeAccept(request), this.SetCallReducerFlags.TradeAcceptFlags);
        }

        public bool InvokeTradeAccept(ReducerEventContext ctx, Reducer.TradeAccept args)
        {
            if (OnTradeAccept == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTradeAccept(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TradeAccept : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public PlayerTradeAcceptRequest Request;

            public TradeAccept(PlayerTradeAcceptRequest Request)
            {
                this.Request = Request;
            }

            public TradeAccept()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "trade_accept";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TradeAcceptFlags;
        public void TradeAccept(CallReducerFlags flags) => TradeAcceptFlags = flags;
    }
}
