// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ActiveEnvironmentBuffStateHandle : RemoteTableHandle<EventContext, ActiveEnvironmentBuffState>
        {
            protected override string RemoteTableName => "active_environment_buff_state";

            public sealed class PlayerBuffIndex : BTreeIndexBase<(ulong EntityId, int BuffId)>
            {
                protected override (ulong EntityId, int BuffId) GetKey(ActiveEnvironmentBuffState row) => (row.EntityId, row.BuffId);

                public PlayerBuffIndex(ActiveEnvironmentBuffStateHandle table) : base(table) { }
            }

            public readonly PlayerBuffIndex PlayerBuff;

            public sealed class EntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ActiveEnvironmentBuffState row) => row.EntityId;

                public EntityIdIndex(ActiveEnvironmentBuffStateHandle table) : base(table) { }
            }

            public readonly EntityIdIndex EntityId;

            internal ActiveEnvironmentBuffStateHandle(DbConnection conn) : base(conn)
            {
                PlayerBuff = new(this);
                EntityId = new(this);
            }
        }

        public readonly ActiveEnvironmentBuffStateHandle ActiveEnvironmentBuffState;
    }

    public sealed class ActiveEnvironmentBuffStateCols
    {
        public global::SpacetimeDB.Col<ActiveEnvironmentBuffState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<ActiveEnvironmentBuffState, int> BuffId { get; }

        public ActiveEnvironmentBuffStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<ActiveEnvironmentBuffState, ulong>(tableName, "entity_id");
            BuffId = new global::SpacetimeDB.Col<ActiveEnvironmentBuffState, int>(tableName, "buff_id");
        }
    }

    public sealed class ActiveEnvironmentBuffStateIxCols
    {
        public global::SpacetimeDB.IxCol<ActiveEnvironmentBuffState, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<ActiveEnvironmentBuffState, int> BuffId { get; }

        public ActiveEnvironmentBuffStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<ActiveEnvironmentBuffState, ulong>(tableName, "entity_id");
            BuffId = new global::SpacetimeDB.IxCol<ActiveEnvironmentBuffState, int>(tableName, "buff_id");
        }
    }
}
