// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BlockedIdentityHandle : RemoteTableHandle<EventContext, BlockedIdentity>
        {
            protected override string RemoteTableName => "blocked_identity";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(BlockedIdentity row) => row.Identity;

                public IdentityUniqueIndex(BlockedIdentityHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal BlockedIdentityHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(BlockedIdentity row) => row.Identity;
        }

        public readonly BlockedIdentityHandle BlockedIdentity;
    }
}
