// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class BuildingTypeDescHandle : RemoteTableHandle<EventContext, BuildingTypeDesc>
        {
            protected override string RemoteTableName => "building_type_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(BuildingTypeDesc row) => row.Id;

                public IdUniqueIndex(BuildingTypeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal BuildingTypeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(BuildingTypeDesc row) => row.Id;
        }

        public readonly BuildingTypeDescHandle BuildingTypeDesc;
    }

    public sealed class BuildingTypeDescCols
    {
        public global::SpacetimeDB.Col<BuildingTypeDesc, int> Id { get; }
        public global::SpacetimeDB.Col<BuildingTypeDesc, string> Name { get; }
        public global::SpacetimeDB.Col<BuildingTypeDesc, BuildingCategory> Category { get; }
        public global::SpacetimeDB.Col<BuildingTypeDesc, System.Collections.Generic.List<string>> Actions { get; }

        public BuildingTypeDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<BuildingTypeDesc, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<BuildingTypeDesc, string>(tableName, "name");
            Category = new global::SpacetimeDB.Col<BuildingTypeDesc, BuildingCategory>(tableName, "category");
            Actions = new global::SpacetimeDB.Col<BuildingTypeDesc, System.Collections.Generic.List<string>>(tableName, "actions");
        }
    }

    public sealed class BuildingTypeDescIxCols
    {
        public global::SpacetimeDB.IxCol<BuildingTypeDesc, int> Id { get; }

        public BuildingTypeDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<BuildingTypeDesc, int>(tableName, "id");
        }
    }
}
