// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatCleanupTimerHandle : RemoteTableHandle<EventContext, ChatCleanupTimer>
        {
            protected override string RemoteTableName => "chat_cleanup_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChatCleanupTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(ChatCleanupTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal ChatCleanupTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(ChatCleanupTimer row) => row.ScheduledId;
        }

        public readonly ChatCleanupTimerHandle ChatCleanupTimer;
    }

    public sealed class ChatCleanupTimerCols
    {
        public global::SpacetimeDB.Col<ChatCleanupTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<ChatCleanupTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }

        public ChatCleanupTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<ChatCleanupTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<ChatCleanupTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
        }
    }

    public sealed class ChatCleanupTimerIxCols
    {
        public global::SpacetimeDB.IxCol<ChatCleanupTimer, ulong> ScheduledId { get; }

        public ChatCleanupTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<ChatCleanupTimer, ulong>(tableName, "scheduled_id");
        }
    }
}
