// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ChatMessageStateHandle : RemoteTableHandle<EventContext, ChatMessageState>
        {
            protected override string RemoteTableName => "chat_message_state";

            public sealed class ChannelAndTargetIdIndex : BTreeIndexBase<(int ChannelId, ulong TargetId, int Timestamp)>
            {
                protected override (int ChannelId, ulong TargetId, int Timestamp) GetKey(ChatMessageState row) => (row.ChannelId, row.TargetId, row.Timestamp);

                public ChannelAndTargetIdIndex(ChatMessageStateHandle table) : base(table) { }
            }

            public readonly ChannelAndTargetIdIndex ChannelAndTargetId;

            public sealed class ChannelIdIndex : BTreeIndexBase<(int ChannelId, int Timestamp)>
            {
                protected override (int ChannelId, int Timestamp) GetKey(ChatMessageState row) => (row.ChannelId, row.Timestamp);

                public ChannelIdIndex(ChatMessageStateHandle table) : base(table) { }
            }

            public readonly ChannelIdIndex ChannelId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ChatMessageState row) => row.EntityId;

                public EntityIdUniqueIndex(ChatMessageStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class OwnerEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ChatMessageState row) => row.OwnerEntityId;

                public OwnerEntityIdIndex(ChatMessageStateHandle table) : base(table) { }
            }

            public readonly OwnerEntityIdIndex OwnerEntityId;

            public sealed class JustTargetIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ChatMessageState row) => row.TargetId;

                public JustTargetIdIndex(ChatMessageStateHandle table) : base(table) { }
            }

            public readonly JustTargetIdIndex JustTargetId;

            public sealed class TargetIdIndex : BTreeIndexBase<(ulong TargetId, int Timestamp)>
            {
                protected override (ulong TargetId, int Timestamp) GetKey(ChatMessageState row) => (row.TargetId, row.Timestamp);

                public TargetIdIndex(ChatMessageStateHandle table) : base(table) { }
            }

            public readonly TargetIdIndex TargetId;

            internal ChatMessageStateHandle(DbConnection conn) : base(conn)
            {
                ChannelAndTargetId = new(this);
                ChannelId = new(this);
                EntityId = new(this);
                OwnerEntityId = new(this);
                JustTargetId = new(this);
                TargetId = new(this);
            }

            protected override object GetPrimaryKey(ChatMessageState row) => row.EntityId;
        }

        public readonly ChatMessageStateHandle ChatMessageState;
    }

    public sealed class ChatMessageStateCols
    {
        public global::SpacetimeDB.Col<ChatMessageState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<ChatMessageState, string> Username { get; }
        public global::SpacetimeDB.Col<ChatMessageState, int> TitleId { get; }
        public global::SpacetimeDB.Col<ChatMessageState, int> ChannelId { get; }
        public global::SpacetimeDB.Col<ChatMessageState, ulong> TargetId { get; }
        public global::SpacetimeDB.Col<ChatMessageState, string> Text { get; }
        public global::SpacetimeDB.Col<ChatMessageState, int> Timestamp { get; }
        public global::SpacetimeDB.Col<ChatMessageState, ulong> OwnerEntityId { get; }

        public ChatMessageStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<ChatMessageState, ulong>(tableName, "entity_id");
            Username = new global::SpacetimeDB.Col<ChatMessageState, string>(tableName, "username");
            TitleId = new global::SpacetimeDB.Col<ChatMessageState, int>(tableName, "title_id");
            ChannelId = new global::SpacetimeDB.Col<ChatMessageState, int>(tableName, "channel_id");
            TargetId = new global::SpacetimeDB.Col<ChatMessageState, ulong>(tableName, "target_id");
            Text = new global::SpacetimeDB.Col<ChatMessageState, string>(tableName, "text");
            Timestamp = new global::SpacetimeDB.Col<ChatMessageState, int>(tableName, "timestamp");
            OwnerEntityId = new global::SpacetimeDB.Col<ChatMessageState, ulong>(tableName, "owner_entity_id");
        }
    }

    public sealed class ChatMessageStateIxCols
    {
        public global::SpacetimeDB.IxCol<ChatMessageState, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<ChatMessageState, int> ChannelId { get; }
        public global::SpacetimeDB.IxCol<ChatMessageState, ulong> TargetId { get; }
        public global::SpacetimeDB.IxCol<ChatMessageState, int> Timestamp { get; }
        public global::SpacetimeDB.IxCol<ChatMessageState, ulong> OwnerEntityId { get; }

        public ChatMessageStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<ChatMessageState, ulong>(tableName, "entity_id");
            ChannelId = new global::SpacetimeDB.IxCol<ChatMessageState, int>(tableName, "channel_id");
            TargetId = new global::SpacetimeDB.IxCol<ChatMessageState, ulong>(tableName, "target_id");
            Timestamp = new global::SpacetimeDB.IxCol<ChatMessageState, int>(tableName, "timestamp");
            OwnerEntityId = new global::SpacetimeDB.IxCol<ChatMessageState, ulong>(tableName, "owner_entity_id");
        }
    }
}
