// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClaimTechStateHandle : RemoteTableHandle<EventContext, ClaimTechState>
        {
            protected override string RemoteTableName => "claim_tech_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClaimTechState row) => row.EntityId;

                public EntityIdUniqueIndex(ClaimTechStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal ClaimTechStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(ClaimTechState row) => row.EntityId;
        }

        public readonly ClaimTechStateHandle ClaimTechState;
    }

    public sealed class ClaimTechStateCols
    {
        public global::SpacetimeDB.Col<ClaimTechState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<ClaimTechState, System.Collections.Generic.List<int>> Learned { get; }
        public global::SpacetimeDB.Col<ClaimTechState, int> Researching { get; }
        public global::SpacetimeDB.Col<ClaimTechState, SpacetimeDB.Timestamp> StartTimestamp { get; }
        public global::SpacetimeDB.NullableCol<ClaimTechState, ulong> ScheduledId { get; }

        public ClaimTechStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<ClaimTechState, ulong>(tableName, "entity_id");
            Learned = new global::SpacetimeDB.Col<ClaimTechState, System.Collections.Generic.List<int>>(tableName, "learned");
            Researching = new global::SpacetimeDB.Col<ClaimTechState, int>(tableName, "researching");
            StartTimestamp = new global::SpacetimeDB.Col<ClaimTechState, SpacetimeDB.Timestamp>(tableName, "start_timestamp");
            ScheduledId = new global::SpacetimeDB.NullableCol<ClaimTechState, ulong>(tableName, "scheduled_id");
        }
    }

    public sealed class ClaimTechStateIxCols
    {
        public global::SpacetimeDB.IxCol<ClaimTechState, ulong> EntityId { get; }

        public ClaimTechStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<ClaimTechState, ulong>(tableName, "entity_id");
        }
    }
}
