// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClaimStateHandle : RemoteTableHandle<EventContext, ClaimState>
        {
            protected override string RemoteTableName => "claim_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClaimState row) => row.EntityId;

                public EntityIdUniqueIndex(ClaimStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class NameIndex : BTreeIndexBase<string>
            {
                protected override string GetKey(ClaimState row) => row.Name;

                public NameIndex(ClaimStateHandle table) : base(table) { }
            }

            public readonly NameIndex Name;

            public sealed class NeutralIndex : BTreeIndexBase<bool>
            {
                protected override bool GetKey(ClaimState row) => row.Neutral;

                public NeutralIndex(ClaimStateHandle table) : base(table) { }
            }

            public readonly NeutralIndex Neutral;

            public sealed class OwnerBuildingEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClaimState row) => row.OwnerBuildingEntityId;

                public OwnerBuildingEntityIdUniqueIndex(ClaimStateHandle table) : base(table) { }
            }

            public readonly OwnerBuildingEntityIdUniqueIndex OwnerBuildingEntityId;

            public sealed class OwnerPlayerEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(ClaimState row) => row.OwnerPlayerEntityId;

                public OwnerPlayerEntityIdIndex(ClaimStateHandle table) : base(table) { }
            }

            public readonly OwnerPlayerEntityIdIndex OwnerPlayerEntityId;

            internal ClaimStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                Name = new(this);
                Neutral = new(this);
                OwnerBuildingEntityId = new(this);
                OwnerPlayerEntityId = new(this);
            }

            protected override object GetPrimaryKey(ClaimState row) => row.EntityId;
        }

        public readonly ClaimStateHandle ClaimState;
    }
}
