// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ClaimLocalStateHandle : RemoteTableHandle<EventContext, ClaimLocalState>
        {
            protected override string RemoteTableName => "claim_local_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ClaimLocalState row) => row.EntityId;

                public EntityIdUniqueIndex(ClaimLocalStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal ClaimLocalStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(ClaimLocalState row) => row.EntityId;
        }

        public readonly ClaimLocalStateHandle ClaimLocalState;
    }

    public sealed class ClaimLocalStateCols
    {
        public global::SpacetimeDB.Col<ClaimLocalState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<ClaimLocalState, int> Supplies { get; }
        public global::SpacetimeDB.Col<ClaimLocalState, float> BuildingMaintenance { get; }
        public global::SpacetimeDB.Col<ClaimLocalState, int> NumTiles { get; }
        public global::SpacetimeDB.Col<ClaimLocalState, uint> NumTileNeighbors { get; }
        public global::SpacetimeDB.NullableCol<ClaimLocalState, OffsetCoordinatesSmallMessage> Location { get; }
        public global::SpacetimeDB.Col<ClaimLocalState, uint> Treasury { get; }
        public global::SpacetimeDB.Col<ClaimLocalState, uint> XpGainedSinceLastCoinMinting { get; }
        public global::SpacetimeDB.Col<ClaimLocalState, uint> SuppliesPurchaseThreshold { get; }
        public global::SpacetimeDB.Col<ClaimLocalState, float> SuppliesPurchasePrice { get; }
        public global::SpacetimeDB.Col<ClaimLocalState, int> BuildingDescriptionId { get; }

        public ClaimLocalStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<ClaimLocalState, ulong>(tableName, "entity_id");
            Supplies = new global::SpacetimeDB.Col<ClaimLocalState, int>(tableName, "supplies");
            BuildingMaintenance = new global::SpacetimeDB.Col<ClaimLocalState, float>(tableName, "building_maintenance");
            NumTiles = new global::SpacetimeDB.Col<ClaimLocalState, int>(tableName, "num_tiles");
            NumTileNeighbors = new global::SpacetimeDB.Col<ClaimLocalState, uint>(tableName, "num_tile_neighbors");
            Location = new global::SpacetimeDB.NullableCol<ClaimLocalState, OffsetCoordinatesSmallMessage>(tableName, "location");
            Treasury = new global::SpacetimeDB.Col<ClaimLocalState, uint>(tableName, "treasury");
            XpGainedSinceLastCoinMinting = new global::SpacetimeDB.Col<ClaimLocalState, uint>(tableName, "xp_gained_since_last_coin_minting");
            SuppliesPurchaseThreshold = new global::SpacetimeDB.Col<ClaimLocalState, uint>(tableName, "supplies_purchase_threshold");
            SuppliesPurchasePrice = new global::SpacetimeDB.Col<ClaimLocalState, float>(tableName, "supplies_purchase_price");
            BuildingDescriptionId = new global::SpacetimeDB.Col<ClaimLocalState, int>(tableName, "building_description_id");
        }
    }

    public sealed class ClaimLocalStateIxCols
    {
        public global::SpacetimeDB.IxCol<ClaimLocalState, ulong> EntityId { get; }

        public ClaimLocalStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<ClaimLocalState, ulong>(tableName, "entity_id");
        }
    }
}
