// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CombatActionDescV3Handle : RemoteTableHandle<EventContext, CombatActionDescV3>
        {
            protected override string RemoteTableName => "combat_action_desc_v3";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CombatActionDescV3 row) => row.Id;

                public IdUniqueIndex(CombatActionDescV3Handle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class LearnedByPlayerIndex : BTreeIndexBase<bool>
            {
                protected override bool GetKey(CombatActionDescV3 row) => row.LearnedByPlayer;

                public LearnedByPlayerIndex(CombatActionDescV3Handle table) : base(table) { }
            }

            public readonly LearnedByPlayerIndex LearnedByPlayer;

            internal CombatActionDescV3Handle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                LearnedByPlayer = new(this);
            }

            protected override object GetPrimaryKey(CombatActionDescV3 row) => row.Id;
        }

        public readonly CombatActionDescV3Handle CombatActionDescV3;
    }
}
