// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConstructionRecipeDiscoveryCargoDescHandle : RemoteTableHandle<EventContext, DiscoveryTriggerDesc>
        {
            protected override string RemoteTableName => "construction_recipe_discovery_cargo_desc";

            public sealed class CargoIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(DiscoveryTriggerDesc row) => row.RequirementId;

                public CargoIdIndex(ConstructionRecipeDiscoveryCargoDescHandle table) : base(table) { }
            }

            public readonly CargoIdIndex CargoId;

            internal ConstructionRecipeDiscoveryCargoDescHandle(DbConnection conn) : base(conn)
            {
                CargoId = new(this);
            }
        }

        public readonly ConstructionRecipeDiscoveryCargoDescHandle ConstructionRecipeDiscoveryCargoDesc;
    }

    public sealed class ConstructionRecipeDiscoveryCargoDescCols
    {
        public global::SpacetimeDB.Col<DiscoveryTriggerDesc, int> RequirementId { get; }
        public global::SpacetimeDB.Col<DiscoveryTriggerDesc, int> RecipeId { get; }

        public ConstructionRecipeDiscoveryCargoDescCols(string tableName)
        {
            RequirementId = new global::SpacetimeDB.Col<DiscoveryTriggerDesc, int>(tableName, "requirement_id");
            RecipeId = new global::SpacetimeDB.Col<DiscoveryTriggerDesc, int>(tableName, "recipe_id");
        }
    }

    public sealed class ConstructionRecipeDiscoveryCargoDescIxCols
    {
        public global::SpacetimeDB.IxCol<DiscoveryTriggerDesc, int> RequirementId { get; }

        public ConstructionRecipeDiscoveryCargoDescIxCols(string tableName)
        {
            RequirementId = new global::SpacetimeDB.IxCol<DiscoveryTriggerDesc, int>(tableName, "requirement_id");
        }
    }
}
