// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ContributionLootDescHandle : RemoteTableHandle<EventContext, ContributionLootDesc>
        {
            protected override string RemoteTableName => "contribution_loot_desc";

            public sealed class EnemyTypeIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(ContributionLootDesc row) => row.EnemyTypeId;

                public EnemyTypeIdIndex(ContributionLootDescHandle table) : base(table) { }
            }

            public readonly EnemyTypeIdIndex EnemyTypeId;

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ContributionLootDesc row) => row.Id;

                public IdUniqueIndex(ContributionLootDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ContributionLootDescHandle(DbConnection conn) : base(conn)
            {
                EnemyTypeId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(ContributionLootDesc row) => row.Id;
        }

        public readonly ContributionLootDescHandle ContributionLootDesc;
    }

    public sealed class ContributionLootDescCols
    {
        public global::SpacetimeDB.Col<ContributionLootDesc, int> Id { get; }
        public global::SpacetimeDB.Col<ContributionLootDesc, int> EnemyTypeId { get; }
        public global::SpacetimeDB.Col<ContributionLootDesc, int> ItemListId { get; }
        public global::SpacetimeDB.Col<ContributionLootDesc, int> MinimumContribution { get; }
        public global::SpacetimeDB.Col<ContributionLootDesc, bool> Weighted { get; }

        public ContributionLootDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ContributionLootDesc, int>(tableName, "id");
            EnemyTypeId = new global::SpacetimeDB.Col<ContributionLootDesc, int>(tableName, "enemy_type_id");
            ItemListId = new global::SpacetimeDB.Col<ContributionLootDesc, int>(tableName, "item_list_id");
            MinimumContribution = new global::SpacetimeDB.Col<ContributionLootDesc, int>(tableName, "minimum_contribution");
            Weighted = new global::SpacetimeDB.Col<ContributionLootDesc, bool>(tableName, "weighted");
        }
    }

    public sealed class ContributionLootDescIxCols
    {
        public global::SpacetimeDB.IxCol<ContributionLootDesc, int> Id { get; }
        public global::SpacetimeDB.IxCol<ContributionLootDesc, int> EnemyTypeId { get; }

        public ContributionLootDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ContributionLootDesc, int>(tableName, "id");
            EnemyTypeId = new global::SpacetimeDB.IxCol<ContributionLootDesc, int>(tableName, "enemy_type_id");
        }
    }
}
