// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class CrumbTrailContributionSpentStateHandle : RemoteTableHandle<EventContext, CrumbTrailContributionSpentState>
        {
            protected override string RemoteTableName => "crumb_trail_contribution_spent_state";

            public sealed class CrumbTrailEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(CrumbTrailContributionSpentState row) => row.CrumbTrailEntityId;

                public CrumbTrailEntityIdIndex(CrumbTrailContributionSpentStateHandle table) : base(table) { }
            }

            public readonly CrumbTrailEntityIdIndex CrumbTrailEntityId;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(CrumbTrailContributionSpentState row) => row.EntityId;

                public EntityIdUniqueIndex(CrumbTrailContributionSpentStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class PlayerAndCrumbEntityIdIndex : BTreeIndexBase<(ulong PlayerEntityId, ulong CrumbTrailEntityId)>
            {
                protected override (ulong PlayerEntityId, ulong CrumbTrailEntityId) GetKey(CrumbTrailContributionSpentState row) => (row.PlayerEntityId, row.CrumbTrailEntityId);

                public PlayerAndCrumbEntityIdIndex(CrumbTrailContributionSpentStateHandle table) : base(table) { }
            }

            public readonly PlayerAndCrumbEntityIdIndex PlayerAndCrumbEntityId;

            internal CrumbTrailContributionSpentStateHandle(DbConnection conn) : base(conn)
            {
                CrumbTrailEntityId = new(this);
                EntityId = new(this);
                PlayerAndCrumbEntityId = new(this);
            }

            protected override object GetPrimaryKey(CrumbTrailContributionSpentState row) => row.EntityId;
        }

        public readonly CrumbTrailContributionSpentStateHandle CrumbTrailContributionSpentState;
    }

    public sealed class CrumbTrailContributionSpentStateCols
    {
        public global::SpacetimeDB.Col<CrumbTrailContributionSpentState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<CrumbTrailContributionSpentState, ulong> PlayerEntityId { get; }
        public global::SpacetimeDB.Col<CrumbTrailContributionSpentState, ulong> CrumbTrailEntityId { get; }

        public CrumbTrailContributionSpentStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<CrumbTrailContributionSpentState, ulong>(tableName, "entity_id");
            PlayerEntityId = new global::SpacetimeDB.Col<CrumbTrailContributionSpentState, ulong>(tableName, "player_entity_id");
            CrumbTrailEntityId = new global::SpacetimeDB.Col<CrumbTrailContributionSpentState, ulong>(tableName, "crumb_trail_entity_id");
        }
    }

    public sealed class CrumbTrailContributionSpentStateIxCols
    {
        public global::SpacetimeDB.IxCol<CrumbTrailContributionSpentState, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<CrumbTrailContributionSpentState, ulong> PlayerEntityId { get; }
        public global::SpacetimeDB.IxCol<CrumbTrailContributionSpentState, ulong> CrumbTrailEntityId { get; }

        public CrumbTrailContributionSpentStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<CrumbTrailContributionSpentState, ulong>(tableName, "entity_id");
            PlayerEntityId = new global::SpacetimeDB.IxCol<CrumbTrailContributionSpentState, ulong>(tableName, "player_entity_id");
            CrumbTrailEntityId = new global::SpacetimeDB.IxCol<CrumbTrailContributionSpentState, ulong>(tableName, "crumb_trail_entity_id");
        }
    }
}
