// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class DeployableCollectibleStateV2Handle : RemoteTableHandle<EventContext, DeployableCollectibleStateV2>
        {
            protected override string RemoteTableName => "deployable_collectible_state_v2";

            public sealed class DeployableEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(DeployableCollectibleStateV2 row) => row.DeployableEntityId;

                public DeployableEntityIdUniqueIndex(DeployableCollectibleStateV2Handle table) : base(table) { }
            }

            public readonly DeployableEntityIdUniqueIndex DeployableEntityId;

            public sealed class OwnerEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(DeployableCollectibleStateV2 row) => row.OwnerEntityId;

                public OwnerEntityIdIndex(DeployableCollectibleStateV2Handle table) : base(table) { }
            }

            public readonly OwnerEntityIdIndex OwnerEntityId;

            internal DeployableCollectibleStateV2Handle(DbConnection conn) : base(conn)
            {
                DeployableEntityId = new(this);
                OwnerEntityId = new(this);
            }

            protected override object GetPrimaryKey(DeployableCollectibleStateV2 row) => row.DeployableEntityId;
        }

        public readonly DeployableCollectibleStateV2Handle DeployableCollectibleStateV2;
    }
}
