// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireRankDescHandle : RemoteTableHandle<EventContext, EmpireRankDesc>
        {
            protected override string RemoteTableName => "empire_rank_desc";

            public sealed class RankUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EmpireRankDesc row) => row.Rank;

                public RankUniqueIndex(EmpireRankDescHandle table) : base(table) { }
            }

            public readonly RankUniqueIndex Rank;

            internal EmpireRankDescHandle(DbConnection conn) : base(conn)
            {
                Rank = new(this);
            }

            protected override object GetPrimaryKey(EmpireRankDesc row) => row.Rank;
        }

        public readonly EmpireRankDescHandle EmpireRankDesc;
    }

    public sealed class EmpireRankDescCols
    {
        public global::SpacetimeDB.Col<EmpireRankDesc, int> Rank { get; }
        public global::SpacetimeDB.Col<EmpireRankDesc, string> Title { get; }
        public global::SpacetimeDB.NullableCol<EmpireRankDesc, int> MaxCount { get; }
        public global::SpacetimeDB.Col<EmpireRankDesc, System.Collections.Generic.List<bool>> Permissions { get; }

        public EmpireRankDescCols(string tableName)
        {
            Rank = new global::SpacetimeDB.Col<EmpireRankDesc, int>(tableName, "rank");
            Title = new global::SpacetimeDB.Col<EmpireRankDesc, string>(tableName, "title");
            MaxCount = new global::SpacetimeDB.NullableCol<EmpireRankDesc, int>(tableName, "max_count");
            Permissions = new global::SpacetimeDB.Col<EmpireRankDesc, System.Collections.Generic.List<bool>>(tableName, "permissions");
        }
    }

    public sealed class EmpireRankDescIxCols
    {
        public global::SpacetimeDB.IxCol<EmpireRankDesc, int> Rank { get; }

        public EmpireRankDescIxCols(string tableName)
        {
            Rank = new global::SpacetimeDB.IxCol<EmpireRankDesc, int>(tableName, "rank");
        }
    }
}
