// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EmpireNotificationDescHandle : RemoteTableHandle<EventContext, EmpireNotificationDesc>
        {
            protected override string RemoteTableName => "empire_notification_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EmpireNotificationDesc row) => row.Id;

                public IdUniqueIndex(EmpireNotificationDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EmpireNotificationDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(EmpireNotificationDesc row) => row.Id;
        }

        public readonly EmpireNotificationDescHandle EmpireNotificationDesc;
    }

    public sealed class EmpireNotificationDescCols
    {
        public global::SpacetimeDB.Col<EmpireNotificationDesc, int> Id { get; }
        public global::SpacetimeDB.Col<EmpireNotificationDesc, EmpireNotificationType> NotificationType { get; }
        public global::SpacetimeDB.Col<EmpireNotificationDesc, int> Priority { get; }
        public global::SpacetimeDB.Col<EmpireNotificationDesc, bool> ShowOnLogin { get; }
        public global::SpacetimeDB.Col<EmpireNotificationDesc, string> Text { get; }

        public EmpireNotificationDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<EmpireNotificationDesc, int>(tableName, "id");
            NotificationType = new global::SpacetimeDB.Col<EmpireNotificationDesc, EmpireNotificationType>(tableName, "notification_type");
            Priority = new global::SpacetimeDB.Col<EmpireNotificationDesc, int>(tableName, "priority");
            ShowOnLogin = new global::SpacetimeDB.Col<EmpireNotificationDesc, bool>(tableName, "show_on_login");
            Text = new global::SpacetimeDB.Col<EmpireNotificationDesc, string>(tableName, "text");
        }
    }

    public sealed class EmpireNotificationDescIxCols
    {
        public global::SpacetimeDB.IxCol<EmpireNotificationDesc, int> Id { get; }

        public EmpireNotificationDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<EmpireNotificationDesc, int>(tableName, "id");
        }
    }
}
