// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyScalingDescHandle : RemoteTableHandle<EventContext, EnemyScalingDesc>
        {
            protected override string RemoteTableName => "enemy_scaling_desc";

            public sealed class EnemyTypeIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(EnemyScalingDesc row) => row.EnemyTypeId;

                public EnemyTypeIdIndex(EnemyScalingDescHandle table) : base(table) { }
            }

            public readonly EnemyTypeIdIndex EnemyTypeId;

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EnemyScalingDesc row) => row.Id;

                public IdUniqueIndex(EnemyScalingDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal EnemyScalingDescHandle(DbConnection conn) : base(conn)
            {
                EnemyTypeId = new(this);
                Id = new(this);
            }

            protected override object GetPrimaryKey(EnemyScalingDesc row) => row.Id;
        }

        public readonly EnemyScalingDescHandle EnemyScalingDesc;
    }
}
