// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnemyRegenLoopTimerHandle : RemoteTableHandle<EventContext, EnemyRegenLoopTimer>
        {
            protected override string RemoteTableName => "enemy_regen_loop_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(EnemyRegenLoopTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(EnemyRegenLoopTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal EnemyRegenLoopTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(EnemyRegenLoopTimer row) => row.ScheduledId;
        }

        public readonly EnemyRegenLoopTimerHandle EnemyRegenLoopTimer;
    }

    public sealed class EnemyRegenLoopTimerCols
    {
        public global::SpacetimeDB.Col<EnemyRegenLoopTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<EnemyRegenLoopTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }

        public EnemyRegenLoopTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<EnemyRegenLoopTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<EnemyRegenLoopTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
        }
    }

    public sealed class EnemyRegenLoopTimerIxCols
    {
        public global::SpacetimeDB.IxCol<EnemyRegenLoopTimer, ulong> ScheduledId { get; }

        public EnemyRegenLoopTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<EnemyRegenLoopTimer, ulong>(tableName, "scheduled_id");
        }
    }
}
