// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class EnvironmentDebuffDescHandle : RemoteTableHandle<EventContext, EnvironmentDebuffDesc>
        {
            protected override string RemoteTableName => "environment_debuff_desc";

            public sealed class BuffIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EnvironmentDebuffDesc row) => row.BuffId;

                public BuffIdUniqueIndex(EnvironmentDebuffDescHandle table) : base(table) { }
            }

            public readonly BuffIdUniqueIndex BuffId;

            internal EnvironmentDebuffDescHandle(DbConnection conn) : base(conn)
            {
                BuffId = new(this);
            }

            protected override object GetPrimaryKey(EnvironmentDebuffDesc row) => row.BuffId;
        }

        public readonly EnvironmentDebuffDescHandle EnvironmentDebuffDesc;
    }

    public sealed class EnvironmentDebuffDescCols
    {
        public global::SpacetimeDB.Col<EnvironmentDebuffDesc, int> BuffId { get; }
        public global::SpacetimeDB.Col<EnvironmentDebuffDesc, EnvironmentResistanceType> ResistanceType { get; }
        public global::SpacetimeDB.Col<EnvironmentDebuffDesc, int> ResistanceLevel { get; }
        public global::SpacetimeDB.Col<EnvironmentDebuffDesc, int> GroundDamage { get; }
        public global::SpacetimeDB.Col<EnvironmentDebuffDesc, int> WaterDamage { get; }
        public global::SpacetimeDB.Col<EnvironmentDebuffDesc, string> ResistanceUnmetText { get; }
        public global::SpacetimeDB.Col<EnvironmentDebuffDesc, string> ResistanceMetText { get; }

        public EnvironmentDebuffDescCols(string tableName)
        {
            BuffId = new global::SpacetimeDB.Col<EnvironmentDebuffDesc, int>(tableName, "buff_id");
            ResistanceType = new global::SpacetimeDB.Col<EnvironmentDebuffDesc, EnvironmentResistanceType>(tableName, "resistance_type");
            ResistanceLevel = new global::SpacetimeDB.Col<EnvironmentDebuffDesc, int>(tableName, "resistance_level");
            GroundDamage = new global::SpacetimeDB.Col<EnvironmentDebuffDesc, int>(tableName, "ground_damage");
            WaterDamage = new global::SpacetimeDB.Col<EnvironmentDebuffDesc, int>(tableName, "water_damage");
            ResistanceUnmetText = new global::SpacetimeDB.Col<EnvironmentDebuffDesc, string>(tableName, "resistance_unmet_text");
            ResistanceMetText = new global::SpacetimeDB.Col<EnvironmentDebuffDesc, string>(tableName, "resistance_met_text");
        }
    }

    public sealed class EnvironmentDebuffDescIxCols
    {
        public global::SpacetimeDB.IxCol<EnvironmentDebuffDesc, int> BuffId { get; }

        public EnvironmentDebuffDescIxCols(string tableName)
        {
            BuffId = new global::SpacetimeDB.IxCol<EnvironmentDebuffDesc, int>(tableName, "buff_id");
        }
    }
}
