// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KnowledgeSecondaryStateHandle : RemoteTableHandle<EventContext, KnowledgeSecondaryState>
        {
            protected override string RemoteTableName => "knowledge_secondary_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(KnowledgeSecondaryState row) => row.EntityId;

                public EntityIdUniqueIndex(KnowledgeSecondaryStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal KnowledgeSecondaryStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(KnowledgeSecondaryState row) => row.EntityId;
        }

        public readonly KnowledgeSecondaryStateHandle KnowledgeSecondaryState;
    }

    public sealed class KnowledgeSecondaryStateCols
    {
        public global::SpacetimeDB.Col<KnowledgeSecondaryState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<KnowledgeSecondaryState, System.Collections.Generic.List<KnowledgeEntry>> Entries { get; }

        public KnowledgeSecondaryStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<KnowledgeSecondaryState, ulong>(tableName, "entity_id");
            Entries = new global::SpacetimeDB.Col<KnowledgeSecondaryState, System.Collections.Generic.List<KnowledgeEntry>>(tableName, "entries");
        }
    }

    public sealed class KnowledgeSecondaryStateIxCols
    {
        public global::SpacetimeDB.IxCol<KnowledgeSecondaryState, ulong> EntityId { get; }

        public KnowledgeSecondaryStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<KnowledgeSecondaryState, ulong>(tableName, "entity_id");
        }
    }
}
