// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class LocationStateHandle : RemoteTableHandle<EventContext, LocationState>
        {
            protected override string RemoteTableName => "location_state";

            public sealed class ChunkIndexIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(LocationState row) => row.ChunkIndex;

                public ChunkIndexIndex(LocationStateHandle table) : base(table) { }
            }

            public readonly ChunkIndexIndex ChunkIndex;

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(LocationState row) => row.EntityId;

                public EntityIdUniqueIndex(LocationStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class XZChunkIndexIndex : BTreeIndexBase<(int X, int Z, ulong ChunkIndex)>
            {
                protected override (int X, int Z, ulong ChunkIndex) GetKey(LocationState row) => (row.X, row.Z, row.ChunkIndex);

                public XZChunkIndexIndex(LocationStateHandle table) : base(table) { }
            }

            public readonly XZChunkIndexIndex XZChunkIndex;

            internal LocationStateHandle(DbConnection conn) : base(conn)
            {
                ChunkIndex = new(this);
                EntityId = new(this);
                XZChunkIndex = new(this);
            }

            protected override object GetPrimaryKey(LocationState row) => row.EntityId;
        }

        public readonly LocationStateHandle LocationState;
    }

    public sealed class LocationStateCols
    {
        public global::SpacetimeDB.Col<LocationState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<LocationState, ulong> ChunkIndex { get; }
        public global::SpacetimeDB.Col<LocationState, int> X { get; }
        public global::SpacetimeDB.Col<LocationState, int> Z { get; }
        public global::SpacetimeDB.Col<LocationState, uint> Dimension { get; }

        public LocationStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<LocationState, ulong>(tableName, "entity_id");
            ChunkIndex = new global::SpacetimeDB.Col<LocationState, ulong>(tableName, "chunk_index");
            X = new global::SpacetimeDB.Col<LocationState, int>(tableName, "x");
            Z = new global::SpacetimeDB.Col<LocationState, int>(tableName, "z");
            Dimension = new global::SpacetimeDB.Col<LocationState, uint>(tableName, "dimension");
        }
    }

    public sealed class LocationStateIxCols
    {
        public global::SpacetimeDB.IxCol<LocationState, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<LocationState, ulong> ChunkIndex { get; }
        public global::SpacetimeDB.IxCol<LocationState, int> X { get; }
        public global::SpacetimeDB.IxCol<LocationState, int> Z { get; }

        public LocationStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<LocationState, ulong>(tableName, "entity_id");
            ChunkIndex = new global::SpacetimeDB.IxCol<LocationState, ulong>(tableName, "chunk_index");
            X = new global::SpacetimeDB.IxCol<LocationState, int>(tableName, "x");
            Z = new global::SpacetimeDB.IxCol<LocationState, int>(tableName, "z");
        }
    }
}
