// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MarketplaceStateHandle : RemoteTableHandle<EventContext, MarketplaceState>
        {
            protected override string RemoteTableName => "marketplace_state";

            public sealed class BuildingEntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(MarketplaceState row) => row.BuildingEntityId;

                public BuildingEntityIdUniqueIndex(MarketplaceStateHandle table) : base(table) { }
            }

            public readonly BuildingEntityIdUniqueIndex BuildingEntityId;

            public sealed class ClaimEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(MarketplaceState row) => row.ClaimEntityId;

                public ClaimEntityIdIndex(MarketplaceStateHandle table) : base(table) { }
            }

            public readonly ClaimEntityIdIndex ClaimEntityId;

            internal MarketplaceStateHandle(DbConnection conn) : base(conn)
            {
                BuildingEntityId = new(this);
                ClaimEntityId = new(this);
            }

            protected override object GetPrimaryKey(MarketplaceState row) => row.BuildingEntityId;
        }

        public readonly MarketplaceStateHandle MarketplaceState;
    }
}
