// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class NpcDescHandle : RemoteTableHandle<EventContext, NpcDesc>
        {
            protected override string RemoteTableName => "npc_desc";

            public sealed class NpcTypeUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(NpcDesc row) => row.NpcType;

                public NpcTypeUniqueIndex(NpcDescHandle table) : base(table) { }
            }

            public readonly NpcTypeUniqueIndex NpcType;

            internal NpcDescHandle(DbConnection conn) : base(conn)
            {
                NpcType = new(this);
            }

            protected override object GetPrimaryKey(NpcDesc row) => row.NpcType;
        }

        public readonly NpcDescHandle NpcDesc;
    }

    public sealed class NpcDescCols
    {
        public global::SpacetimeDB.Col<NpcDesc, int> NpcType { get; }
        public global::SpacetimeDB.Col<NpcDesc, string> Name { get; }
        public global::SpacetimeDB.Col<NpcDesc, float> Population { get; }
        public global::SpacetimeDB.Col<NpcDesc, int> Speed { get; }
        public global::SpacetimeDB.Col<NpcDesc, int> MinTimeAtRuin { get; }
        public global::SpacetimeDB.Col<NpcDesc, int> MaxTimeAtRuin { get; }
        public global::SpacetimeDB.Col<NpcDesc, string> PrefabAddress { get; }
        public global::SpacetimeDB.Col<NpcDesc, string> IconAddress { get; }
        public global::SpacetimeDB.Col<NpcDesc, bool> ForceMarketMode { get; }
        public global::SpacetimeDB.Col<NpcDesc, System.Collections.Generic.List<int>> TaskSkillCheck { get; }

        public NpcDescCols(string tableName)
        {
            NpcType = new global::SpacetimeDB.Col<NpcDesc, int>(tableName, "npc_type");
            Name = new global::SpacetimeDB.Col<NpcDesc, string>(tableName, "name");
            Population = new global::SpacetimeDB.Col<NpcDesc, float>(tableName, "population");
            Speed = new global::SpacetimeDB.Col<NpcDesc, int>(tableName, "speed");
            MinTimeAtRuin = new global::SpacetimeDB.Col<NpcDesc, int>(tableName, "min_time_at_ruin");
            MaxTimeAtRuin = new global::SpacetimeDB.Col<NpcDesc, int>(tableName, "max_time_at_ruin");
            PrefabAddress = new global::SpacetimeDB.Col<NpcDesc, string>(tableName, "prefab_address");
            IconAddress = new global::SpacetimeDB.Col<NpcDesc, string>(tableName, "icon_address");
            ForceMarketMode = new global::SpacetimeDB.Col<NpcDesc, bool>(tableName, "force_market_mode");
            TaskSkillCheck = new global::SpacetimeDB.Col<NpcDesc, System.Collections.Generic.List<int>>(tableName, "task_skill_check");
        }
    }

    public sealed class NpcDescIxCols
    {
        public global::SpacetimeDB.IxCol<NpcDesc, int> NpcType { get; }

        public NpcDescIxCols(string tableName)
        {
            NpcType = new global::SpacetimeDB.IxCol<NpcDesc, int>(tableName, "npc_type");
        }
    }
}
