// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PavingTileDescHandle : RemoteTableHandle<EventContext, PavingTileDesc>
        {
            protected override string RemoteTableName => "paving_tile_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(PavingTileDesc row) => row.Id;

                public IdUniqueIndex(PavingTileDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal PavingTileDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(PavingTileDesc row) => row.Id;
        }

        public readonly PavingTileDescHandle PavingTileDesc;
    }

    public sealed class PavingTileDescCols
    {
        public global::SpacetimeDB.Col<PavingTileDesc, int> Id { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, string> Name { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, System.Collections.Generic.List<InputItemStack>> ConsumedItemStacks { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, int> InputCargoId { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, int> InputCargoDiscoveryScore { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, System.Collections.Generic.List<ExperienceStackF32>> ExperiencePerProgress { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, System.Collections.Generic.List<int>> DiscoveryTriggers { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, System.Collections.Generic.List<int>> RequiredKnowledges { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, int> FullDiscoveryScore { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, float> PavingDuration { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, string> PrefabAddress { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, int> Tier { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, System.Collections.Generic.List<CsvStatEntry>> StatEffects { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, string> IconAddress { get; }
        public global::SpacetimeDB.Col<PavingTileDesc, string> Description { get; }

        public PavingTileDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PavingTileDesc, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<PavingTileDesc, string>(tableName, "name");
            ConsumedItemStacks = new global::SpacetimeDB.Col<PavingTileDesc, System.Collections.Generic.List<InputItemStack>>(tableName, "consumed_item_stacks");
            InputCargoId = new global::SpacetimeDB.Col<PavingTileDesc, int>(tableName, "input_cargo_id");
            InputCargoDiscoveryScore = new global::SpacetimeDB.Col<PavingTileDesc, int>(tableName, "input_cargo_discovery_score");
            ExperiencePerProgress = new global::SpacetimeDB.Col<PavingTileDesc, System.Collections.Generic.List<ExperienceStackF32>>(tableName, "experience_per_progress");
            DiscoveryTriggers = new global::SpacetimeDB.Col<PavingTileDesc, System.Collections.Generic.List<int>>(tableName, "discovery_triggers");
            RequiredKnowledges = new global::SpacetimeDB.Col<PavingTileDesc, System.Collections.Generic.List<int>>(tableName, "required_knowledges");
            FullDiscoveryScore = new global::SpacetimeDB.Col<PavingTileDesc, int>(tableName, "full_discovery_score");
            PavingDuration = new global::SpacetimeDB.Col<PavingTileDesc, float>(tableName, "paving_duration");
            PrefabAddress = new global::SpacetimeDB.Col<PavingTileDesc, string>(tableName, "prefab_address");
            Tier = new global::SpacetimeDB.Col<PavingTileDesc, int>(tableName, "tier");
            StatEffects = new global::SpacetimeDB.Col<PavingTileDesc, System.Collections.Generic.List<CsvStatEntry>>(tableName, "stat_effects");
            IconAddress = new global::SpacetimeDB.Col<PavingTileDesc, string>(tableName, "icon_address");
            Description = new global::SpacetimeDB.Col<PavingTileDesc, string>(tableName, "description");
        }
    }

    public sealed class PavingTileDescIxCols
    {
        public global::SpacetimeDB.IxCol<PavingTileDesc, int> Id { get; }

        public PavingTileDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PavingTileDesc, int>(tableName, "id");
        }
    }
}
