// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PillarShapingRecipeDiscoveryKnowledgeDescHandle : RemoteTableHandle<EventContext, DiscoveryTriggerDesc>
        {
            protected override string RemoteTableName => "pillar_shaping_recipe_discovery_knowledge_desc";

            public sealed class KnowledgeIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(DiscoveryTriggerDesc row) => row.RequirementId;

                public KnowledgeIdIndex(PillarShapingRecipeDiscoveryKnowledgeDescHandle table) : base(table) { }
            }

            public readonly KnowledgeIdIndex KnowledgeId;

            internal PillarShapingRecipeDiscoveryKnowledgeDescHandle(DbConnection conn) : base(conn)
            {
                KnowledgeId = new(this);
            }
        }

        public readonly PillarShapingRecipeDiscoveryKnowledgeDescHandle PillarShapingRecipeDiscoveryKnowledgeDesc;
    }

    public sealed class PillarShapingRecipeDiscoveryKnowledgeDescCols
    {
        public global::SpacetimeDB.Col<DiscoveryTriggerDesc, int> RequirementId { get; }
        public global::SpacetimeDB.Col<DiscoveryTriggerDesc, int> RecipeId { get; }

        public PillarShapingRecipeDiscoveryKnowledgeDescCols(string tableName)
        {
            RequirementId = new global::SpacetimeDB.Col<DiscoveryTriggerDesc, int>(tableName, "requirement_id");
            RecipeId = new global::SpacetimeDB.Col<DiscoveryTriggerDesc, int>(tableName, "recipe_id");
        }
    }

    public sealed class PillarShapingRecipeDiscoveryKnowledgeDescIxCols
    {
        public global::SpacetimeDB.IxCol<DiscoveryTriggerDesc, int> RequirementId { get; }

        public PillarShapingRecipeDiscoveryKnowledgeDescIxCols(string tableName)
        {
            RequirementId = new global::SpacetimeDB.IxCol<DiscoveryTriggerDesc, int>(tableName, "requirement_id");
        }
    }
}
