// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlaceableGrowthDescHandle : RemoteTableHandle<EventContext, PlaceableGrowthDesc>
        {
            protected override string RemoteTableName => "placeable_growth_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(PlaceableGrowthDesc row) => row.Id;

                public IdUniqueIndex(PlaceableGrowthDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            public sealed class PlaceableIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(PlaceableGrowthDesc row) => row.PlaceableId;

                public PlaceableIdUniqueIndex(PlaceableGrowthDescHandle table) : base(table) { }
            }

            public readonly PlaceableIdUniqueIndex PlaceableId;

            internal PlaceableGrowthDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
                PlaceableId = new(this);
            }

            protected override object GetPrimaryKey(PlaceableGrowthDesc row) => row.Id;
        }

        public readonly PlaceableGrowthDescHandle PlaceableGrowthDesc;
    }

    public sealed class PlaceableGrowthDescCols
    {
        public global::SpacetimeDB.Col<PlaceableGrowthDesc, int> Id { get; }
        public global::SpacetimeDB.Col<PlaceableGrowthDesc, int> PlaceableId { get; }
        public global::SpacetimeDB.Col<PlaceableGrowthDesc, System.Collections.Generic.List<float>> Time { get; }
        public global::SpacetimeDB.Col<PlaceableGrowthDesc, System.Collections.Generic.List<PlaceableGrowthOutcome>> Outcomes { get; }
        public global::SpacetimeDB.Col<PlaceableGrowthDesc, bool> ShowTimeLeft { get; }

        public PlaceableGrowthDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<PlaceableGrowthDesc, int>(tableName, "id");
            PlaceableId = new global::SpacetimeDB.Col<PlaceableGrowthDesc, int>(tableName, "placeable_id");
            Time = new global::SpacetimeDB.Col<PlaceableGrowthDesc, System.Collections.Generic.List<float>>(tableName, "time");
            Outcomes = new global::SpacetimeDB.Col<PlaceableGrowthDesc, System.Collections.Generic.List<PlaceableGrowthOutcome>>(tableName, "outcomes");
            ShowTimeLeft = new global::SpacetimeDB.Col<PlaceableGrowthDesc, bool>(tableName, "show_time_left");
        }
    }

    public sealed class PlaceableGrowthDescIxCols
    {
        public global::SpacetimeDB.IxCol<PlaceableGrowthDesc, int> Id { get; }
        public global::SpacetimeDB.IxCol<PlaceableGrowthDesc, int> PlaceableId { get; }

        public PlaceableGrowthDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<PlaceableGrowthDesc, int>(tableName, "id");
            PlaceableId = new global::SpacetimeDB.IxCol<PlaceableGrowthDesc, int>(tableName, "placeable_id");
        }
    }
}
