// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayerHousingMovingCostStateHandle : RemoteTableHandle<EventContext, PlayerHousingMovingCostState>
        {
            protected override string RemoteTableName => "player_housing_moving_cost_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(PlayerHousingMovingCostState row) => row.EntityId;

                public EntityIdUniqueIndex(PlayerHousingMovingCostStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal PlayerHousingMovingCostStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(PlayerHousingMovingCostState row) => row.EntityId;
        }

        public readonly PlayerHousingMovingCostStateHandle PlayerHousingMovingCostState;
    }

    public sealed class PlayerHousingMovingCostStateCols
    {
        public global::SpacetimeDB.Col<PlayerHousingMovingCostState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<PlayerHousingMovingCostState, int> MovingTimeCostMinutes { get; }

        public PlayerHousingMovingCostStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<PlayerHousingMovingCostState, ulong>(tableName, "entity_id");
            MovingTimeCostMinutes = new global::SpacetimeDB.Col<PlayerHousingMovingCostState, int>(tableName, "moving_time_cost_minutes");
        }
    }

    public sealed class PlayerHousingMovingCostStateIxCols
    {
        public global::SpacetimeDB.IxCol<PlayerHousingMovingCostState, ulong> EntityId { get; }

        public PlayerHousingMovingCostStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<PlayerHousingMovingCostState, ulong>(tableName, "entity_id");
        }
    }
}
