// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class QuestChainDescHandle : RemoteTableHandle<EventContext, QuestChainDesc>
        {
            protected override string RemoteTableName => "quest_chain_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(QuestChainDesc row) => row.Id;

                public IdUniqueIndex(QuestChainDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal QuestChainDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(QuestChainDesc row) => row.Id;
        }

        public readonly QuestChainDescHandle QuestChainDesc;
    }

    public sealed class QuestChainDescCols
    {
        public global::SpacetimeDB.Col<QuestChainDesc, int> Id { get; }
        public global::SpacetimeDB.Col<QuestChainDesc, string> Name { get; }
        public global::SpacetimeDB.Col<QuestChainDesc, bool> IsHint { get; }
        public global::SpacetimeDB.Col<QuestChainDesc, System.Collections.Generic.List<int>> Stages { get; }
        public global::SpacetimeDB.Col<QuestChainDesc, System.Collections.Generic.List<QuestRequirement>> Requirements { get; }
        public global::SpacetimeDB.Col<QuestChainDesc, System.Collections.Generic.List<QuestReward>> Rewards { get; }
        public global::SpacetimeDB.Col<QuestChainDesc, System.Collections.Generic.List<QuestReward>> ImplicitRewards { get; }
        public global::SpacetimeDB.Col<QuestChainDesc, bool> Unstartable { get; }
        public global::SpacetimeDB.Col<QuestChainDesc, bool> IsSecret { get; }

        public QuestChainDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<QuestChainDesc, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<QuestChainDesc, string>(tableName, "name");
            IsHint = new global::SpacetimeDB.Col<QuestChainDesc, bool>(tableName, "is_hint");
            Stages = new global::SpacetimeDB.Col<QuestChainDesc, System.Collections.Generic.List<int>>(tableName, "stages");
            Requirements = new global::SpacetimeDB.Col<QuestChainDesc, System.Collections.Generic.List<QuestRequirement>>(tableName, "requirements");
            Rewards = new global::SpacetimeDB.Col<QuestChainDesc, System.Collections.Generic.List<QuestReward>>(tableName, "rewards");
            ImplicitRewards = new global::SpacetimeDB.Col<QuestChainDesc, System.Collections.Generic.List<QuestReward>>(tableName, "implicit_rewards");
            Unstartable = new global::SpacetimeDB.Col<QuestChainDesc, bool>(tableName, "unstartable");
            IsSecret = new global::SpacetimeDB.Col<QuestChainDesc, bool>(tableName, "is_secret");
        }
    }

    public sealed class QuestChainDescIxCols
    {
        public global::SpacetimeDB.IxCol<QuestChainDesc, int> Id { get; }

        public QuestChainDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<QuestChainDesc, int>(tableName, "id");
        }
    }
}
