// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResourcePlacementRecipeDiscoveryKnowledgeDescHandle : RemoteTableHandle<EventContext, DiscoveryTriggerDesc>
        {
            protected override string RemoteTableName => "resource_placement_recipe_discovery_knowledge_desc";

            public sealed class KnowledgeIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(DiscoveryTriggerDesc row) => row.RequirementId;

                public KnowledgeIdIndex(ResourcePlacementRecipeDiscoveryKnowledgeDescHandle table) : base(table) { }
            }

            public readonly KnowledgeIdIndex KnowledgeId;

            internal ResourcePlacementRecipeDiscoveryKnowledgeDescHandle(DbConnection conn) : base(conn)
            {
                KnowledgeId = new(this);
            }
        }

        public readonly ResourcePlacementRecipeDiscoveryKnowledgeDescHandle ResourcePlacementRecipeDiscoveryKnowledgeDesc;
    }

    public sealed class ResourcePlacementRecipeDiscoveryKnowledgeDescCols
    {
        public global::SpacetimeDB.Col<DiscoveryTriggerDesc, int> RequirementId { get; }
        public global::SpacetimeDB.Col<DiscoveryTriggerDesc, int> RecipeId { get; }

        public ResourcePlacementRecipeDiscoveryKnowledgeDescCols(string tableName)
        {
            RequirementId = new global::SpacetimeDB.Col<DiscoveryTriggerDesc, int>(tableName, "requirement_id");
            RecipeId = new global::SpacetimeDB.Col<DiscoveryTriggerDesc, int>(tableName, "recipe_id");
        }
    }

    public sealed class ResourcePlacementRecipeDiscoveryKnowledgeDescIxCols
    {
        public global::SpacetimeDB.IxCol<DiscoveryTriggerDesc, int> RequirementId { get; }

        public ResourcePlacementRecipeDiscoveryKnowledgeDescIxCols(string tableName)
        {
            RequirementId = new global::SpacetimeDB.IxCol<DiscoveryTriggerDesc, int>(tableName, "requirement_id");
        }
    }
}
