// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResourceClumpDescHandle : RemoteTableHandle<EventContext, ResourceClumpDesc>
        {
            protected override string RemoteTableName => "resource_clump_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ResourceClumpDesc row) => row.Id;

                public IdUniqueIndex(ResourceClumpDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal ResourceClumpDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ResourceClumpDesc row) => row.Id;
        }

        public readonly ResourceClumpDescHandle ResourceClumpDesc;
    }

    public sealed class ResourceClumpDescCols
    {
        public global::SpacetimeDB.Col<ResourceClumpDesc, int> Id { get; }
        public global::SpacetimeDB.Col<ResourceClumpDesc, System.Collections.Generic.List<int>> ResourceId { get; }
        public global::SpacetimeDB.Col<ResourceClumpDesc, System.Collections.Generic.List<int>> X { get; }
        public global::SpacetimeDB.Col<ResourceClumpDesc, System.Collections.Generic.List<int>> Z { get; }
        public global::SpacetimeDB.Col<ResourceClumpDesc, System.Collections.Generic.List<int>> Direction { get; }

        public ResourceClumpDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ResourceClumpDesc, int>(tableName, "id");
            ResourceId = new global::SpacetimeDB.Col<ResourceClumpDesc, System.Collections.Generic.List<int>>(tableName, "resource_id");
            X = new global::SpacetimeDB.Col<ResourceClumpDesc, System.Collections.Generic.List<int>>(tableName, "x");
            Z = new global::SpacetimeDB.Col<ResourceClumpDesc, System.Collections.Generic.List<int>>(tableName, "z");
            Direction = new global::SpacetimeDB.Col<ResourceClumpDesc, System.Collections.Generic.List<int>>(tableName, "direction");
        }
    }

    public sealed class ResourceClumpDescIxCols
    {
        public global::SpacetimeDB.IxCol<ResourceClumpDesc, int> Id { get; }

        public ResourceClumpDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ResourceClumpDesc, int>(tableName, "id");
        }
    }
}
