// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ResourceStateHandle : RemoteTableHandle<EventContext, ResourceState>
        {
            protected override string RemoteTableName => "resource_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ResourceState row) => row.EntityId;

                public EntityIdUniqueIndex(ResourceStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            public sealed class ResourceIdIndex : BTreeIndexBase<int>
            {
                protected override int GetKey(ResourceState row) => row.ResourceId;

                public ResourceIdIndex(ResourceStateHandle table) : base(table) { }
            }

            public readonly ResourceIdIndex ResourceId;

            internal ResourceStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
                ResourceId = new(this);
            }

            protected override object GetPrimaryKey(ResourceState row) => row.EntityId;
        }

        public readonly ResourceStateHandle ResourceState;
    }

    public sealed class ResourceStateCols
    {
        public global::SpacetimeDB.Col<ResourceState, ulong> EntityId { get; }
        public global::SpacetimeDB.Col<ResourceState, int> ResourceId { get; }
        public global::SpacetimeDB.Col<ResourceState, int> DirectionIndex { get; }

        public ResourceStateCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.Col<ResourceState, ulong>(tableName, "entity_id");
            ResourceId = new global::SpacetimeDB.Col<ResourceState, int>(tableName, "resource_id");
            DirectionIndex = new global::SpacetimeDB.Col<ResourceState, int>(tableName, "direction_index");
        }
    }

    public sealed class ResourceStateIxCols
    {
        public global::SpacetimeDB.IxCol<ResourceState, ulong> EntityId { get; }
        public global::SpacetimeDB.IxCol<ResourceState, int> ResourceId { get; }

        public ResourceStateIxCols(string tableName)
        {
            EntityId = new global::SpacetimeDB.IxCol<ResourceState, ulong>(tableName, "entity_id");
            ResourceId = new global::SpacetimeDB.IxCol<ResourceState, int>(tableName, "resource_id");
        }
    }
}
