// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class SingleResourceClumpInfoHandle : RemoteTableHandle<EventContext, SingleResourceClumpInfo>
        {
            protected override string RemoteTableName => "single_resource_clump_info";

            public sealed class ClumpIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(SingleResourceClumpInfo row) => row.ClumpId;

                public ClumpIdUniqueIndex(SingleResourceClumpInfoHandle table) : base(table) { }
            }

            public readonly ClumpIdUniqueIndex ClumpId;

            internal SingleResourceClumpInfoHandle(DbConnection conn) : base(conn)
            {
                ClumpId = new(this);
            }

            protected override object GetPrimaryKey(SingleResourceClumpInfo row) => row.ClumpId;
        }

        public readonly SingleResourceClumpInfoHandle SingleResourceClumpInfo;
    }
}
