// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedTravelerTradeOrderDescHandle : RemoteTableHandle<EventContext, TravelerTradeOrderDesc>
        {
            protected override string RemoteTableName => "staged_traveler_trade_order_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(TravelerTradeOrderDesc row) => row.Id;

                public IdUniqueIndex(StagedTravelerTradeOrderDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedTravelerTradeOrderDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(TravelerTradeOrderDesc row) => row.Id;
        }

        public readonly StagedTravelerTradeOrderDescHandle StagedTravelerTradeOrderDesc;
    }

    public sealed class StagedTravelerTradeOrderDescCols
    {
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, int> Id { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, int> StartingStock { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, bool> AlwaysOffered { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, NpcType> Traveler { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<ItemStack>> OfferItems { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<int>> OfferCargoId { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<ItemStack>> RequiredItems { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<int>> RequiredCargoId { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<LevelRequirement>> LevelRequirements { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<int>> AchievementRequirements { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, bool> HideIfRequirementsAreNotMet { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<int>> RequiredKnowledges { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, bool> HideWithoutRequiredKnowledge { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<int>> BlockingKnowledges { get; }
        public global::SpacetimeDB.Col<TravelerTradeOrderDesc, bool> HideWithBlockingKnowledges { get; }

        public StagedTravelerTradeOrderDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, int>(tableName, "id");
            StartingStock = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, int>(tableName, "starting_stock");
            AlwaysOffered = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, bool>(tableName, "always_offered");
            Traveler = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, NpcType>(tableName, "traveler");
            OfferItems = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<ItemStack>>(tableName, "offer_items");
            OfferCargoId = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<int>>(tableName, "offer_cargo_id");
            RequiredItems = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<ItemStack>>(tableName, "required_items");
            RequiredCargoId = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<int>>(tableName, "required_cargo_id");
            LevelRequirements = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<LevelRequirement>>(tableName, "level_requirements");
            AchievementRequirements = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<int>>(tableName, "achievement_requirements");
            HideIfRequirementsAreNotMet = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, bool>(tableName, "hide_if_requirements_are_not_met");
            RequiredKnowledges = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<int>>(tableName, "required_knowledges");
            HideWithoutRequiredKnowledge = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, bool>(tableName, "hide_without_required_knowledge");
            BlockingKnowledges = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, System.Collections.Generic.List<int>>(tableName, "blocking_knowledges");
            HideWithBlockingKnowledges = new global::SpacetimeDB.Col<TravelerTradeOrderDesc, bool>(tableName, "hide_with_blocking_knowledges");
        }
    }

    public sealed class StagedTravelerTradeOrderDescIxCols
    {
        public global::SpacetimeDB.IxCol<TravelerTradeOrderDesc, int> Id { get; }

        public StagedTravelerTradeOrderDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<TravelerTradeOrderDesc, int>(tableName, "id");
        }
    }
}
