// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedStaticDataV5Handle : RemoteTableHandle<EventContext, StagedStaticDataV5>
        {
            protected override string RemoteTableName => "staged_static_data_v5";

            public sealed class VersionUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(StagedStaticDataV5 row) => row.Version;

                public VersionUniqueIndex(StagedStaticDataV5Handle table) : base(table) { }
            }

            public readonly VersionUniqueIndex Version;

            internal StagedStaticDataV5Handle(DbConnection conn) : base(conn)
            {
                Version = new(this);
            }

            protected override object GetPrimaryKey(StagedStaticDataV5 row) => row.Version;
        }

        public readonly StagedStaticDataV5Handle StagedStaticDataV5;
    }
}
