// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedKnowledgeStatModifierDescHandle : RemoteTableHandle<EventContext, KnowledgeStatModifierDesc>
        {
            protected override string RemoteTableName => "staged_knowledge_stat_modifier_desc";

            public sealed class SecondaryKnowledgeIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(KnowledgeStatModifierDesc row) => row.SecondaryKnowledgeId;

                public SecondaryKnowledgeIdUniqueIndex(StagedKnowledgeStatModifierDescHandle table) : base(table) { }
            }

            public readonly SecondaryKnowledgeIdUniqueIndex SecondaryKnowledgeId;

            internal StagedKnowledgeStatModifierDescHandle(DbConnection conn) : base(conn)
            {
                SecondaryKnowledgeId = new(this);
            }

            protected override object GetPrimaryKey(KnowledgeStatModifierDesc row) => row.SecondaryKnowledgeId;
        }

        public readonly StagedKnowledgeStatModifierDescHandle StagedKnowledgeStatModifierDesc;
    }

    public sealed class StagedKnowledgeStatModifierDescCols
    {
        public global::SpacetimeDB.Col<KnowledgeStatModifierDesc, int> SecondaryKnowledgeId { get; }
        public global::SpacetimeDB.Col<KnowledgeStatModifierDesc, System.Collections.Generic.List<CsvStatEntry>> Stats { get; }

        public StagedKnowledgeStatModifierDescCols(string tableName)
        {
            SecondaryKnowledgeId = new global::SpacetimeDB.Col<KnowledgeStatModifierDesc, int>(tableName, "secondary_knowledge_id");
            Stats = new global::SpacetimeDB.Col<KnowledgeStatModifierDesc, System.Collections.Generic.List<CsvStatEntry>>(tableName, "stats");
        }
    }

    public sealed class StagedKnowledgeStatModifierDescIxCols
    {
        public global::SpacetimeDB.IxCol<KnowledgeStatModifierDesc, int> SecondaryKnowledgeId { get; }

        public StagedKnowledgeStatModifierDescIxCols(string tableName)
        {
            SecondaryKnowledgeId = new global::SpacetimeDB.IxCol<KnowledgeStatModifierDesc, int>(tableName, "secondary_knowledge_id");
        }
    }
}
