// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedWeaponDescHandle : RemoteTableHandle<EventContext, WeaponDesc>
        {
            protected override string RemoteTableName => "staged_weapon_desc";

            public sealed class ItemIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(WeaponDesc row) => row.ItemId;

                public ItemIdUniqueIndex(StagedWeaponDescHandle table) : base(table) { }
            }

            public readonly ItemIdUniqueIndex ItemId;

            internal StagedWeaponDescHandle(DbConnection conn) : base(conn)
            {
                ItemId = new(this);
            }

            protected override object GetPrimaryKey(WeaponDesc row) => row.ItemId;
        }

        public readonly StagedWeaponDescHandle StagedWeaponDesc;
    }
}
