// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedInteriorShapeDescHandle : RemoteTableHandle<EventContext, InteriorShapeDesc>
        {
            protected override string RemoteTableName => "staged_interior_shape_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(InteriorShapeDesc row) => row.Id;

                public IdUniqueIndex(StagedInteriorShapeDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedInteriorShapeDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(InteriorShapeDesc row) => row.Id;
        }

        public readonly StagedInteriorShapeDescHandle StagedInteriorShapeDesc;
    }

    public sealed class StagedInteriorShapeDescCols
    {
        public global::SpacetimeDB.Col<InteriorShapeDesc, int> Id { get; }
        public global::SpacetimeDB.Col<InteriorShapeDesc, System.Collections.Generic.List<FootprintTile>> Footprint { get; }
        public global::SpacetimeDB.Col<InteriorShapeDesc, int> MinX { get; }
        public global::SpacetimeDB.Col<InteriorShapeDesc, int> MinZ { get; }
        public global::SpacetimeDB.Col<InteriorShapeDesc, int> SizeX { get; }
        public global::SpacetimeDB.Col<InteriorShapeDesc, int> SizeZ { get; }

        public StagedInteriorShapeDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<InteriorShapeDesc, int>(tableName, "id");
            Footprint = new global::SpacetimeDB.Col<InteriorShapeDesc, System.Collections.Generic.List<FootprintTile>>(tableName, "footprint");
            MinX = new global::SpacetimeDB.Col<InteriorShapeDesc, int>(tableName, "min_x");
            MinZ = new global::SpacetimeDB.Col<InteriorShapeDesc, int>(tableName, "min_z");
            SizeX = new global::SpacetimeDB.Col<InteriorShapeDesc, int>(tableName, "size_x");
            SizeZ = new global::SpacetimeDB.Col<InteriorShapeDesc, int>(tableName, "size_z");
        }
    }

    public sealed class StagedInteriorShapeDescIxCols
    {
        public global::SpacetimeDB.IxCol<InteriorShapeDesc, int> Id { get; }

        public StagedInteriorShapeDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<InteriorShapeDesc, int>(tableName, "id");
        }
    }
}
