// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedWindParamsDescHandle : RemoteTableHandle<EventContext, WindParamsDesc>
        {
            protected override string RemoteTableName => "staged_wind_params_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(WindParamsDesc row) => row.Id;

                public IdUniqueIndex(StagedWindParamsDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedWindParamsDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(WindParamsDesc row) => row.Id;
        }

        public readonly StagedWindParamsDescHandle StagedWindParamsDesc;
    }

    public sealed class StagedWindParamsDescCols
    {
        public global::SpacetimeDB.Col<WindParamsDesc, int> Id { get; }
        public global::SpacetimeDB.Col<WindParamsDesc, double> Scale { get; }
        public global::SpacetimeDB.Col<WindParamsDesc, double> Weight { get; }
        public global::SpacetimeDB.Col<WindParamsDesc, ulong> CycleSec { get; }

        public StagedWindParamsDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<WindParamsDesc, int>(tableName, "id");
            Scale = new global::SpacetimeDB.Col<WindParamsDesc, double>(tableName, "scale");
            Weight = new global::SpacetimeDB.Col<WindParamsDesc, double>(tableName, "weight");
            CycleSec = new global::SpacetimeDB.Col<WindParamsDesc, ulong>(tableName, "cycle_sec");
        }
    }

    public sealed class StagedWindParamsDescIxCols
    {
        public global::SpacetimeDB.IxCol<WindParamsDesc, int> Id { get; }

        public StagedWindParamsDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<WindParamsDesc, int>(tableName, "id");
        }
    }
}
