// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedEnemyScalingDescHandle : RemoteTableHandle<EventContext, EnemyScalingDesc>
        {
            protected override string RemoteTableName => "staged_enemy_scaling_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(EnemyScalingDesc row) => row.Id;

                public IdUniqueIndex(StagedEnemyScalingDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedEnemyScalingDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(EnemyScalingDesc row) => row.Id;
        }

        public readonly StagedEnemyScalingDescHandle StagedEnemyScalingDesc;
    }

    public sealed class StagedEnemyScalingDescCols
    {
        public global::SpacetimeDB.Col<EnemyScalingDesc, int> Id { get; }
        public global::SpacetimeDB.Col<EnemyScalingDesc, int> EnemyTypeId { get; }
        public global::SpacetimeDB.Col<EnemyScalingDesc, int> RequiredPlayersCount { get; }
        public global::SpacetimeDB.Col<EnemyScalingDesc, int> ScaledArmorBonus { get; }
        public global::SpacetimeDB.Col<EnemyScalingDesc, int> StrengthBonus { get; }
        public global::SpacetimeDB.Col<EnemyScalingDesc, int> AccuracyBonus { get; }
        public global::SpacetimeDB.Col<EnemyScalingDesc, int> EvasionBonus { get; }
        public global::SpacetimeDB.Col<EnemyScalingDesc, int> MinDamageBonus { get; }
        public global::SpacetimeDB.Col<EnemyScalingDesc, int> MaxDamageBonus { get; }

        public StagedEnemyScalingDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<EnemyScalingDesc, int>(tableName, "id");
            EnemyTypeId = new global::SpacetimeDB.Col<EnemyScalingDesc, int>(tableName, "enemy_type_id");
            RequiredPlayersCount = new global::SpacetimeDB.Col<EnemyScalingDesc, int>(tableName, "required_players_count");
            ScaledArmorBonus = new global::SpacetimeDB.Col<EnemyScalingDesc, int>(tableName, "scaled_armor_bonus");
            StrengthBonus = new global::SpacetimeDB.Col<EnemyScalingDesc, int>(tableName, "strength_bonus");
            AccuracyBonus = new global::SpacetimeDB.Col<EnemyScalingDesc, int>(tableName, "accuracy_bonus");
            EvasionBonus = new global::SpacetimeDB.Col<EnemyScalingDesc, int>(tableName, "evasion_bonus");
            MinDamageBonus = new global::SpacetimeDB.Col<EnemyScalingDesc, int>(tableName, "min_damage_bonus");
            MaxDamageBonus = new global::SpacetimeDB.Col<EnemyScalingDesc, int>(tableName, "max_damage_bonus");
        }
    }

    public sealed class StagedEnemyScalingDescIxCols
    {
        public global::SpacetimeDB.IxCol<EnemyScalingDesc, int> Id { get; }

        public StagedEnemyScalingDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<EnemyScalingDesc, int>(tableName, "id");
        }
    }
}
