// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedCollectibleDescHandle : RemoteTableHandle<EventContext, CollectibleDesc>
        {
            protected override string RemoteTableName => "staged_collectible_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CollectibleDesc row) => row.Id;

                public IdUniqueIndex(StagedCollectibleDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedCollectibleDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(CollectibleDesc row) => row.Id;
        }

        public readonly StagedCollectibleDescHandle StagedCollectibleDesc;
    }

    public sealed class StagedCollectibleDescCols
    {
        public global::SpacetimeDB.Col<CollectibleDesc, int> Id { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, string> Name { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, string> Description { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, CollectibleType> CollectibleType { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, CollectibleType> InvalidatesType { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, bool> AutoCollect { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, Rarity> CollectibleRarity { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, bool> StartingLoadout { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, bool> Locked { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, int> Variant { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, string> Color { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, string> Emission { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, int> MaxEquipCount { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, string> ModelAssetName { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, string> VariantMaterial { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, string> IconAssetName { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, string> Tag { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, string> DisplayString { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, int> ItemDeedId { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, System.Collections.Generic.List<int>> RequiredKnowledgesToUse { get; }
        public global::SpacetimeDB.Col<CollectibleDesc, System.Collections.Generic.List<int>> RequiredKnowledgesToConvert { get; }

        public StagedCollectibleDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<CollectibleDesc, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<CollectibleDesc, string>(tableName, "name");
            Description = new global::SpacetimeDB.Col<CollectibleDesc, string>(tableName, "description");
            CollectibleType = new global::SpacetimeDB.Col<CollectibleDesc, CollectibleType>(tableName, "collectible_type");
            InvalidatesType = new global::SpacetimeDB.Col<CollectibleDesc, CollectibleType>(tableName, "invalidates_type");
            AutoCollect = new global::SpacetimeDB.Col<CollectibleDesc, bool>(tableName, "auto_collect");
            CollectibleRarity = new global::SpacetimeDB.Col<CollectibleDesc, Rarity>(tableName, "collectible_rarity");
            StartingLoadout = new global::SpacetimeDB.Col<CollectibleDesc, bool>(tableName, "starting_loadout");
            Locked = new global::SpacetimeDB.Col<CollectibleDesc, bool>(tableName, "locked");
            Variant = new global::SpacetimeDB.Col<CollectibleDesc, int>(tableName, "variant");
            Color = new global::SpacetimeDB.Col<CollectibleDesc, string>(tableName, "color");
            Emission = new global::SpacetimeDB.Col<CollectibleDesc, string>(tableName, "emission");
            MaxEquipCount = new global::SpacetimeDB.Col<CollectibleDesc, int>(tableName, "max_equip_count");
            ModelAssetName = new global::SpacetimeDB.Col<CollectibleDesc, string>(tableName, "model_asset_name");
            VariantMaterial = new global::SpacetimeDB.Col<CollectibleDesc, string>(tableName, "variant_material");
            IconAssetName = new global::SpacetimeDB.Col<CollectibleDesc, string>(tableName, "icon_asset_name");
            Tag = new global::SpacetimeDB.Col<CollectibleDesc, string>(tableName, "tag");
            DisplayString = new global::SpacetimeDB.Col<CollectibleDesc, string>(tableName, "display_string");
            ItemDeedId = new global::SpacetimeDB.Col<CollectibleDesc, int>(tableName, "item_deed_id");
            RequiredKnowledgesToUse = new global::SpacetimeDB.Col<CollectibleDesc, System.Collections.Generic.List<int>>(tableName, "required_knowledges_to_use");
            RequiredKnowledgesToConvert = new global::SpacetimeDB.Col<CollectibleDesc, System.Collections.Generic.List<int>>(tableName, "required_knowledges_to_convert");
        }
    }

    public sealed class StagedCollectibleDescIxCols
    {
        public global::SpacetimeDB.IxCol<CollectibleDesc, int> Id { get; }

        public StagedCollectibleDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<CollectibleDesc, int>(tableName, "id");
        }
    }
}
