// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedInteriorPortalConnectionsDescHandle : RemoteTableHandle<EventContext, InteriorPortalConnectionsDesc>
        {
            protected override string RemoteTableName => "staged_interior_portal_connections_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(InteriorPortalConnectionsDesc row) => row.Id;

                public IdUniqueIndex(StagedInteriorPortalConnectionsDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedInteriorPortalConnectionsDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(InteriorPortalConnectionsDesc row) => row.Id;
        }

        public readonly StagedInteriorPortalConnectionsDescHandle StagedInteriorPortalConnectionsDesc;
    }

    public sealed class StagedInteriorPortalConnectionsDescCols
    {
        public global::SpacetimeDB.Col<InteriorPortalConnectionsDesc, int> Id { get; }
        public global::SpacetimeDB.Col<InteriorPortalConnectionsDesc, int> EntranceSpawnId { get; }
        public global::SpacetimeDB.Col<InteriorPortalConnectionsDesc, int> EntrancePortalId { get; }
        public global::SpacetimeDB.Col<InteriorPortalConnectionsDesc, int> ExitSpawnId { get; }
        public global::SpacetimeDB.Col<InteriorPortalConnectionsDesc, int> ExitPortalId { get; }

        public StagedInteriorPortalConnectionsDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<InteriorPortalConnectionsDesc, int>(tableName, "id");
            EntranceSpawnId = new global::SpacetimeDB.Col<InteriorPortalConnectionsDesc, int>(tableName, "entrance_spawn_id");
            EntrancePortalId = new global::SpacetimeDB.Col<InteriorPortalConnectionsDesc, int>(tableName, "entrance_portal_id");
            ExitSpawnId = new global::SpacetimeDB.Col<InteriorPortalConnectionsDesc, int>(tableName, "exit_spawn_id");
            ExitPortalId = new global::SpacetimeDB.Col<InteriorPortalConnectionsDesc, int>(tableName, "exit_portal_id");
        }
    }

    public sealed class StagedInteriorPortalConnectionsDescIxCols
    {
        public global::SpacetimeDB.IxCol<InteriorPortalConnectionsDesc, int> Id { get; }

        public StagedInteriorPortalConnectionsDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<InteriorPortalConnectionsDesc, int>(tableName, "id");
        }
    }
}
