// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedItemDescHandle : RemoteTableHandle<EventContext, ItemDesc>
        {
            protected override string RemoteTableName => "staged_item_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(ItemDesc row) => row.Id;

                public IdUniqueIndex(StagedItemDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedItemDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(ItemDesc row) => row.Id;
        }

        public readonly StagedItemDescHandle StagedItemDesc;
    }

    public sealed class StagedItemDescCols
    {
        public global::SpacetimeDB.Col<ItemDesc, int> Id { get; }
        public global::SpacetimeDB.Col<ItemDesc, string> Name { get; }
        public global::SpacetimeDB.Col<ItemDesc, string> Description { get; }
        public global::SpacetimeDB.Col<ItemDesc, int> Volume { get; }
        public global::SpacetimeDB.Col<ItemDesc, int> Durability { get; }
        public global::SpacetimeDB.Col<ItemDesc, int> ConvertToOnDurabilityZero { get; }
        public global::SpacetimeDB.Col<ItemDesc, int> SecondaryKnowledgeId { get; }
        public global::SpacetimeDB.Col<ItemDesc, string> ModelAssetName { get; }
        public global::SpacetimeDB.Col<ItemDesc, string> IconAssetName { get; }
        public global::SpacetimeDB.Col<ItemDesc, int> Tier { get; }
        public global::SpacetimeDB.Col<ItemDesc, string> Tag { get; }
        public global::SpacetimeDB.Col<ItemDesc, Rarity> Rarity { get; }
        public global::SpacetimeDB.Col<ItemDesc, bool> CompendiumEntry { get; }
        public global::SpacetimeDB.Col<ItemDesc, int> ItemListId { get; }

        public StagedItemDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<ItemDesc, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<ItemDesc, string>(tableName, "name");
            Description = new global::SpacetimeDB.Col<ItemDesc, string>(tableName, "description");
            Volume = new global::SpacetimeDB.Col<ItemDesc, int>(tableName, "volume");
            Durability = new global::SpacetimeDB.Col<ItemDesc, int>(tableName, "durability");
            ConvertToOnDurabilityZero = new global::SpacetimeDB.Col<ItemDesc, int>(tableName, "convert_to_on_durability_zero");
            SecondaryKnowledgeId = new global::SpacetimeDB.Col<ItemDesc, int>(tableName, "secondary_knowledge_id");
            ModelAssetName = new global::SpacetimeDB.Col<ItemDesc, string>(tableName, "model_asset_name");
            IconAssetName = new global::SpacetimeDB.Col<ItemDesc, string>(tableName, "icon_asset_name");
            Tier = new global::SpacetimeDB.Col<ItemDesc, int>(tableName, "tier");
            Tag = new global::SpacetimeDB.Col<ItemDesc, string>(tableName, "tag");
            Rarity = new global::SpacetimeDB.Col<ItemDesc, Rarity>(tableName, "rarity");
            CompendiumEntry = new global::SpacetimeDB.Col<ItemDesc, bool>(tableName, "compendium_entry");
            ItemListId = new global::SpacetimeDB.Col<ItemDesc, int>(tableName, "item_list_id");
        }
    }

    public sealed class StagedItemDescIxCols
    {
        public global::SpacetimeDB.IxCol<ItemDesc, int> Id { get; }

        public StagedItemDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<ItemDesc, int>(tableName, "id");
        }
    }
}
