// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedGateDescHandle : RemoteTableHandle<EventContext, GateDesc>
        {
            protected override string RemoteTableName => "staged_gate_desc";

            public sealed class BuildingIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(GateDesc row) => row.BuildingId;

                public BuildingIdUniqueIndex(StagedGateDescHandle table) : base(table) { }
            }

            public readonly BuildingIdUniqueIndex BuildingId;

            internal StagedGateDescHandle(DbConnection conn) : base(conn)
            {
                BuildingId = new(this);
            }

            protected override object GetPrimaryKey(GateDesc row) => row.BuildingId;
        }

        public readonly StagedGateDescHandle StagedGateDesc;
    }

    public sealed class StagedGateDescCols
    {
        public global::SpacetimeDB.Col<GateDesc, int> BuildingId { get; }
        public global::SpacetimeDB.Col<GateDesc, string> SmallPostAssetName { get; }

        public StagedGateDescCols(string tableName)
        {
            BuildingId = new global::SpacetimeDB.Col<GateDesc, int>(tableName, "building_id");
            SmallPostAssetName = new global::SpacetimeDB.Col<GateDesc, string>(tableName, "small_post_asset_name");
        }
    }

    public sealed class StagedGateDescIxCols
    {
        public global::SpacetimeDB.IxCol<GateDesc, int> BuildingId { get; }

        public StagedGateDescIxCols(string tableName)
        {
            BuildingId = new global::SpacetimeDB.IxCol<GateDesc, int>(tableName, "building_id");
        }
    }
}
