// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedTargetingMatrixDescHandle : RemoteTableHandle<EventContext, TargetingMatrixDesc>
        {
            protected override string RemoteTableName => "staged_targeting_matrix_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(TargetingMatrixDesc row) => row.Id;

                public IdUniqueIndex(StagedTargetingMatrixDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedTargetingMatrixDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(TargetingMatrixDesc row) => row.Id;
        }

        public readonly StagedTargetingMatrixDescHandle StagedTargetingMatrixDesc;
    }
}
