// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedCombatActionMultiHitDescHandle : RemoteTableHandle<EventContext, CombatActionMultiHitDesc>
        {
            protected override string RemoteTableName => "staged_combat_action_multi_hit_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(CombatActionMultiHitDesc row) => row.Id;

                public IdUniqueIndex(StagedCombatActionMultiHitDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal StagedCombatActionMultiHitDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(CombatActionMultiHitDesc row) => row.Id;
        }

        public readonly StagedCombatActionMultiHitDescHandle StagedCombatActionMultiHitDesc;
    }

    public sealed class StagedCombatActionMultiHitDescCols
    {
        public global::SpacetimeDB.Col<CombatActionMultiHitDesc, int> Id { get; }
        public global::SpacetimeDB.Col<CombatActionMultiHitDesc, System.Collections.Generic.List<FootprintTile>> AreaFootprint { get; }
        public global::SpacetimeDB.Col<CombatActionMultiHitDesc, int> MaxSecondaryTargets { get; }
        public global::SpacetimeDB.Col<CombatActionMultiHitDesc, float> SecondaryTargetMultiplier { get; }

        public StagedCombatActionMultiHitDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<CombatActionMultiHitDesc, int>(tableName, "id");
            AreaFootprint = new global::SpacetimeDB.Col<CombatActionMultiHitDesc, System.Collections.Generic.List<FootprintTile>>(tableName, "area_footprint");
            MaxSecondaryTargets = new global::SpacetimeDB.Col<CombatActionMultiHitDesc, int>(tableName, "max_secondary_targets");
            SecondaryTargetMultiplier = new global::SpacetimeDB.Col<CombatActionMultiHitDesc, float>(tableName, "secondary_target_multiplier");
        }
    }

    public sealed class StagedCombatActionMultiHitDescIxCols
    {
        public global::SpacetimeDB.IxCol<CombatActionMultiHitDesc, int> Id { get; }

        public StagedCombatActionMultiHitDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<CombatActionMultiHitDesc, int>(tableName, "id");
        }
    }
}
