// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedBuildingRepairsDescHandle : RemoteTableHandle<EventContext, BuildingRepairsDesc>
        {
            protected override string RemoteTableName => "staged_building_repairs_desc";

            public sealed class CargoIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(BuildingRepairsDesc row) => row.CargoId;

                public CargoIdUniqueIndex(StagedBuildingRepairsDescHandle table) : base(table) { }
            }

            public readonly CargoIdUniqueIndex CargoId;

            internal StagedBuildingRepairsDescHandle(DbConnection conn) : base(conn)
            {
                CargoId = new(this);
            }

            protected override object GetPrimaryKey(BuildingRepairsDesc row) => row.CargoId;
        }

        public readonly StagedBuildingRepairsDescHandle StagedBuildingRepairsDesc;
    }
}
