// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StagedBiomeDescHandle : RemoteTableHandle<EventContext, BiomeDesc>
        {
            protected override string RemoteTableName => "staged_biome_desc";

            public sealed class BiomeTypeUniqueIndex : UniqueIndexBase<byte>
            {
                protected override byte GetKey(BiomeDesc row) => row.BiomeType;

                public BiomeTypeUniqueIndex(StagedBiomeDescHandle table) : base(table) { }
            }

            public readonly BiomeTypeUniqueIndex BiomeType;

            internal StagedBiomeDescHandle(DbConnection conn) : base(conn)
            {
                BiomeType = new(this);
            }

            protected override object GetPrimaryKey(BiomeDesc row) => row.BiomeType;
        }

        public readonly StagedBiomeDescHandle StagedBiomeDesc;
    }

    public sealed class StagedBiomeDescCols
    {
        public global::SpacetimeDB.Col<BiomeDesc, byte> BiomeType { get; }
        public global::SpacetimeDB.Col<BiomeDesc, string> Name { get; }
        public global::SpacetimeDB.Col<BiomeDesc, string> Description { get; }
        public global::SpacetimeDB.Col<BiomeDesc, string> HazardLevel { get; }
        public global::SpacetimeDB.Col<BiomeDesc, string> IconAddress { get; }
        public global::SpacetimeDB.Col<BiomeDesc, bool> DisallowPlayerBuild { get; }

        public StagedBiomeDescCols(string tableName)
        {
            BiomeType = new global::SpacetimeDB.Col<BiomeDesc, byte>(tableName, "biome_type");
            Name = new global::SpacetimeDB.Col<BiomeDesc, string>(tableName, "name");
            Description = new global::SpacetimeDB.Col<BiomeDesc, string>(tableName, "description");
            HazardLevel = new global::SpacetimeDB.Col<BiomeDesc, string>(tableName, "hazard_level");
            IconAddress = new global::SpacetimeDB.Col<BiomeDesc, string>(tableName, "icon_address");
            DisallowPlayerBuild = new global::SpacetimeDB.Col<BiomeDesc, bool>(tableName, "disallow_player_build");
        }
    }

    public sealed class StagedBiomeDescIxCols
    {
        public global::SpacetimeDB.IxCol<BiomeDesc, byte> BiomeType { get; }

        public StagedBiomeDescIxCols(string tableName)
        {
            BiomeType = new global::SpacetimeDB.IxCol<BiomeDesc, byte>(tableName, "biome_type");
        }
    }
}
