// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class StarvingLoopTimerHandle : RemoteTableHandle<EventContext, StarvingLoopTimer>
        {
            protected override string RemoteTableName => "starving_loop_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(StarvingLoopTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(StarvingLoopTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal StarvingLoopTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(StarvingLoopTimer row) => row.ScheduledId;
        }

        public readonly StarvingLoopTimerHandle StarvingLoopTimer;
    }

    public sealed class StarvingLoopTimerCols
    {
        public global::SpacetimeDB.Col<StarvingLoopTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<StarvingLoopTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }

        public StarvingLoopTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<StarvingLoopTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<StarvingLoopTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
        }
    }

    public sealed class StarvingLoopTimerIxCols
    {
        public global::SpacetimeDB.IxCol<StarvingLoopTimer, ulong> ScheduledId { get; }

        public StarvingLoopTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<StarvingLoopTimer, ulong>(tableName, "scheduled_id");
        }
    }
}
