// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TeleportItemDescHandle : RemoteTableHandle<EventContext, TeleportItemDesc>
        {
            protected override string RemoteTableName => "teleport_item_desc";

            public sealed class IdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(TeleportItemDesc row) => row.Id;

                public IdUniqueIndex(TeleportItemDescHandle table) : base(table) { }
            }

            public readonly IdUniqueIndex Id;

            internal TeleportItemDescHandle(DbConnection conn) : base(conn)
            {
                Id = new(this);
            }

            protected override object GetPrimaryKey(TeleportItemDesc row) => row.Id;
        }

        public readonly TeleportItemDescHandle TeleportItemDesc;
    }

    public sealed class TeleportItemDescCols
    {
        public global::SpacetimeDB.Col<TeleportItemDesc, int> Id { get; }
        public global::SpacetimeDB.Col<TeleportItemDesc, string> Name { get; }
        public global::SpacetimeDB.Col<TeleportItemDesc, int> BuffId { get; }

        public TeleportItemDescCols(string tableName)
        {
            Id = new global::SpacetimeDB.Col<TeleportItemDesc, int>(tableName, "id");
            Name = new global::SpacetimeDB.Col<TeleportItemDesc, string>(tableName, "name");
            BuffId = new global::SpacetimeDB.Col<TeleportItemDesc, int>(tableName, "buff_id");
        }
    }

    public sealed class TeleportItemDescIxCols
    {
        public global::SpacetimeDB.IxCol<TeleportItemDesc, int> Id { get; }

        public TeleportItemDescIxCols(string tableName)
        {
            Id = new global::SpacetimeDB.IxCol<TeleportItemDesc, int>(tableName, "id");
        }
    }
}
