// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TravelerTaskKnowledgeRequirementDescHandle : RemoteTableHandle<EventContext, TravelerTaskKnowledgeRequirementDesc>
        {
            protected override string RemoteTableName => "traveler_task_knowledge_requirement_desc";

            public sealed class TravelerTaskIdUniqueIndex : UniqueIndexBase<int>
            {
                protected override int GetKey(TravelerTaskKnowledgeRequirementDesc row) => row.TravelerTaskId;

                public TravelerTaskIdUniqueIndex(TravelerTaskKnowledgeRequirementDescHandle table) : base(table) { }
            }

            public readonly TravelerTaskIdUniqueIndex TravelerTaskId;

            internal TravelerTaskKnowledgeRequirementDescHandle(DbConnection conn) : base(conn)
            {
                TravelerTaskId = new(this);
            }

            protected override object GetPrimaryKey(TravelerTaskKnowledgeRequirementDesc row) => row.TravelerTaskId;
        }

        public readonly TravelerTaskKnowledgeRequirementDescHandle TravelerTaskKnowledgeRequirementDesc;
    }

    public sealed class TravelerTaskKnowledgeRequirementDescCols
    {
        public global::SpacetimeDB.Col<TravelerTaskKnowledgeRequirementDesc, int> TravelerTaskId { get; }
        public global::SpacetimeDB.Col<TravelerTaskKnowledgeRequirementDesc, System.Collections.Generic.List<int>> RequiredKnowledges { get; }
        public global::SpacetimeDB.Col<TravelerTaskKnowledgeRequirementDesc, System.Collections.Generic.List<int>> BlockingKnowledges { get; }

        public TravelerTaskKnowledgeRequirementDescCols(string tableName)
        {
            TravelerTaskId = new global::SpacetimeDB.Col<TravelerTaskKnowledgeRequirementDesc, int>(tableName, "traveler_task_id");
            RequiredKnowledges = new global::SpacetimeDB.Col<TravelerTaskKnowledgeRequirementDesc, System.Collections.Generic.List<int>>(tableName, "required_knowledges");
            BlockingKnowledges = new global::SpacetimeDB.Col<TravelerTaskKnowledgeRequirementDesc, System.Collections.Generic.List<int>>(tableName, "blocking_knowledges");
        }
    }

    public sealed class TravelerTaskKnowledgeRequirementDescIxCols
    {
        public global::SpacetimeDB.IxCol<TravelerTaskKnowledgeRequirementDesc, int> TravelerTaskId { get; }

        public TravelerTaskKnowledgeRequirementDescIxCols(string tableName)
        {
            TravelerTaskId = new global::SpacetimeDB.IxCol<TravelerTaskKnowledgeRequirementDesc, int>(tableName, "traveler_task_id");
        }
    }
}
