// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TravelerTaskLoopTimerHandle : RemoteTableHandle<EventContext, TravelerTaskLoopTimer>
        {
            protected override string RemoteTableName => "traveler_task_loop_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(TravelerTaskLoopTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(TravelerTaskLoopTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal TravelerTaskLoopTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(TravelerTaskLoopTimer row) => row.ScheduledId;
        }

        public readonly TravelerTaskLoopTimerHandle TravelerTaskLoopTimer;
    }
}
