// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UnclaimedCollectiblesStateHandle : RemoteTableHandle<EventContext, UnclaimedCollectiblesState>
        {
            protected override string RemoteTableName => "unclaimed_collectibles_state";

            public sealed class IdentityUniqueIndex : UniqueIndexBase<SpacetimeDB.Identity>
            {
                protected override SpacetimeDB.Identity GetKey(UnclaimedCollectiblesState row) => row.Identity;

                public IdentityUniqueIndex(UnclaimedCollectiblesStateHandle table) : base(table) { }
            }

            public readonly IdentityUniqueIndex Identity;

            internal UnclaimedCollectiblesStateHandle(DbConnection conn) : base(conn)
            {
                Identity = new(this);
            }

            protected override object GetPrimaryKey(UnclaimedCollectiblesState row) => row.Identity;
        }

        public readonly UnclaimedCollectiblesStateHandle UnclaimedCollectiblesState;
    }

    public sealed class UnclaimedCollectiblesStateCols
    {
        public global::SpacetimeDB.Col<UnclaimedCollectiblesState, SpacetimeDB.Identity> Identity { get; }
        public global::SpacetimeDB.Col<UnclaimedCollectiblesState, System.Collections.Generic.List<int>> Collectibles { get; }

        public UnclaimedCollectiblesStateCols(string tableName)
        {
            Identity = new global::SpacetimeDB.Col<UnclaimedCollectiblesState, SpacetimeDB.Identity>(tableName, "identity");
            Collectibles = new global::SpacetimeDB.Col<UnclaimedCollectiblesState, System.Collections.Generic.List<int>>(tableName, "collectibles");
        }
    }

    public sealed class UnclaimedCollectiblesStateIxCols
    {
        public global::SpacetimeDB.IxCol<UnclaimedCollectiblesState, SpacetimeDB.Identity> Identity { get; }

        public UnclaimedCollectiblesStateIxCols(string tableName)
        {
            Identity = new global::SpacetimeDB.IxCol<UnclaimedCollectiblesState, SpacetimeDB.Identity>(tableName, "identity");
        }
    }
}
