// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheatDiscoverMapHandler(ReducerEventContext ctx, CheatDiscoverMapRequest request);
        public event CheatDiscoverMapHandler? OnCheatDiscoverMap;

        public void CheatDiscoverMap(CheatDiscoverMapRequest request)
        {
            conn.InternalCallReducer(new Reducer.CheatDiscoverMap(request), this.SetCallReducerFlags.CheatDiscoverMapFlags);
        }

        public bool InvokeCheatDiscoverMap(ReducerEventContext ctx, Reducer.CheatDiscoverMap args)
        {
            if (OnCheatDiscoverMap == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCheatDiscoverMap(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheatDiscoverMap : Reducer, IReducerArgs
        {
            [DataMember(Name = "request")]
            public CheatDiscoverMapRequest Request;

            public CheatDiscoverMap(CheatDiscoverMapRequest Request)
            {
                this.Request = Request;
            }

            public CheatDiscoverMap()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "cheat_discover_map";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CheatDiscoverMapFlags;
        public void CheatDiscoverMap(CallReducerFlags flags) => CheatDiscoverMapFlags = flags;
    }
}
