// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void CheatClearBuffsAndDebuffsHandler(ReducerEventContext ctx, ulong playerEntityId);
        public event CheatClearBuffsAndDebuffsHandler? OnCheatClearBuffsAndDebuffs;

        public void CheatClearBuffsAndDebuffs(ulong playerEntityId)
        {
            conn.InternalCallReducer(new Reducer.CheatClearBuffsAndDebuffs(playerEntityId), this.SetCallReducerFlags.CheatClearBuffsAndDebuffsFlags);
        }

        public bool InvokeCheatClearBuffsAndDebuffs(ReducerEventContext ctx, Reducer.CheatClearBuffsAndDebuffs args)
        {
            if (OnCheatClearBuffsAndDebuffs == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnCheatClearBuffsAndDebuffs(
                ctx,
                args.PlayerEntityId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class CheatClearBuffsAndDebuffs : Reducer, IReducerArgs
        {
            [DataMember(Name = "player_entity_id")]
            public ulong PlayerEntityId;

            public CheatClearBuffsAndDebuffs(ulong PlayerEntityId)
            {
                this.PlayerEntityId = PlayerEntityId;
            }

            public CheatClearBuffsAndDebuffs()
            {
            }

            string IReducerArgs.ReducerName => "cheat_clear_buffs_and_debuffs";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags CheatClearBuffsAndDebuffsFlags;
        public void CheatClearBuffsAndDebuffs(CallReducerFlags flags) => CheatClearBuffsAndDebuffsFlags = flags;
    }
}
