// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportSatiationStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<SatiationState> records);
        public event ImportSatiationStateHandler? OnImportSatiationState;

        public void ImportSatiationState(System.Collections.Generic.List<SatiationState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportSatiationState(records), this.SetCallReducerFlags.ImportSatiationStateFlags);
        }

        public bool InvokeImportSatiationState(ReducerEventContext ctx, Reducer.ImportSatiationState args)
        {
            if (OnImportSatiationState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportSatiationState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportSatiationState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<SatiationState> Records;

            public ImportSatiationState(System.Collections.Generic.List<SatiationState> Records)
            {
                this.Records = Records;
            }

            public ImportSatiationState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_satiation_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportSatiationStateFlags;
        public void ImportSatiationState(CallReducerFlags flags) => ImportSatiationStateFlags = flags;
    }
}
