// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportResourceCountHandler(ReducerEventContext ctx, System.Collections.Generic.List<ResourceCount> records);
        public event ImportResourceCountHandler? OnImportResourceCount;

        public void ImportResourceCount(System.Collections.Generic.List<ResourceCount> records)
        {
            conn.InternalCallReducer(new Reducer.ImportResourceCount(records), this.SetCallReducerFlags.ImportResourceCountFlags);
        }

        public bool InvokeImportResourceCount(ReducerEventContext ctx, Reducer.ImportResourceCount args)
        {
            if (OnImportResourceCount == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportResourceCount(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportResourceCount : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ResourceCount> Records;

            public ImportResourceCount(System.Collections.Generic.List<ResourceCount> Records)
            {
                this.Records = Records;
            }

            public ImportResourceCount()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_resource_count";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportResourceCountFlags;
        public void ImportResourceCount(CallReducerFlags flags) => ImportResourceCountFlags = flags;
    }
}
