// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ImportClaimLocalStateHandler(ReducerEventContext ctx, System.Collections.Generic.List<ClaimLocalState> records);
        public event ImportClaimLocalStateHandler? OnImportClaimLocalState;

        public void ImportClaimLocalState(System.Collections.Generic.List<ClaimLocalState> records)
        {
            conn.InternalCallReducer(new Reducer.ImportClaimLocalState(records), this.SetCallReducerFlags.ImportClaimLocalStateFlags);
        }

        public bool InvokeImportClaimLocalState(ReducerEventContext ctx, Reducer.ImportClaimLocalState args)
        {
            if (OnImportClaimLocalState == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnImportClaimLocalState(
                ctx,
                args.Records
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ImportClaimLocalState : Reducer, IReducerArgs
        {
            [DataMember(Name = "records")]
            public System.Collections.Generic.List<ClaimLocalState> Records;

            public ImportClaimLocalState(System.Collections.Generic.List<ClaimLocalState> Records)
            {
                this.Records = Records;
            }

            public ImportClaimLocalState()
            {
                this.Records = new();
            }

            string IReducerArgs.ReducerName => "import_claim_local_state";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ImportClaimLocalStateFlags;
        public void ImportClaimLocalState(CallReducerFlags flags) => ImportClaimLocalStateFlags = flags;
    }
}
