// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void PlayerTeleportHomeHandler(ReducerEventContext ctx, PlayerTeleportHomeRequest request);
        public event PlayerTeleportHomeHandler? OnPlayerTeleportHome;

        public void PlayerTeleportHome(PlayerTeleportHomeRequest request)
        {
            conn.InternalCallReducer(new Reducer.PlayerTeleportHome(request), this.SetCallReducerFlags.PlayerTeleportHomeFlags);
        }

        public bool InvokePlayerTeleportHome(ReducerEventContext ctx, Reducer.PlayerTeleportHome args)
        {
            if (OnPlayerTeleportHome == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnPlayerTeleportHome(
                ctx,
                args.Request
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class PlayerTeleportHome : Reducer, IReducerArgs
        {
            [DataMember(Name = "_request")]
            public PlayerTeleportHomeRequest Request;

            public PlayerTeleportHome(PlayerTeleportHomeRequest Request)
            {
                this.Request = Request;
            }

            public PlayerTeleportHome()
            {
                this.Request = new();
            }

            string IReducerArgs.ReducerName => "player_teleport_home";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags PlayerTeleportHomeFlags;
        public void PlayerTeleportHome(CallReducerFlags flags) => PlayerTeleportHomeFlags = flags;
    }
}
