// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void ResourcesRegenHandler(ReducerEventContext ctx, ResourcesRegenLoopTimer timer);
        public event ResourcesRegenHandler? OnResourcesRegen;

        public void ResourcesRegen(ResourcesRegenLoopTimer timer)
        {
            conn.InternalCallReducer(new Reducer.ResourcesRegen(timer), this.SetCallReducerFlags.ResourcesRegenFlags);
        }

        public bool InvokeResourcesRegen(ReducerEventContext ctx, Reducer.ResourcesRegen args)
        {
            if (OnResourcesRegen == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnResourcesRegen(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ResourcesRegen : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public ResourcesRegenLoopTimer Timer;

            public ResourcesRegen(ResourcesRegenLoopTimer Timer)
            {
                this.Timer = Timer;
            }

            public ResourcesRegen()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "resources_regen";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags ResourcesRegenFlags;
        public void ResourcesRegen(CallReducerFlags flags) => ResourcesRegenFlags = flags;
    }
}
