// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RespawnResourceInChunkHandler(ReducerEventContext ctx, RespawnResourceInChunkTimer timer);
        public event RespawnResourceInChunkHandler? OnRespawnResourceInChunk;

        public void RespawnResourceInChunk(RespawnResourceInChunkTimer timer)
        {
            conn.InternalCallReducer(new Reducer.RespawnResourceInChunk(timer), this.SetCallReducerFlags.RespawnResourceInChunkFlags);
        }

        public bool InvokeRespawnResourceInChunk(ReducerEventContext ctx, Reducer.RespawnResourceInChunk args)
        {
            if (OnRespawnResourceInChunk == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnRespawnResourceInChunk(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RespawnResourceInChunk : Reducer, IReducerArgs
        {
            [DataMember(Name = "timer")]
            public RespawnResourceInChunkTimer Timer;

            public RespawnResourceInChunk(RespawnResourceInChunkTimer Timer)
            {
                this.Timer = Timer;
            }

            public RespawnResourceInChunk()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "respawn_resource_in_chunk";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RespawnResourceInChunkFlags;
        public void RespawnResourceInChunk(CallReducerFlags flags) => RespawnResourceInChunkFlags = flags;
    }
}
