// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartOnboardingQuestHandler(ReducerEventContext ctx, ushort id);
        public event StartOnboardingQuestHandler? OnStartOnboardingQuest;

        public void StartOnboardingQuest(ushort id)
        {
            conn.InternalCallReducer(new Reducer.StartOnboardingQuest(id), this.SetCallReducerFlags.StartOnboardingQuestFlags);
        }

        public bool InvokeStartOnboardingQuest(ReducerEventContext ctx, Reducer.StartOnboardingQuest args)
        {
            if (OnStartOnboardingQuest == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnStartOnboardingQuest(
                ctx,
                args.Id
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartOnboardingQuest : Reducer, IReducerArgs
        {
            [DataMember(Name = "id")]
            public ushort Id;

            public StartOnboardingQuest(ushort Id)
            {
                this.Id = Id;
            }

            public StartOnboardingQuest()
            {
            }

            string IReducerArgs.ReducerName => "start_onboarding_quest";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StartOnboardingQuestFlags;
        public void StartOnboardingQuest(CallReducerFlags flags) => StartOnboardingQuestFlags = flags;
    }
}
