// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void TradeSessionsAgentLoopHandler(ReducerEventContext ctx, TradeSessionLoopTimer timer);
        public event TradeSessionsAgentLoopHandler? OnTradeSessionsAgentLoop;

        public void TradeSessionsAgentLoop(TradeSessionLoopTimer timer)
        {
            conn.InternalCallReducer(new Reducer.TradeSessionsAgentLoop(timer), this.SetCallReducerFlags.TradeSessionsAgentLoopFlags);
        }

        public bool InvokeTradeSessionsAgentLoop(ReducerEventContext ctx, Reducer.TradeSessionsAgentLoop args)
        {
            if (OnTradeSessionsAgentLoop == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnTradeSessionsAgentLoop(
                ctx,
                args.Timer
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class TradeSessionsAgentLoop : Reducer, IReducerArgs
        {
            [DataMember(Name = "_timer")]
            public TradeSessionLoopTimer Timer;

            public TradeSessionsAgentLoop(TradeSessionLoopTimer Timer)
            {
                this.Timer = Timer;
            }

            public TradeSessionsAgentLoop()
            {
                this.Timer = new();
            }

            string IReducerArgs.ReducerName => "trade_sessions_agent_loop";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags TradeSessionsAgentLoopFlags;
        public void TradeSessionsAgentLoop(CallReducerFlags flags) => TradeSessionsAgentLoopFlags = flags;
    }
}
