// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    public partial record AbilityType : SpacetimeDB.TaggedEnum<(
        U128 _Unsupported,
        int Eat,
        int CombatAction,
        SpacetimeDB.Unit AutoAttack,
        int Custom,
        int Prospecting,
        int Equip,
        int DeployableDeploy,
        int AddToToolbelt,
        int DeployableToggle,
        int Emote
    )>;
}
