// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AbilityState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "owner_entity_id")]
        public ulong OwnerEntityId;
        [DataMember(Name = "ability")]
        public AbilityType Ability;
        [DataMember(Name = "cooldown")]
        public ActionCooldown Cooldown;

        public AbilityState(
            ulong EntityId,
            ulong OwnerEntityId,
            AbilityType Ability,
            ActionCooldown Cooldown
        )
        {
            this.EntityId = EntityId;
            this.OwnerEntityId = OwnerEntityId;
            this.Ability = Ability;
            this.Cooldown = Cooldown;
        }

        public AbilityState()
        {
            this.Ability = null!;
            this.Cooldown = new();
        }
    }
}
