// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ActionLogDataSpaceAllocator
    {
        [DataMember(Name = "item1")]
        public ItemStack Item1;
        [DataMember(Name = "item2")]
        public ItemStack Item2;
        [DataMember(Name = "val1")]
        public ulong Val1;
        [DataMember(Name = "val2")]
        public ulong Val2;

        public ActionLogDataSpaceAllocator(
            ItemStack Item1,
            ItemStack Item2,
            ulong Val1,
            ulong Val2
        )
        {
            this.Item1 = Item1;
            this.Item2 = Item2;
            this.Val1 = Val1;
            this.Val2 = Val2;
        }

        public ActionLogDataSpaceAllocator()
        {
            this.Item1 = new();
            this.Item2 = new();
        }
    }
}
