// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class AttackOutcomeState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "last_attacked_timestamp")]
        public ulong LastAttackedTimestamp;
        [DataMember(Name = "damage")]
        public int Damage;
        [DataMember(Name = "crit_result")]
        public bool CritResult;
        [DataMember(Name = "dodge_result")]
        public bool DodgeResult;

        public AttackOutcomeState(
            ulong EntityId,
            ulong LastAttackedTimestamp,
            int Damage,
            bool CritResult,
            bool DodgeResult
        )
        {
            this.EntityId = EntityId;
            this.LastAttackedTimestamp = LastAttackedTimestamp;
            this.Damage = Damage;
            this.CritResult = CritResult;
            this.DodgeResult = DodgeResult;
        }

        public AttackOutcomeState()
        {
        }
    }
}
