// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BuildingDesc
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "functions")]
        public System.Collections.Generic.List<BuildingFunction> Functions;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "rested_buff_duration")]
        public int RestedBuffDuration;
        [DataMember(Name = "light_radius")]
        public int LightRadius;
        [DataMember(Name = "model_asset_name")]
        public string ModelAssetName;
        [DataMember(Name = "icon_asset_name")]
        public string IconAssetName;
        [DataMember(Name = "unenterable")]
        public bool Unenterable;
        [DataMember(Name = "wilderness")]
        public bool Wilderness;
        [DataMember(Name = "footprint")]
        public System.Collections.Generic.List<FootprintTile> Footprint;
        [DataMember(Name = "max_health")]
        public int MaxHealth;
        [DataMember(Name = "ignore_damage")]
        public bool IgnoreDamage;
        [DataMember(Name = "defense_level")]
        public int DefenseLevel;
        [DataMember(Name = "decay")]
        public float Decay;
        [DataMember(Name = "maintenance")]
        public float Maintenance;
        [DataMember(Name = "build_permission")]
        public BuildingInteractionLevel BuildPermission;
        [DataMember(Name = "interact_permission")]
        public BuildingInteractionLevel InteractPermission;
        [DataMember(Name = "has_action")]
        public bool HasAction;
        [DataMember(Name = "show_in_compendium")]
        public bool ShowInCompendium;
        [DataMember(Name = "is_ruins")]
        public bool IsRuins;
        [DataMember(Name = "not_deconstructible")]
        public bool NotDeconstructible;
        [DataMember(Name = "destroy_on_unclaim")]
        public bool DestroyOnUnclaim;

        public BuildingDesc(
            int Id,
            System.Collections.Generic.List<BuildingFunction> Functions,
            string Name,
            string Description,
            int RestedBuffDuration,
            int LightRadius,
            string ModelAssetName,
            string IconAssetName,
            bool Unenterable,
            bool Wilderness,
            System.Collections.Generic.List<FootprintTile> Footprint,
            int MaxHealth,
            bool IgnoreDamage,
            int DefenseLevel,
            float Decay,
            float Maintenance,
            BuildingInteractionLevel BuildPermission,
            BuildingInteractionLevel InteractPermission,
            bool HasAction,
            bool ShowInCompendium,
            bool IsRuins,
            bool NotDeconstructible,
            bool DestroyOnUnclaim
        )
        {
            this.Id = Id;
            this.Functions = Functions;
            this.Name = Name;
            this.Description = Description;
            this.RestedBuffDuration = RestedBuffDuration;
            this.LightRadius = LightRadius;
            this.ModelAssetName = ModelAssetName;
            this.IconAssetName = IconAssetName;
            this.Unenterable = Unenterable;
            this.Wilderness = Wilderness;
            this.Footprint = Footprint;
            this.MaxHealth = MaxHealth;
            this.IgnoreDamage = IgnoreDamage;
            this.DefenseLevel = DefenseLevel;
            this.Decay = Decay;
            this.Maintenance = Maintenance;
            this.BuildPermission = BuildPermission;
            this.InteractPermission = InteractPermission;
            this.HasAction = HasAction;
            this.ShowInCompendium = ShowInCompendium;
            this.IsRuins = IsRuins;
            this.NotDeconstructible = NotDeconstructible;
            this.DestroyOnUnclaim = DestroyOnUnclaim;
        }

        public BuildingDesc()
        {
            this.Functions = new();
            this.Name = "";
            this.Description = "";
            this.ModelAssetName = "";
            this.IconAssetName = "";
            this.Footprint = new();
        }
    }
}
