// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BuildingSetSignTextRequest
    {
        [DataMember(Name = "building_entity_id")]
        public ulong BuildingEntityId;
        [DataMember(Name = "text")]
        public string Text;

        public BuildingSetSignTextRequest(
            ulong BuildingEntityId,
            string Text
        )
        {
            this.BuildingEntityId = BuildingEntityId;
            this.Text = Text;
        }

        public BuildingSetSignTextRequest()
        {
            this.Text = "";
        }
    }
}
