// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class BuildingPortalDesc
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "building_id")]
        public int BuildingId;
        [DataMember(Name = "allow_deployables")]
        public bool AllowDeployables;
        [DataMember(Name = "enemy_lock")]
        public bool EnemyLock;
        [DataMember(Name = "pos_x")]
        public int PosX;
        [DataMember(Name = "pos_z")]
        public int PosZ;

        public BuildingPortalDesc(
            int Id,
            string Name,
            int BuildingId,
            bool AllowDeployables,
            bool EnemyLock,
            int PosX,
            int PosZ
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.BuildingId = BuildingId;
            this.AllowDeployables = AllowDeployables;
            this.EnemyLock = EnemyLock;
            this.PosX = PosX;
            this.PosZ = PosZ;
        }

        public BuildingPortalDesc()
        {
            this.Name = "";
        }
    }
}
