// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CargoDesc
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "volume")]
        public int Volume;
        [DataMember(Name = "secondary_knowledge_id")]
        public int SecondaryKnowledgeId;
        [DataMember(Name = "model_asset_name")]
        public string ModelAssetName;
        [DataMember(Name = "icon_asset_name")]
        public string IconAssetName;
        [DataMember(Name = "carried_model_asset_name")]
        public string CarriedModelAssetName;
        [DataMember(Name = "pick_up_animation_start")]
        public string PickUpAnimationStart;
        [DataMember(Name = "pick_up_animation_end")]
        public string PickUpAnimationEnd;
        [DataMember(Name = "drop_animation_start")]
        public string DropAnimationStart;
        [DataMember(Name = "drop_animation_end")]
        public string DropAnimationEnd;
        [DataMember(Name = "pick_up_time")]
        public float PickUpTime;
        [DataMember(Name = "place_time")]
        public float PlaceTime;
        [DataMember(Name = "animator_state")]
        public string AnimatorState;
        [DataMember(Name = "movement_modifier")]
        public float MovementModifier;
        [DataMember(Name = "blocks_path")]
        public bool BlocksPath;
        [DataMember(Name = "on_destroy_yield_cargos")]
        public System.Collections.Generic.List<int> OnDestroyYieldCargos;
        [DataMember(Name = "despawn_time")]
        public float DespawnTime;
        [DataMember(Name = "tier")]
        public int Tier;
        [DataMember(Name = "tag")]
        public string Tag;
        [DataMember(Name = "rarity")]
        public Rarity Rarity;
        [DataMember(Name = "not_pickupable")]
        public bool NotPickupable;

        public CargoDesc(
            int Id,
            string Name,
            string Description,
            int Volume,
            int SecondaryKnowledgeId,
            string ModelAssetName,
            string IconAssetName,
            string CarriedModelAssetName,
            string PickUpAnimationStart,
            string PickUpAnimationEnd,
            string DropAnimationStart,
            string DropAnimationEnd,
            float PickUpTime,
            float PlaceTime,
            string AnimatorState,
            float MovementModifier,
            bool BlocksPath,
            System.Collections.Generic.List<int> OnDestroyYieldCargos,
            float DespawnTime,
            int Tier,
            string Tag,
            Rarity Rarity,
            bool NotPickupable
        )
        {
            this.Id = Id;
            this.Name = Name;
            this.Description = Description;
            this.Volume = Volume;
            this.SecondaryKnowledgeId = SecondaryKnowledgeId;
            this.ModelAssetName = ModelAssetName;
            this.IconAssetName = IconAssetName;
            this.CarriedModelAssetName = CarriedModelAssetName;
            this.PickUpAnimationStart = PickUpAnimationStart;
            this.PickUpAnimationEnd = PickUpAnimationEnd;
            this.DropAnimationStart = DropAnimationStart;
            this.DropAnimationEnd = DropAnimationEnd;
            this.PickUpTime = PickUpTime;
            this.PlaceTime = PlaceTime;
            this.AnimatorState = AnimatorState;
            this.MovementModifier = MovementModifier;
            this.BlocksPath = BlocksPath;
            this.OnDestroyYieldCargos = OnDestroyYieldCargos;
            this.DespawnTime = DespawnTime;
            this.Tier = Tier;
            this.Tag = Tag;
            this.Rarity = Rarity;
            this.NotPickupable = NotPickupable;
        }

        public CargoDesc()
        {
            this.Name = "";
            this.Description = "";
            this.ModelAssetName = "";
            this.IconAssetName = "";
            this.CarriedModelAssetName = "";
            this.PickUpAnimationStart = "";
            this.PickUpAnimationEnd = "";
            this.DropAnimationStart = "";
            this.DropAnimationEnd = "";
            this.AnimatorState = "";
            this.OnDestroyYieldCargos = new();
            this.Tag = "";
        }
    }
}
