// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    public enum CollectibleType
    {
        Default,
        Hair,
        Mask,
        MaskPattern,
        HairColor,
        Nameplate,
        BodyColor,
        Emblem,
        ClothesHead,
        ClothesBelt,
        ClothesTorso,
        ClothesArms,
        ClothesLegs,
        ClothesFeet,
        Deployable,
        Title,
        Crown,
        Pet,
        ClothesCape,
        PremiumItem,
    }
}
