// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class CombatImmunityState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "immunity_end_timestamp")]
        public SpacetimeDB.Timestamp ImmunityEndTimestamp;
        [DataMember(Name = "crumb_trail_entity_id")]
        public ulong? CrumbTrailEntityId;

        public CombatImmunityState(
            ulong EntityId,
            SpacetimeDB.Timestamp ImmunityEndTimestamp,
            ulong? CrumbTrailEntityId
        )
        {
            this.EntityId = EntityId;
            this.ImmunityEndTimestamp = ImmunityEndTimestamp;
            this.CrumbTrailEntityId = CrumbTrailEntityId;
        }

        public CombatImmunityState()
        {
        }
    }
}
