// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ElevatorDesc
    {
        [DataMember(Name = "building_id")]
        public int BuildingId;
        [DataMember(Name = "max_cliff_height")]
        public uint MaxCliffHeight;
        [DataMember(Name = "speed")]
        public float Speed;
        [DataMember(Name = "usable_with_deployable")]
        public bool UsableWithDeployable;
        [DataMember(Name = "top_platform_address")]
        public string TopPlatformAddress;
        [DataMember(Name = "basket_address")]
        public string BasketAddress;
        [DataMember(Name = "bottom_platform_address")]
        public string BottomPlatformAddress;

        public ElevatorDesc(
            int BuildingId,
            uint MaxCliffHeight,
            float Speed,
            bool UsableWithDeployable,
            string TopPlatformAddress,
            string BasketAddress,
            string BottomPlatformAddress
        )
        {
            this.BuildingId = BuildingId;
            this.MaxCliffHeight = MaxCliffHeight;
            this.Speed = Speed;
            this.UsableWithDeployable = UsableWithDeployable;
            this.TopPlatformAddress = TopPlatformAddress;
            this.BasketAddress = BasketAddress;
            this.BottomPlatformAddress = BottomPlatformAddress;
        }

        public ElevatorDesc()
        {
            this.TopPlatformAddress = "";
            this.BasketAddress = "";
            this.BottomPlatformAddress = "";
        }
    }
}
