// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EmpireCreateBuildingMsg
    {
        [DataMember(Name = "location")]
        public OffsetCoordinatesSmallMessage Location;
        [DataMember(Name = "player_entity_id")]
        public ulong PlayerEntityId;
        [DataMember(Name = "building_entity_id")]
        public ulong BuildingEntityId;
        [DataMember(Name = "building_desc_id")]
        public int BuildingDescId;
        [DataMember(Name = "construction_recipe_id")]
        public int? ConstructionRecipeId;

        public EmpireCreateBuildingMsg(
            OffsetCoordinatesSmallMessage Location,
            ulong PlayerEntityId,
            ulong BuildingEntityId,
            int BuildingDescId,
            int? ConstructionRecipeId
        )
        {
            this.Location = Location;
            this.PlayerEntityId = PlayerEntityId;
            this.BuildingEntityId = BuildingEntityId;
            this.BuildingDescId = BuildingDescId;
            this.ConstructionRecipeId = ConstructionRecipeId;
        }

        public EmpireCreateBuildingMsg()
        {
            this.Location = new();
        }
    }
}
