// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EmpireRankDesc
    {
        [DataMember(Name = "rank")]
        public int Rank;
        [DataMember(Name = "title")]
        public string Title;
        [DataMember(Name = "max_count")]
        public int? MaxCount;
        [DataMember(Name = "permissions")]
        public System.Collections.Generic.List<bool> Permissions;

        public EmpireRankDesc(
            int Rank,
            string Title,
            int? MaxCount,
            System.Collections.Generic.List<bool> Permissions
        )
        {
            this.Rank = Rank;
            this.Title = Title;
            this.MaxCount = MaxCount;
            this.Permissions = Permissions;
        }

        public EmpireRankDesc()
        {
            this.Title = "";
            this.Permissions = new();
        }
    }
}
