// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EmpireTerritoryDesc
    {
        [DataMember(Name = "id")]
        public byte Id;
        [DataMember(Name = "chunks")]
        public ushort Chunks;
        [DataMember(Name = "ranks")]
        public System.Collections.Generic.List<byte> Ranks;
        [DataMember(Name = "crown_collectible_id")]
        public int CrownCollectibleId;

        public EmpireTerritoryDesc(
            byte Id,
            ushort Chunks,
            System.Collections.Generic.List<byte> Ranks,
            int CrownCollectibleId
        )
        {
            this.Id = Id;
            this.Chunks = Chunks;
            this.Ranks = Ranks;
            this.CrownCollectibleId = CrownCollectibleId;
        }

        public EmpireTerritoryDesc()
        {
            this.Ranks = new();
        }
    }
}
