// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class EnemySetHealthRequest
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "health")]
        public int Health;

        public EnemySetHealthRequest(
            ulong EntityId,
            int Health
        )
        {
            this.EntityId = EntityId;
            this.Health = Health;
        }

        public EnemySetHealthRequest()
        {
        }
    }
}
