// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class GateDesc
    {
        [DataMember(Name = "building_id")]
        public int BuildingId;
        [DataMember(Name = "small_post_asset_name")]
        public string SmallPostAssetName;

        public GateDesc(
            int BuildingId,
            string SmallPostAssetName
        )
        {
            this.BuildingId = BuildingId;
            this.SmallPostAssetName = SmallPostAssetName;
        }

        public GateDesc()
        {
            this.SmallPostAssetName = "";
        }
    }
}
