// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InterModuleResponseMessageCounter
    {
        [DataMember(Name = "dst_module_id")]
        public byte DstModuleId;
        [DataMember(Name = "last_processed_message_id")]
        public ulong LastProcessedMessageId;

        public InterModuleResponseMessageCounter(
            byte DstModuleId,
            ulong LastProcessedMessageId
        )
        {
            this.DstModuleId = DstModuleId;
            this.LastProcessedMessageId = LastProcessedMessageId;
        }

        public InterModuleResponseMessageCounter()
        {
        }
    }
}
