// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InterModuleMessageV4
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "to")]
        public byte To;
        [DataMember(Name = "contents")]
        public MessageContentsV4 Contents;

        public InterModuleMessageV4(
            ulong Id,
            byte To,
            MessageContentsV4 Contents
        )
        {
            this.Id = Id;
            this.To = To;
            this.Contents = Contents;
        }

        public InterModuleMessageV4()
        {
            this.Contents = null!;
        }
    }
}
