// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class InterModuleMessage
    {
        [DataMember(Name = "id")]
        public ulong Id;
        [DataMember(Name = "to")]
        public byte To;
        [DataMember(Name = "contents")]
        public MessageContents Contents;

        public InterModuleMessage(
            ulong Id,
            byte To,
            MessageContents Contents
        )
        {
            this.Id = Id;
            this.To = To;
            this.Contents = Contents;
        }

        public InterModuleMessage()
        {
            this.Contents = null!;
        }
    }
}
