// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ItemListPossibility
    {
        [DataMember(Name = "probability")]
        public float Probability;
        [DataMember(Name = "items")]
        public System.Collections.Generic.List<ItemStack> Items;

        public ItemListPossibility(
            float Probability,
            System.Collections.Generic.List<ItemStack> Items
        )
        {
            this.Probability = Probability;
            this.Items = Items;
        }

        public ItemListPossibility()
        {
            this.Items = new();
        }
    }
}
