// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MobileEntityState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "chunk_index")]
        public ulong ChunkIndex;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;
        [DataMember(Name = "location_x")]
        public int LocationX;
        [DataMember(Name = "location_z")]
        public int LocationZ;
        [DataMember(Name = "destination_x")]
        public int DestinationX;
        [DataMember(Name = "destination_z")]
        public int DestinationZ;
        [DataMember(Name = "dimension")]
        public uint Dimension;
        [DataMember(Name = "is_walking")]
        public bool IsWalking;
        [DataMember(Name = "_pad1")]
        public byte Pad1;
        [DataMember(Name = "_pad2")]
        public byte Pad2;
        [DataMember(Name = "_pad3")]
        public byte Pad3;

        public MobileEntityState(
            ulong EntityId,
            ulong ChunkIndex,
            ulong Timestamp,
            int LocationX,
            int LocationZ,
            int DestinationX,
            int DestinationZ,
            uint Dimension,
            bool IsWalking,
            byte Pad1,
            byte Pad2,
            byte Pad3
        )
        {
            this.EntityId = EntityId;
            this.ChunkIndex = ChunkIndex;
            this.Timestamp = Timestamp;
            this.LocationX = LocationX;
            this.LocationZ = LocationZ;
            this.DestinationX = DestinationX;
            this.DestinationZ = DestinationZ;
            this.Dimension = Dimension;
            this.IsWalking = IsWalking;
            this.Pad1 = Pad1;
            this.Pad2 = Pad2;
            this.Pad3 = Pad3;
        }

        public MobileEntityState()
        {
        }
    }
}
