// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerCompleteTaskRequest
    {
        [DataMember(Name = "task_entity_id")]
        public ulong TaskEntityId;
        [DataMember(Name = "npc_entity_id")]
        public ulong NpcEntityId;

        public PlayerCompleteTaskRequest(
            ulong TaskEntityId,
            ulong NpcEntityId
        )
        {
            this.TaskEntityId = TaskEntityId;
            this.NpcEntityId = NpcEntityId;
        }

        public PlayerCompleteTaskRequest()
        {
        }
    }
}
