// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerVoteConcludeTimer
    {
        [DataMember(Name = "scheduled_id")]
        public ulong ScheduledId;
        [DataMember(Name = "scheduled_at")]
        public SpacetimeDB.ScheduleAt ScheduledAt;
        [DataMember(Name = "vote_entity_id")]
        public ulong VoteEntityId;

        public PlayerVoteConcludeTimer(
            ulong ScheduledId,
            SpacetimeDB.ScheduleAt ScheduledAt,
            ulong VoteEntityId
        )
        {
            this.ScheduledId = ScheduledId;
            this.ScheduledAt = ScheduledAt;
            this.VoteEntityId = VoteEntityId;
        }

        public PlayerVoteConcludeTimer()
        {
            this.ScheduledAt = null!;
        }
    }
}
