// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerItemStackMoveRequest
    {
        [DataMember(Name = "from_pocket")]
        public PocketKey FromPocket;
        [DataMember(Name = "to_pocket")]
        public PocketKey ToPocket;
        [DataMember(Name = "quantity")]
        public int Quantity;

        public PlayerItemStackMoveRequest(
            PocketKey FromPocket,
            PocketKey ToPocket,
            int Quantity
        )
        {
            this.FromPocket = FromPocket;
            this.ToPocket = ToPocket;
            this.Quantity = Quantity;
        }

        public PlayerItemStackMoveRequest()
        {
            this.FromPocket = new();
            this.ToPocket = new();
        }
    }
}
