// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerTerraformSetFinalTargetRequest
    {
        [DataMember(Name = "coordinates")]
        public OffsetCoordinatesLargeMessage Coordinates;
        [DataMember(Name = "final_height_target")]
        public short FinalHeightTarget;

        public PlayerTerraformSetFinalTargetRequest(
            OffsetCoordinatesLargeMessage Coordinates,
            short FinalHeightTarget
        )
        {
            this.Coordinates = Coordinates;
            this.FinalHeightTarget = FinalHeightTarget;
        }

        public PlayerTerraformSetFinalTargetRequest()
        {
            this.Coordinates = new();
        }
    }
}
