// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerBarterStallOrderCreateRequest
    {
        [DataMember(Name = "shop_entity_id")]
        public ulong ShopEntityId;
        [DataMember(Name = "remaining_stock")]
        public int RemainingStock;
        [DataMember(Name = "offer_items")]
        public ItemStack? OfferItems;
        [DataMember(Name = "offer_cargo_id")]
        public int OfferCargoId;
        [DataMember(Name = "required_items")]
        public System.Collections.Generic.List<ItemStack> RequiredItems;
        [DataMember(Name = "required_cargos")]
        public System.Collections.Generic.List<int> RequiredCargos;

        public PlayerBarterStallOrderCreateRequest(
            ulong ShopEntityId,
            int RemainingStock,
            ItemStack? OfferItems,
            int OfferCargoId,
            System.Collections.Generic.List<ItemStack> RequiredItems,
            System.Collections.Generic.List<int> RequiredCargos
        )
        {
            this.ShopEntityId = ShopEntityId;
            this.RemainingStock = RemainingStock;
            this.OfferItems = OfferItems;
            this.OfferCargoId = OfferCargoId;
            this.RequiredItems = RequiredItems;
            this.RequiredCargos = RequiredCargos;
        }

        public PlayerBarterStallOrderCreateRequest()
        {
            this.RequiredItems = new();
            this.RequiredCargos = new();
        }
    }
}
