// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerVoteAnswerRequest
    {
        [DataMember(Name = "vote_entity_id")]
        public ulong VoteEntityId;
        [DataMember(Name = "accept")]
        public bool Accept;

        public PlayerVoteAnswerRequest(
            ulong VoteEntityId,
            bool Accept
        )
        {
            this.VoteEntityId = VoteEntityId;
            this.Accept = Accept;
        }

        public PlayerVoteAnswerRequest()
        {
        }
    }
}
