// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerCraftContinueRequest
    {
        [DataMember(Name = "progressive_action_entity_id")]
        public ulong ProgressiveActionEntityId;
        [DataMember(Name = "timestamp")]
        public ulong Timestamp;

        public PlayerCraftContinueRequest(
            ulong ProgressiveActionEntityId,
            ulong Timestamp
        )
        {
            this.ProgressiveActionEntityId = ProgressiveActionEntityId;
            this.Timestamp = Timestamp;
        }

        public PlayerCraftContinueRequest()
        {
        }
    }
}
