// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerPrefsState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "default_deployable_collectible_id")]
        public int DefaultDeployableCollectibleId;

        public PlayerPrefsState(
            ulong EntityId,
            int DefaultDeployableCollectibleId
        )
        {
            this.EntityId = EntityId;
            this.DefaultDeployableCollectibleId = DefaultDeployableCollectibleId;
        }

        public PlayerPrefsState()
        {
        }
    }
}
