// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerClaimDepositToTreasuryRequest
    {
        [DataMember(Name = "claim_entity_id")]
        public ulong ClaimEntityId;
        [DataMember(Name = "amount")]
        public uint Amount;

        public PlayerClaimDepositToTreasuryRequest(
            ulong ClaimEntityId,
            uint Amount
        )
        {
            this.ClaimEntityId = ClaimEntityId;
            this.Amount = Amount;
        }

        public PlayerClaimDepositToTreasuryRequest()
        {
        }
    }
}
