// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PlayerReportState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "reporter_entity_id")]
        public ulong ReporterEntityId;
        [DataMember(Name = "reported_player_entity_id")]
        public ulong ReportedPlayerEntityId;
        [DataMember(Name = "reported_player_username")]
        public string ReportedPlayerUsername;
        [DataMember(Name = "report_type")]
        public string ReportType;
        [DataMember(Name = "report_message")]
        public string ReportMessage;
        [DataMember(Name = "reported_chat_message")]
        public ChatMessageState? ReportedChatMessage;
        [DataMember(Name = "chat_channel_context")]
        public System.Collections.Generic.List<ChatMessageState>? ChatChannelContext;
        [DataMember(Name = "chat_user_context")]
        public System.Collections.Generic.List<ChatMessageState>? ChatUserContext;
        [DataMember(Name = "actioned")]
        public bool Actioned;

        public PlayerReportState(
            ulong EntityId,
            ulong ReporterEntityId,
            ulong ReportedPlayerEntityId,
            string ReportedPlayerUsername,
            string ReportType,
            string ReportMessage,
            ChatMessageState? ReportedChatMessage,
            System.Collections.Generic.List<ChatMessageState>? ChatChannelContext,
            System.Collections.Generic.List<ChatMessageState>? ChatUserContext,
            bool Actioned
        )
        {
            this.EntityId = EntityId;
            this.ReporterEntityId = ReporterEntityId;
            this.ReportedPlayerEntityId = ReportedPlayerEntityId;
            this.ReportedPlayerUsername = ReportedPlayerUsername;
            this.ReportType = ReportType;
            this.ReportMessage = ReportMessage;
            this.ReportedChatMessage = ReportedChatMessage;
            this.ChatChannelContext = ChatChannelContext;
            this.ChatUserContext = ChatUserContext;
            this.Actioned = Actioned;
        }

        public PlayerReportState()
        {
            this.ReportedPlayerUsername = "";
            this.ReportType = "";
            this.ReportMessage = "";
        }
    }
}
