// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class PreviousPlayerUsernameState
    {
        [DataMember(Name = "identity")]
        public SpacetimeDB.Identity Identity;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "lower_case_name")]
        public string LowerCaseName;

        public PreviousPlayerUsernameState(
            SpacetimeDB.Identity Identity,
            string Name,
            string LowerCaseName
        )
        {
            this.Identity = Identity;
            this.Name = Name;
            this.LowerCaseName = LowerCaseName;
        }

        public PreviousPlayerUsernameState()
        {
            this.Name = "";
            this.LowerCaseName = "";
        }
    }
}
