// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ProspectingParticipant
    {
        [DataMember(Name = "player_name")]
        public string PlayerName;
        [DataMember(Name = "node")]
        public int Node;

        public ProspectingParticipant(
            string PlayerName,
            int Node
        )
        {
            this.PlayerName = PlayerName;
            this.Node = Node;
        }

        public ProspectingParticipant()
        {
            this.PlayerName = "";
        }
    }
}
