// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RentSetDailyRateRequest
    {
        [DataMember(Name = "rent_entity_id")]
        public ulong RentEntityId;
        [DataMember(Name = "daily_rate")]
        public uint DailyRate;

        public RentSetDailyRateRequest(
            ulong RentEntityId,
            uint DailyRate
        )
        {
            this.RentEntityId = RentEntityId;
            this.DailyRate = DailyRate;
        }

        public RentSetDailyRateRequest()
        {
        }
    }
}
