// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RentDepositCoinsRequest
    {
        [DataMember(Name = "rent_entity_id")]
        public ulong RentEntityId;
        [DataMember(Name = "amount")]
        public uint Amount;

        public RentDepositCoinsRequest(
            ulong RentEntityId,
            uint Amount
        )
        {
            this.RentEntityId = RentEntityId;
            this.Amount = Amount;
        }

        public RentDepositCoinsRequest()
        {
        }
    }
}
