// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ResourcePlacement
    {
        [DataMember(Name = "coordinates")]
        public OffsetCoordinatesSmallMessage Coordinates;
        [DataMember(Name = "facing_direction")]
        public int FacingDirection;

        public ResourcePlacement(
            OffsetCoordinatesSmallMessage Coordinates,
            int FacingDirection
        )
        {
            this.Coordinates = Coordinates;
            this.FacingDirection = FacingDirection;
        }

        public ResourcePlacement()
        {
            this.Coordinates = new();
        }
    }
}
