// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class RestoreSkillsMsg
    {
        [DataMember(Name = "player_entity_id")]
        public ulong PlayerEntityId;
        [DataMember(Name = "experience_stacks")]
        public System.Collections.Generic.List<ExperienceStack> ExperienceStacks;

        public RestoreSkillsMsg(
            ulong PlayerEntityId,
            System.Collections.Generic.List<ExperienceStack> ExperienceStacks
        )
        {
            this.PlayerEntityId = PlayerEntityId;
            this.ExperienceStacks = ExperienceStacks;
        }

        public RestoreSkillsMsg()
        {
            this.ExperienceStacks = new();
        }
    }
}
