// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class SkillDesc
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "skill_type")]
        public int SkillType;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "description")]
        public string Description;
        [DataMember(Name = "icon_asset_name")]
        public string IconAssetName;
        [DataMember(Name = "title")]
        public string Title;
        [DataMember(Name = "skill_category")]
        public SkillCategory SkillCategory;
        [DataMember(Name = "max_level")]
        public int MaxLevel;

        public SkillDesc(
            int Id,
            int SkillType,
            string Name,
            string Description,
            string IconAssetName,
            string Title,
            SkillCategory SkillCategory,
            int MaxLevel
        )
        {
            this.Id = Id;
            this.SkillType = SkillType;
            this.Name = Name;
            this.Description = Description;
            this.IconAssetName = IconAssetName;
            this.Title = Title;
            this.SkillCategory = SkillCategory;
            this.MaxLevel = MaxLevel;
        }

        public SkillDesc()
        {
            this.Name = "";
            this.Description = "";
            this.IconAssetName = "";
            this.Title = "";
        }
    }
}
