// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ToolbarState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "owner_entity_id")]
        public ulong OwnerEntityId;
        [DataMember(Name = "index")]
        public byte Index;
        [DataMember(Name = "actions")]
        public System.Collections.Generic.List<ulong> Actions;

        public ToolbarState(
            ulong EntityId,
            ulong OwnerEntityId,
            byte Index,
            System.Collections.Generic.List<ulong> Actions
        )
        {
            this.EntityId = EntityId;
            this.OwnerEntityId = OwnerEntityId;
            this.Index = Index;
            this.Actions = Actions;
        }

        public ToolbarState()
        {
            this.Actions = new();
        }
    }
}
