// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TradeSessionState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "status")]
        public TradeSessionStatus Status;
        [DataMember(Name = "initiator_entity_id")]
        public ulong InitiatorEntityId;
        [DataMember(Name = "acceptor_entity_id")]
        public ulong AcceptorEntityId;
        [DataMember(Name = "initiator_offer")]
        public System.Collections.Generic.List<TradePocket> InitiatorOffer;
        [DataMember(Name = "acceptor_offer")]
        public System.Collections.Generic.List<TradePocket> AcceptorOffer;
        [DataMember(Name = "updated_at")]
        public SpacetimeDB.Timestamp UpdatedAt;
        [DataMember(Name = "resolution_message")]
        public string ResolutionMessage;

        public TradeSessionState(
            ulong EntityId,
            TradeSessionStatus Status,
            ulong InitiatorEntityId,
            ulong AcceptorEntityId,
            System.Collections.Generic.List<TradePocket> InitiatorOffer,
            System.Collections.Generic.List<TradePocket> AcceptorOffer,
            SpacetimeDB.Timestamp UpdatedAt,
            string ResolutionMessage
        )
        {
            this.EntityId = EntityId;
            this.Status = Status;
            this.InitiatorEntityId = InitiatorEntityId;
            this.AcceptorEntityId = AcceptorEntityId;
            this.InitiatorOffer = InitiatorOffer;
            this.AcceptorOffer = AcceptorOffer;
            this.UpdatedAt = UpdatedAt;
            this.ResolutionMessage = ResolutionMessage;
        }

        public TradeSessionState()
        {
            this.InitiatorOffer = new();
            this.AcceptorOffer = new();
            this.ResolutionMessage = "";
        }
    }
}
