// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TravelerTradeOrderDesc
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "starting_stock")]
        public int StartingStock;
        [DataMember(Name = "always_offered")]
        public bool AlwaysOffered;
        [DataMember(Name = "traveler")]
        public NpcType Traveler;
        [DataMember(Name = "offer_items")]
        public System.Collections.Generic.List<ItemStack> OfferItems;
        [DataMember(Name = "offer_cargo_id")]
        public System.Collections.Generic.List<int> OfferCargoId;
        [DataMember(Name = "required_items")]
        public System.Collections.Generic.List<ItemStack> RequiredItems;
        [DataMember(Name = "required_cargo_id")]
        public System.Collections.Generic.List<int> RequiredCargoId;
        [DataMember(Name = "level_requirements")]
        public System.Collections.Generic.List<LevelRequirement> LevelRequirements;
        [DataMember(Name = "achievement_requirements")]
        public System.Collections.Generic.List<int> AchievementRequirements;
        [DataMember(Name = "hide_if_requirements_are_not_met")]
        public bool HideIfRequirementsAreNotMet;
        [DataMember(Name = "required_knowledges")]
        public System.Collections.Generic.List<int> RequiredKnowledges;
        [DataMember(Name = "hide_without_required_knowledge")]
        public bool HideWithoutRequiredKnowledge;
        [DataMember(Name = "blocking_knowledges")]
        public System.Collections.Generic.List<int> BlockingKnowledges;
        [DataMember(Name = "hide_with_blocking_knowledges")]
        public bool HideWithBlockingKnowledges;

        public TravelerTradeOrderDesc(
            int Id,
            int StartingStock,
            bool AlwaysOffered,
            NpcType Traveler,
            System.Collections.Generic.List<ItemStack> OfferItems,
            System.Collections.Generic.List<int> OfferCargoId,
            System.Collections.Generic.List<ItemStack> RequiredItems,
            System.Collections.Generic.List<int> RequiredCargoId,
            System.Collections.Generic.List<LevelRequirement> LevelRequirements,
            System.Collections.Generic.List<int> AchievementRequirements,
            bool HideIfRequirementsAreNotMet,
            System.Collections.Generic.List<int> RequiredKnowledges,
            bool HideWithoutRequiredKnowledge,
            System.Collections.Generic.List<int> BlockingKnowledges,
            bool HideWithBlockingKnowledges
        )
        {
            this.Id = Id;
            this.StartingStock = StartingStock;
            this.AlwaysOffered = AlwaysOffered;
            this.Traveler = Traveler;
            this.OfferItems = OfferItems;
            this.OfferCargoId = OfferCargoId;
            this.RequiredItems = RequiredItems;
            this.RequiredCargoId = RequiredCargoId;
            this.LevelRequirements = LevelRequirements;
            this.AchievementRequirements = AchievementRequirements;
            this.HideIfRequirementsAreNotMet = HideIfRequirementsAreNotMet;
            this.RequiredKnowledges = RequiredKnowledges;
            this.HideWithoutRequiredKnowledge = HideWithoutRequiredKnowledge;
            this.BlockingKnowledges = BlockingKnowledges;
            this.HideWithBlockingKnowledges = HideWithBlockingKnowledges;
        }

        public TravelerTradeOrderDesc()
        {
            this.OfferItems = new();
            this.OfferCargoId = new();
            this.RequiredItems = new();
            this.RequiredCargoId = new();
            this.LevelRequirements = new();
            this.AchievementRequirements = new();
            this.RequiredKnowledges = new();
            this.BlockingKnowledges = new();
        }
    }
}
