// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WindParamsDesc
    {
        [DataMember(Name = "id")]
        public int Id;
        [DataMember(Name = "scale")]
        public double Scale;
        [DataMember(Name = "weight")]
        public double Weight;
        [DataMember(Name = "cycle_sec")]
        public ulong CycleSec;

        public WindParamsDesc(
            int Id,
            double Scale,
            double Weight,
            ulong CycleSec
        )
        {
            this.Id = Id;
            this.Scale = Scale;
            this.Weight = Weight;
            this.CycleSec = CycleSec;
        }

        public WindParamsDesc()
        {
        }
    }
}
