// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldGenResourceDetails
    {
        [DataMember(Name = "clump_id")]
        public int ClumpId;
        [DataMember(Name = "spawns_on_land")]
        public bool SpawnsOnLand;
        [DataMember(Name = "land_elevation_range")]
        public WorldGenVector2Int LandElevationRange;
        [DataMember(Name = "spawns_in_water")]
        public bool SpawnsInWater;
        [DataMember(Name = "water_depth_range")]
        public WorldGenVector2Int WaterDepthRange;
        [DataMember(Name = "max_elevation_delta")]
        public int MaxElevationDelta;

        public WorldGenResourceDetails(
            int ClumpId,
            bool SpawnsOnLand,
            WorldGenVector2Int LandElevationRange,
            bool SpawnsInWater,
            WorldGenVector2Int WaterDepthRange,
            int MaxElevationDelta
        )
        {
            this.ClumpId = ClumpId;
            this.SpawnsOnLand = SpawnsOnLand;
            this.LandElevationRange = LandElevationRange;
            this.SpawnsInWater = SpawnsInWater;
            this.WaterDepthRange = WaterDepthRange;
            this.MaxElevationDelta = MaxElevationDelta;
        }

        public WorldGenResourceDetails()
        {
            this.LandElevationRange = new();
            this.WaterDepthRange = new();
        }
    }
}
