// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldGenResourceDefinition
    {
        [DataMember(Name = "resource_details")]
        public WorldGenResourceDetails ResourceDetails;
        [DataMember(Name = "biomes")]
        public System.Collections.Generic.List<WorldGenResourceBiome> Biomes;

        public WorldGenResourceDefinition(
            WorldGenResourceDetails ResourceDetails,
            System.Collections.Generic.List<WorldGenResourceBiome> Biomes
        )
        {
            this.ResourceDetails = ResourceDetails;
            this.Biomes = Biomes;
        }

        public WorldGenResourceDefinition()
        {
            this.ResourceDetails = new();
            this.Biomes = new();
        }
    }
}
