// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldPlaceBuildingRequest
    {
        [DataMember(Name = "buildings")]
        public System.Collections.Generic.List<BuildingPlacement> Buildings;
        [DataMember(Name = "construction_recipe_id")]
        public int ConstructionRecipeId;
        [DataMember(Name = "dry_run")]
        public bool DryRun;
        [DataMember(Name = "log_results")]
        public bool LogResults;
        [DataMember(Name = "ignore_claims")]
        public bool IgnoreClaims;
        [DataMember(Name = "clear_and_level_ground")]
        public bool ClearAndLevelGround;
        [DataMember(Name = "ignore_dimension_rules")]
        public bool IgnoreDimensionRules;
        [DataMember(Name = "ignore_empire_checks")]
        public bool IgnoreEmpireChecks;

        public WorldPlaceBuildingRequest(
            System.Collections.Generic.List<BuildingPlacement> Buildings,
            int ConstructionRecipeId,
            bool DryRun,
            bool LogResults,
            bool IgnoreClaims,
            bool ClearAndLevelGround,
            bool IgnoreDimensionRules,
            bool IgnoreEmpireChecks
        )
        {
            this.Buildings = Buildings;
            this.ConstructionRecipeId = ConstructionRecipeId;
            this.DryRun = DryRun;
            this.LogResults = LogResults;
            this.IgnoreClaims = IgnoreClaims;
            this.ClearAndLevelGround = ClearAndLevelGround;
            this.IgnoreDimensionRules = IgnoreDimensionRules;
            this.IgnoreEmpireChecks = IgnoreEmpireChecks;
        }

        public WorldPlaceBuildingRequest()
        {
            this.Buildings = new();
        }
    }
}
