// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldGenRiverGenerationSettings
    {
        [DataMember(Name = "radius")]
        public int Radius;
        [DataMember(Name = "depth_curve")]
        public WorldGenAnimationCurve DepthCurve;
        [DataMember(Name = "erosion")]
        public float Erosion;
        [DataMember(Name = "min_lake_circumference")]
        public int MinLakeCircumference;
        [DataMember(Name = "pathfinding_node_limit")]
        public int PathfindingNodeLimit;
        [DataMember(Name = "pathfinding_costs")]
        public System.Collections.Generic.List<WorldGenRiverPathfindingCosts> PathfindingCosts;

        public WorldGenRiverGenerationSettings(
            int Radius,
            WorldGenAnimationCurve DepthCurve,
            float Erosion,
            int MinLakeCircumference,
            int PathfindingNodeLimit,
            System.Collections.Generic.List<WorldGenRiverPathfindingCosts> PathfindingCosts
        )
        {
            this.Radius = Radius;
            this.DepthCurve = DepthCurve;
            this.Erosion = Erosion;
            this.MinLakeCircumference = MinLakeCircumference;
            this.PathfindingNodeLimit = PathfindingNodeLimit;
            this.PathfindingCosts = PathfindingCosts;
        }

        public WorldGenRiverGenerationSettings()
        {
            this.DepthCurve = new();
            this.PathfindingCosts = new();
        }
    }
}
