// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class ClosedListingState
    {
        [DataMember(Name = "entity_id")]
        public ulong EntityId;
        [DataMember(Name = "owner_entity_id")]
        public ulong OwnerEntityId;
        [DataMember(Name = "claim_entity_id")]
        public ulong ClaimEntityId;
        [DataMember(Name = "item_stack")]
        public ItemStack ItemStack;
        [DataMember(Name = "timestamp")]
        public SpacetimeDB.Timestamp Timestamp;

        public ClosedListingState(
            ulong EntityId,
            ulong OwnerEntityId,
            ulong ClaimEntityId,
            ItemStack ItemStack,
            SpacetimeDB.Timestamp Timestamp
        )
        {
            this.EntityId = EntityId;
            this.OwnerEntityId = OwnerEntityId;
            this.ClaimEntityId = ClaimEntityId;
            this.ItemStack = ItemStack;
            this.Timestamp = Timestamp;
        }

        public ClosedListingState()
        {
            this.ItemStack = new();
        }
    }
}
