// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class KnowledgePillarShapingStateHandle : RemoteTableHandle<EventContext, KnowledgePillarShapingState>
        {
            protected override string RemoteTableName => "knowledge_pillar_shaping_state";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(KnowledgePillarShapingState row) => row.EntityId;

                public EntityIdUniqueIndex(KnowledgePillarShapingStateHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal KnowledgePillarShapingStateHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(KnowledgePillarShapingState row) => row.EntityId;
        }

        public readonly KnowledgePillarShapingStateHandle KnowledgePillarShapingState;
    }
}
