// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit 080c501f238afc5fc0ccaedf8742ff4fe306727a).

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class OnDurabilityZeroTimerHandle : RemoteTableHandle<EventContext, OnDurabilityZeroTimer>
        {
            protected override string RemoteTableName => "on_durability_zero_timer";

            public sealed class PlayerEntityIdIndex : BTreeIndexBase<ulong>
            {
                protected override ulong GetKey(OnDurabilityZeroTimer row) => row.PlayerEntityId;

                public PlayerEntityIdIndex(OnDurabilityZeroTimerHandle table) : base(table) { }
            }

            public readonly PlayerEntityIdIndex PlayerEntityId;

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(OnDurabilityZeroTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(OnDurabilityZeroTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal OnDurabilityZeroTimerHandle(DbConnection conn) : base(conn)
            {
                PlayerEntityId = new(this);
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(OnDurabilityZeroTimer row) => row.ScheduledId;
        }

        public readonly OnDurabilityZeroTimerHandle OnDurabilityZeroTimer;
    }
}
